'use strict';

// race/element on all cards. Heroes = human only.
// range='melee'|'ranged', hpReg=체력회복/턴, nrgReg=에너지회복/턴
// bonusTrigger: {on:'attack'|'hit'|'skill'|'kill', chance:0~1, effect:'...', desc:'...'}
// === HERO CARDS: 3 roles × 6 elements = 18 ===
// Base: 전사(atk7,hp45,def5,spd3,rage5,nrg3,luck3,eva1,meva2,hpReg3,nrgReg1)
//       궁수(atk9,hp22,def1,spd8,rage4,nrg5,luck7,eva6,meva2,hpReg1,nrgReg2)
//       마법사(atk4,hp28,def2,spd5,rage2,nrg12,luck5,eva3,meva8,hpReg2,nrgReg5)
// Element bonus: 불(atk+2,rage+2) 물(hp+8,hpReg+1) 전기(spd+3,eva+2) 땅(hp+5,def+2) 암흑(atk+1,luck+3) 신성(nrg+3,meva+2)
RoF.Data.UNITS = Object.freeze([
  // ── 근접 전사 ──
  {id:'h_m_fire',name:'근접 전사',icon:'⚔️',type:'전사',role:'attack',range:'melee',race:'human',element:'fire',
    atk:9,hp:45,def:5,spd:3,rage:7,nrg:3,luck:3,eva:1,meva:2,hpReg:3,nrgReg:1,
    skill:'frenzy',skillType:'passive',skillChance:1,skillNrg:0,skillDesc:'[패시브] 광기: HP50%↓시 공격2배',
    bonusTrigger:{on:'attack',chance:.2,effect:'cleave',desc:'20% 공격시: 인접 적에게 50% 추가데미지'},rarity:'bronze'},
  {id:'h_m_water',name:'근접 전사',icon:'⚔️',type:'전사',role:'defense',range:'melee',race:'human',element:'water',
    atk:7,hp:53,def:5,spd:3,rage:5,nrg:3,luck:3,eva:1,meva:2,hpReg:4,nrgReg:1,
    skill:'taunt',skillType:'passive',skillChance:1,skillNrg:0,skillDesc:'[패시브] 도발: 적 공격을 대신 받음',
    bonusTrigger:{on:'hit',chance:.2,effect:'counter',desc:'20% 반격: 피격시 공격력50% 반격'},rarity:'bronze'},
  {id:'h_m_lightning',name:'근접 전사',icon:'⚔️',type:'전사',role:'attack',range:'melee',race:'human',element:'lightning',
    atk:7,hp:45,def:5,spd:6,rage:5,nrg:3,luck:3,eva:3,meva:2,hpReg:3,nrgReg:1,
    skill:'first_strike',skillType:'passive',skillChance:1,skillNrg:0,skillDesc:'[패시브] 선제: 항상 먼저 공격',
    bonusTrigger:{on:'attack',chance:.25,effect:'double_arrow',desc:'25% 연격: 공격시 2회 타격'},rarity:'bronze'},
  {id:'h_m_earth',name:'근접 전사',icon:'⚔️',type:'전사',role:'defense',range:'melee',race:'human',element:'earth',
    atk:7,hp:50,def:7,spd:3,rage:5,nrg:3,luck:3,eva:1,meva:2,hpReg:3,nrgReg:1,
    skill:'armor',skillType:'passive',skillChance:1,skillNrg:0,skillDesc:'[패시브] 방어: 받는 피해 -3',
    bonusTrigger:{on:'hit',chance:.2,effect:'thorns',desc:'20% 가시: 피격시 공격자에게 3데미지'},rarity:'bronze'},
  {id:'h_m_dark',name:'근접 전사',icon:'⚔️',type:'전사',role:'attack',range:'melee',race:'human',element:'dark',
    atk:8,hp:45,def:5,spd:3,rage:5,nrg:3,luck:6,eva:1,meva:2,hpReg:3,nrgReg:1,
    skill:'life_steal',skillType:'passive',skillChance:.5,skillNrg:0,skillDesc:'[패시브 50%] 생명흡수: 피해100%회복',
    bonusTrigger:{on:'kill',chance:.4,effect:'soul_harvest',desc:'40% 처치시: 공격력+3 영구'},rarity:'bronze'},
  {id:'h_m_holy',name:'근접 전사',icon:'⚔️',type:'전사',role:'defense',range:'melee',race:'human',element:'holy',
    atk:7,hp:45,def:5,spd:3,rage:5,nrg:6,luck:3,eva:1,meva:4,hpReg:3,nrgReg:1,
    skill:'heal_self',skillType:'active',skillChance:.9,skillNrg:2,skillDesc:'[액티브 90%] 신성: HP4회복 (에너지2)',
    bonusTrigger:{on:'skill',chance:.2,effect:'divine_shield',desc:'20% 비전 발동 시: 다음 피해 1회 무효'},rarity:'bronze'},
  // ── 원거리 궁수 ──
  {id:'h_r_fire',name:'원거리 궁수',icon:'🏹',type:'사수',role:'attack',range:'ranged',race:'human',element:'fire',
    atk:11,hp:22,def:1,spd:8,rage:6,nrg:5,luck:7,eva:6,meva:2,hpReg:1,nrgReg:2,
    skill:'aoe',skillType:'active',skillChance:.6,skillNrg:4,skillDesc:'[액티브 60%] 화살비: 적전체 3데미지 (에너지4)',
    bonusTrigger:{on:'skill',chance:.25,effect:'ignite',desc:'25% 비전 발동 시: 대상 2턴 화상(턴당3)'},rarity:'bronze'},
  {id:'h_r_water',name:'원거리 궁수',icon:'🏹',type:'사수',role:'defense',range:'ranged',race:'human',element:'water',
    atk:9,hp:30,def:1,spd:8,rage:4,nrg:5,luck:7,eva:6,meva:2,hpReg:2,nrgReg:2,
    skill:'freeze',skillType:'active',skillChance:.5,skillNrg:5,skillDesc:'[액티브 50%] 빙결: 1턴 행동불가 (에너지5)',
    bonusTrigger:{on:'attack',chance:.15,effect:'frostbite',desc:'15% 공격시: 대상 스피드-3'},rarity:'bronze'},
  {id:'h_r_lightning',name:'원거리 궁수',icon:'🏹',type:'사수',role:'attack',range:'ranged',race:'human',element:'lightning',
    atk:9,hp:22,def:1,spd:11,rage:4,nrg:5,luck:7,eva:8,meva:2,hpReg:1,nrgReg:2,
    skill:'pierce',skillType:'passive',skillChance:1,skillNrg:0,skillDesc:'[패시브] 관통: 방어무시',
    bonusTrigger:{on:'attack',chance:.2,effect:'headshot',desc:'20% 공격시: 대상 HP 10% 즉사'},rarity:'bronze'},
  {id:'h_r_earth',name:'원거리 궁수',icon:'🏹',type:'사수',role:'defense',range:'ranged',race:'human',element:'earth',
    atk:9,hp:27,def:3,spd:8,rage:4,nrg:5,luck:7,eva:6,meva:2,hpReg:1,nrgReg:2,
    skill:'armor',skillType:'passive',skillChance:1,skillNrg:0,skillDesc:'[패시브] 위장: 받는 피해 -3',
    bonusTrigger:{on:'hit',chance:.2,effect:'thorns',desc:'20% 반격: 피격시 독가시 3데미지'},rarity:'bronze'},
  {id:'h_r_dark',name:'원거리 궁수',icon:'🏹',type:'사수',role:'attack',range:'ranged',race:'human',element:'dark',
    atk:10,hp:22,def:1,spd:8,rage:4,nrg:5,luck:10,eva:6,meva:2,hpReg:1,nrgReg:2,
    skill:'crit',skillType:'passive',skillChance:.3,skillNrg:0,skillDesc:'[패시브 30%] 급소: 3배 데미지',
    bonusTrigger:{on:'kill',chance:.4,effect:'stealth',desc:'40% 처치시: 다음턴 회피 100%'},rarity:'bronze'},
  {id:'h_r_holy',name:'원거리 궁수',icon:'🏹',type:'사수',role:'attack',range:'ranged',race:'human',element:'holy',
    atk:9,hp:22,def:1,spd:8,rage:4,nrg:8,luck:7,eva:6,meva:4,hpReg:1,nrgReg:2,
    skill:'first_strike',skillType:'passive',skillChance:1,skillNrg:0,skillDesc:'[패시브] 선제: 항상 먼저 공격',
    bonusTrigger:{on:'attack',chance:.2,effect:'double_arrow',desc:'20% 쌍발: 공격시 2회 타격'},rarity:'bronze'},
  // ── 지원 마법사 ──
  {id:'h_s_fire',name:'지원 마법사',icon:'🔮',type:'마법사',role:'support',range:'ranged',race:'human',element:'fire',
    atk:6,hp:28,def:2,spd:5,rage:4,nrg:12,luck:5,eva:3,meva:8,hpReg:2,nrgReg:5,
    skill:'aoe',skillType:'active',skillChance:.7,skillNrg:4,skillDesc:'[액티브 70%] 화염: 적전체 3데미지 (에너지4)',
    bonusTrigger:{on:'skill',chance:.25,effect:'ignite',desc:'25% 비전 발동 시: 대상 2턴 화상(턴당3)'},rarity:'bronze'},
  {id:'h_s_water',name:'지원 마법사',icon:'🔮',type:'마법사',role:'support',range:'ranged',race:'human',element:'water',
    atk:4,hp:36,def:2,spd:5,rage:2,nrg:12,luck:5,eva:3,meva:8,hpReg:3,nrgReg:5,
    skill:'heal_ally',skillType:'active',skillChance:.8,skillNrg:3,skillDesc:'[액티브 80%] 치유: 아군 HP5 회복 (에너지3)',
    bonusTrigger:{on:'skill',chance:.3,effect:'group_heal',desc:'30% 비전 발동 시: 아군 전체 HP2 회복'},rarity:'bronze'},
  {id:'h_s_lightning',name:'지원 마법사',icon:'🔮',type:'마법사',role:'support',range:'ranged',race:'human',element:'lightning',
    atk:4,hp:28,def:2,spd:8,rage:2,nrg:12,luck:5,eva:5,meva:8,hpReg:2,nrgReg:5,
    skill:'inspire',skillType:'active',skillChance:.7,skillNrg:4,skillDesc:'[액티브 70%] 전기충전: 아군 전체 공격+2 (에너지4)',
    bonusTrigger:{on:'skill',chance:.25,effect:'arcane_burst',desc:'25% 비전 발동 시: 적전체 2추가데미지'},rarity:'bronze'},
  {id:'h_s_earth',name:'지원 마법사',icon:'🔮',type:'마법사',role:'support',range:'ranged',race:'human',element:'earth',
    atk:4,hp:33,def:4,spd:5,rage:2,nrg:12,luck:5,eva:3,meva:8,hpReg:2,nrgReg:5,
    skill:'mass_heal',skillType:'active',skillChance:.8,skillNrg:4,skillDesc:'[액티브 80%] 대치유: 아군전체 HP3 (에너지4)',
    bonusTrigger:{on:'skill',chance:.2,effect:'bless',desc:'20% 비전 발동 시: 랜덤 아군 보호막+3'},rarity:'bronze'},
  {id:'h_s_dark',name:'지원 마법사',icon:'🔮',type:'마법사',role:'support',range:'ranged',race:'human',element:'dark',
    atk:5,hp:28,def:2,spd:5,rage:2,nrg:12,luck:8,eva:3,meva:8,hpReg:2,nrgReg:5,
    skill:'drain',skillType:'passive',skillChance:.7,skillNrg:0,skillDesc:'[패시브 70%] 흡수: 피해50%회복',
    bonusTrigger:{on:'kill',chance:.35,effect:'soul_harvest',desc:'35% 처치시: 공격력+3 영구'},rarity:'bronze'},
  {id:'h_s_holy',name:'지원 마법사',icon:'🔮',type:'마법사',role:'support',range:'ranged',race:'human',element:'holy',
    atk:4,hp:28,def:2,spd:5,rage:2,nrg:15,luck:5,eva:3,meva:10,hpReg:2,nrgReg:5,
    skill:'heal_ally',skillType:'active',skillChance:.9,skillNrg:3,skillDesc:'[액티브 90%] 신성치유: 아군 HP6 회복 (에너지3)',
    bonusTrigger:{on:'skill',chance:.25,effect:'group_heal',desc:'25% 비전 발동 시: 아군 전체 HP3 회복'},rarity:'bronze'},
  // ══════════════════════════════════
  // ── RECRUITABLE UNITS (선술집/전투 중 획득) ──
  // ══════════════════════════════════
  // ── BRONZE (10) ──
  {id:'militia',name:'민병',icon:'🗡️',type:'전사',role:'attack',range:'melee',race:'human',element:'earth',
    atk:5,hp:28,def:3,spd:3,rage:4,nrg:2,luck:2,eva:1,meva:1,hpReg:1,nrgReg:1,
    skill:'none',skillType:'passive',skillChance:0,skillNrg:0,skillDesc:'기본 공격만 수행',
    bonusTrigger:{on:'attack',chance:.15,effect:'cleave',desc:'15% 광역: 인접 적 50% 추가데미지'},rarity:'bronze'},
  {id:'hunter',name:'사냥꾼',icon:'🏹',type:'사수',role:'attack',range:'ranged',race:'human',element:'earth',
    atk:6,hp:18,def:1,spd:6,rage:3,nrg:3,luck:4,eva:4,meva:1,hpReg:0,nrgReg:2,
    skill:'first_strike',skillType:'passive',skillChance:1,skillNrg:0,skillDesc:'[패시브] 선제: 항상 먼저 공격',
    bonusTrigger:{on:'attack',chance:.2,effect:'double_arrow',desc:'20% 쌍발: 공격시 2회 타격'},rarity:'bronze'},
  {id:'apprentice',name:'견습마법사',icon:'📖',type:'마법사',role:'support',range:'ranged',race:'human',element:'fire',
    atk:4,hp:20,def:1,spd:5,rage:2,nrg:8,luck:3,eva:2,meva:5,hpReg:0,nrgReg:3,
    skill:'aoe',skillType:'active',skillChance:.5,skillNrg:4,skillDesc:'[액티브 50%] 화염구: 적전체 2데미지 (에너지4)',
    bonusTrigger:{on:'skill',chance:.15,effect:'ignite',desc:'15% 비전 발동 시: 대상 1턴 화상(턴당2)'},rarity:'bronze'},
  {id:'wolf',name:'늑대',icon:'🐺',type:'야수',role:'attack',range:'melee',race:'beast',element:'earth',
    atk:5,hp:16,def:1,spd:7,rage:6,nrg:3,luck:3,eva:5,meva:1,hpReg:1,nrgReg:1,
    skill:'pack',skillType:'passive',skillChance:1,skillNrg:0,skillDesc:'[패시브] 무리: 야수 1마리당 공격+2',
    bonusTrigger:{on:'kill',chance:.4,effect:'howl',desc:'40% 처치시: 아군 야수 공격+1'},rarity:'bronze'},
  {id:'guard',name:'수비병',icon:'🛡️',type:'전사',role:'defense',range:'melee',race:'human',element:'water',
    atk:3,hp:35,def:5,spd:2,rage:2,nrg:2,luck:2,eva:0,meva:2,hpReg:2,nrgReg:1,
    skill:'taunt',skillType:'passive',skillChance:1,skillNrg:0,skillDesc:'[패시브] 도발: 적 공격을 대신 받음',
    bonusTrigger:{on:'hit',chance:.15,effect:'counter',desc:'15% 반격: 피격시 공격력50% 반격'},rarity:'bronze'},
  {id:'rogue',name:'도적',icon:'🗡️',type:'사수',role:'attack',range:'ranged',race:'human',element:'dark',
    atk:6,hp:16,def:0,spd:8,rage:5,nrg:4,luck:6,eva:6,meva:1,hpReg:0,nrgReg:2,
    skill:'crit',skillType:'passive',skillChance:.2,skillNrg:0,skillDesc:'[패시브 20%] 급소: 3배 데미지',
    bonusTrigger:{on:'kill',chance:.3,effect:'stealth',desc:'30% 처치시: 다음턴 회피 100%'},rarity:'bronze'},
  {id:'herbalist',name:'약초사',icon:'🌿',type:'마법사',role:'support',range:'ranged',race:'human',element:'earth',
    atk:2,hp:22,def:1,spd:4,rage:1,nrg:9,luck:3,eva:2,meva:4,hpReg:2,nrgReg:3,
    skill:'heal_ally',skillType:'active',skillChance:.7,skillNrg:3,skillDesc:'[액티브 70%] 약초치유: 아군 HP4 회복 (에너지3)',
    bonusTrigger:{on:'skill',chance:.2,effect:'group_heal',desc:'20% 비전 발동 시: 아군 전체 HP1 회복'},rarity:'bronze'},
  {id:'lancer',name:'창병',icon:'🔱',type:'전사',role:'attack',range:'melee',race:'human',element:'lightning',
    atk:6,hp:24,def:2,spd:5,rage:4,nrg:3,luck:3,eva:3,meva:1,hpReg:1,nrgReg:1,
    skill:'first_strike',skillType:'passive',skillChance:1,skillNrg:0,skillDesc:'[패시브] 선제: 항상 먼저 공격',
    bonusTrigger:{on:'attack',chance:.2,effect:'cleave',desc:'20% 관통: 뒤열 적에게 50% 추가데미지'},rarity:'bronze'},
  {id:'crossbow',name:'석궁병',icon:'🎯',type:'사수',role:'attack',range:'ranged',race:'human',element:'fire',
    atk:7,hp:17,def:1,spd:4,rage:3,nrg:3,luck:3,eva:2,meva:1,hpReg:0,nrgReg:2,
    skill:'pierce',skillType:'passive',skillChance:1,skillNrg:0,skillDesc:'[패시브] 관통: 방어무시',
    bonusTrigger:{on:'attack',chance:.1,effect:'headshot',desc:'10% 공격시: 대상 HP 10% 즉사'},rarity:'bronze'},
  {id:'fire_spirit',name:'불꽃정령',icon:'🔥',type:'야수',role:'attack',range:'ranged',race:'spirit',element:'fire',
    atk:5,hp:14,def:0,spd:7,rage:4,nrg:6,luck:4,eva:4,meva:3,hpReg:0,nrgReg:3,
    skill:'aoe',skillType:'active',skillChance:.5,skillNrg:3,skillDesc:'[액티브 50%] 불꽃: 적전체 2데미지 (에너지3)',
    bonusTrigger:{on:'skill',chance:.2,effect:'ignite',desc:'20% 비전 발동 시: 대상 1턴 화상(턴당2)'},rarity:'bronze'},
  // ── SILVER (7) ──
  {id:'knight',name:'기사',icon:'⚜️',type:'전사',role:'defense',range:'melee',race:'human',element:'holy',
    atk:7,hp:42,def:6,spd:4,rage:5,nrg:4,luck:4,eva:2,meva:4,hpReg:3,nrgReg:2,
    skill:'taunt',skillType:'passive',skillChance:1,skillNrg:0,skillDesc:'[패시브] 도발: 적 공격을 대신 받음',
    bonusTrigger:{on:'hit',chance:.25,effect:'counter',desc:'25% 반격: 피격시 공격력50% 반격'},rarity:'silver'},
  {id:'assassin',name:'암살자',icon:'🗡️',type:'사수',role:'attack',range:'ranged',race:'human',element:'dark',
    atk:12,hp:20,def:1,spd:10,rage:7,nrg:5,luck:12,eva:9,meva:3,hpReg:0,nrgReg:3,
    skill:'crit',skillType:'passive',skillChance:.3,skillNrg:0,skillDesc:'[패시브 30%] 급소: 3배 데미지',
    bonusTrigger:{on:'kill',chance:.5,effect:'stealth',desc:'50% 처치시: 다음턴 회피 100%'},rarity:'silver'},
  {id:'pyromancer',name:'화염술사',icon:'🔥',type:'마법사',role:'attack',range:'ranged',race:'human',element:'fire',
    atk:10,hp:22,def:1,spd:6,rage:5,nrg:12,luck:5,eva:3,meva:6,hpReg:0,nrgReg:4,
    skill:'aoe',skillType:'active',skillChance:.7,skillNrg:4,skillDesc:'[액티브 70%] 화염폭발: 적전체 4데미지 (에너지4)',
    bonusTrigger:{on:'skill',chance:.3,effect:'ignite',desc:'30% 비전 발동 시: 전체 2턴 화상(턴당3)'},rarity:'silver'},
  {id:'cryomancer',name:'빙결술사',icon:'❄️',type:'마법사',role:'defense',range:'ranged',race:'human',element:'water',
    atk:6,hp:28,def:2,spd:6,rage:3,nrg:12,luck:5,eva:3,meva:8,hpReg:2,nrgReg:4,
    skill:'freeze',skillType:'active',skillChance:.6,skillNrg:5,skillDesc:'[액티브 60%] 빙결: 1턴 행동불가 (에너지5)',
    bonusTrigger:{on:'attack',chance:.2,effect:'frostbite',desc:'20% 공격시: 대상 스피드-3'},rarity:'silver'},
  {id:'berserker',name:'광전사',icon:'🪓',type:'전사',role:'attack',range:'melee',race:'human',element:'fire',
    atk:11,hp:32,def:2,spd:6,rage:10,nrg:4,luck:5,eva:3,meva:1,hpReg:1,nrgReg:2,
    skill:'frenzy',skillType:'passive',skillChance:1,skillNrg:0,skillDesc:'[패시브] 광기: HP50%↓시 공격2배',
    bonusTrigger:{on:'attack',chance:.25,effect:'cleave',desc:'25% 공격시: 인접 적에게 50% 추가데미지'},rarity:'silver'},
  {id:'priest',name:'사제',icon:'✝️',type:'마법사',role:'support',range:'ranged',race:'human',element:'holy',
    atk:3,hp:30,def:2,spd:5,rage:2,nrg:14,luck:6,eva:2,meva:9,hpReg:3,nrgReg:5,
    skill:'mass_heal',skillType:'active',skillChance:.8,skillNrg:4,skillDesc:'[액티브 80%] 대치유: 아군전체 HP4 (에너지4)',
    bonusTrigger:{on:'skill',chance:.25,effect:'bless',desc:'25% 비전 발동 시: 랜덤 아군 보호막+3'},rarity:'silver'},
  {id:'thunderbird',name:'썬더버드',icon:'🦅',type:'야수',role:'attack',range:'ranged',race:'beast',element:'lightning',
    atk:9,hp:20,def:1,spd:11,rage:5,nrg:6,luck:6,eva:8,meva:3,hpReg:0,nrgReg:3,
    skill:'first_strike',skillType:'passive',skillChance:1,skillNrg:0,skillDesc:'[패시브] 선제: 항상 먼저 공격',
    bonusTrigger:{on:'attack',chance:.2,effect:'double_arrow',desc:'20% 연격: 공격시 2회 타격'},rarity:'silver'},
  // ── GOLD (5) ──
  {id:'paladin',name:'성기사',icon:'⚜️',type:'전사',role:'defense',range:'melee',race:'human',element:'holy',
    atk:10,hp:55,def:7,spd:4,rage:5,nrg:8,luck:5,eva:2,meva:7,hpReg:4,nrgReg:3,
    skill:'heal_self',skillType:'active',skillChance:.9,skillNrg:2,skillDesc:'[액티브 90%] 신성: HP6회복 (에너지2)',
    bonusTrigger:{on:'skill',chance:.25,effect:'divine_shield',desc:'25% 비전 발동 시: 다음 피해 1회 무효'},rarity:'gold'},
  {id:'archmage',name:'대마법사',icon:'🌟',type:'마법사',role:'attack',range:'ranged',race:'human',element:'lightning',
    atk:14,hp:22,def:1,spd:8,rage:4,nrg:18,luck:8,eva:4,meva:10,hpReg:0,nrgReg:6,
    skill:'double_cast',skillType:'active',skillChance:.5,skillNrg:6,skillDesc:'[액티브 50%] 더블캐스트: 2회공격 (에너지6)',
    bonusTrigger:{on:'skill',chance:.25,effect:'arcane_burst',desc:'25% 비전 발동 시: 적전체 3추가데미지'},rarity:'gold'},
  {id:'death_knight',name:'죽음의기사',icon:'💀',type:'전사',role:'attack',range:'melee',race:'undead',element:'dark',
    atk:14,hp:40,def:5,spd:4,rage:10,nrg:6,luck:7,eva:2,meva:5,hpReg:0,nrgReg:2,
    skill:'life_steal',skillType:'passive',skillChance:.6,skillNrg:0,skillDesc:'[패시브 60%] 생명흡수: 피해100%회복',
    bonusTrigger:{on:'kill',chance:.5,effect:'raise_dead',desc:'50% 처치시: 적을 아군 좀비로 소환'},rarity:'gold'},
  {id:'sniper',name:'저격수',icon:'🎯',type:'사수',role:'attack',range:'ranged',race:'human',element:'lightning',
    atk:16,hp:16,def:0,spd:10,rage:4,nrg:7,luck:10,eva:7,meva:2,hpReg:0,nrgReg:3,
    skill:'pierce',skillType:'passive',skillChance:1,skillNrg:0,skillDesc:'[패시브] 관통: 방어무시',
    bonusTrigger:{on:'attack',chance:.25,effect:'headshot',desc:'25% 공격시: 대상 HP 10% 즉사'},rarity:'gold'},
  {id:'phoenix',name:'불사조',icon:'🔶',type:'야수',role:'support',range:'melee',race:'spirit',element:'fire',
    atk:9,hp:32,def:3,spd:6,rage:5,nrg:8,luck:8,eva:5,meva:7,hpReg:4,nrgReg:4,
    skill:'rebirth',skillType:'passive',skillChance:1,skillNrg:0,skillDesc:'[패시브] 부활: 첫사망시 HP50%부활',
    bonusTrigger:{on:'hit',chance:.25,effect:'flame_aura',desc:'25% 피격시: 공격자에게 5데미지'},rarity:'gold'},
  // ── LEGENDARY (3) ──
  {id:'dragon',name:'드래곤',icon:'🐉',type:'야수',role:'attack',range:'melee',race:'dragon',element:'fire',
    atk:18,hp:50,def:5,spd:5,rage:12,nrg:10,luck:6,eva:2,meva:5,hpReg:3,nrgReg:3,
    skill:'breath',skillType:'active',skillChance:.7,skillNrg:6,skillDesc:'[액티브 70%] 브레스: 전체6데미지 (에너지6)',
    bonusTrigger:{on:'skill',chance:.3,effect:'inferno',desc:'30% 비전 발동 시: 전체 화상 2턴(턴당3)'},rarity:'legendary'},
  {id:'lich',name:'리치',icon:'👻',type:'마법사',role:'attack',range:'ranged',race:'undead',element:'dark',
    atk:15,hp:30,def:2,spd:7,rage:6,nrg:20,luck:8,eva:5,meva:12,hpReg:0,nrgReg:7,
    skill:'drain',skillType:'passive',skillChance:.8,skillNrg:0,skillDesc:'[패시브 80%] 흡수: 피해50%회복',
    bonusTrigger:{on:'kill',chance:.5,effect:'raise_dead',desc:'50% 처치시: 적을 아군 해골로 소환'},rarity:'legendary'},
  {id:'archangel',name:'대천사',icon:'👼',type:'전사',role:'defense',range:'melee',race:'celestial',element:'holy',
    atk:14,hp:60,def:8,spd:6,rage:5,nrg:12,luck:8,eva:4,meva:10,hpReg:5,nrgReg:4,
    skill:'mass_heal',skillType:'active',skillChance:.9,skillNrg:5,skillDesc:'[액티브 90%] 천상치유: 아군전체 HP5 (에너지5)',
    bonusTrigger:{on:'skill',chance:.3,effect:'divine_shield',desc:'30% 비전 발동 시: 아군 전체 1회 피해무효'},rarity:'legendary'},
  // ── DIVINE (1) ──
  {id:'titan',name:'번개 타이탄',icon:'⚡',type:'거인',role:'attack',range:'melee',race:'titan',element:'lightning',
    atk:22,hp:70,def:6,spd:8,rage:15,nrg:15,luck:10,eva:5,meva:8,hpReg:5,nrgReg:5,
    skill:'breath',skillType:'active',skillChance:.8,skillNrg:5,skillDesc:'[액티브 80%] 뇌격: 전체8데미지 (에너지5)',
    bonusTrigger:{on:'attack',chance:.3,effect:'double_arrow',desc:'30% 공격시: 번개 연쇄 2회 타격'},rarity:'divine'},
]);

// 호환성 레이어
window.UNITS = RoF.Data.UNITS;
