// NOTE: This file must load before other 5x_game_*.js
RoF.Game = RoF.Game || {};

// Game Core (기본 속성 + core 메서드)
// Generated by docs/_split_game.py — Phase 4
// DO NOT hand-edit keys — edit in original and re-run splitter if needed.

RoF.__gameKeys = RoF.__gameKeys || new Set();
(function(keys){
  for (const k of keys) {
    if (RoF.__gameKeys.has(k)) {
      console.error('[Game] 중복 키 감지:', k);
      RoF.__gameKeyError = true;
    }
    RoF.__gameKeys.add(k);
  }
})(["round", "hp", "maxHp", "gold", "xp", "level", "honor", "deck", "relics", "maxDeck", "battleSpeed", "battleRunning", "skipReq", "_slowMo", "battleMultiplier", "load", "persist", "logout", "cardXpNext", "giveCardXp", "giveCardHonor", "getHeroLevel", "getActionPoints", "getTotalHonor", "checkTutorial"]);

Object.assign(RoF.Game, {
  round:0,hp:3,maxHp:3,gold:0,xp:0,level:1,honor:0,deck:[],relics:[],maxDeck:8,
  battleSpeed:500,battleRunning:false,skipReq:false,_slowMo:false,battleMultiplier:1,

  load(s){
    Object.assign(this,{round:s.round||0,hp:s.hp||3,maxHp:s.maxHp||3,gold:s.gold||2,
      deck:s.deck||[],relics:s.relics||[],ownedRelics:s.ownedRelics||[],ownedSkills:s.ownedSkills||[],heroBaseId:s.heroBaseId||'h_m_fire',bestRound:s.bestRound||0,totalWins:s.totalWins||0,totalGames:s.totalGames||0,leaguePoints:s.leaguePoints||0,buildings:s.buildings||{},tutStep:s.tutStep||0,companionName:s.companionName||'동료',blessings:s.blessings||0,winStreak:s.winStreak||0,tavernSlots:s.tavernSlots||null,tavernDate:s.tavernDate||null,savedFormations:s.savedFormations||[]});
    this.deck.forEach(c=>{if(!c.equips)c.equips=[];if(!c.maxHp)c.maxHp=c.hp;if(!c.xp)c.xp=0;if(!c.honor)c.honor=0;if(!c.level)c.level=1;if(c.shield==null)c.shield=0;if(c.meva==null)c.meva=0;if(c.hpReg==null)c.hpReg=0;if(c.nrgReg==null)c.nrgReg=0;if(!c.range)c.range=(c.type==='사수'||c.type==='마법사')?'ranged':'melee';
      if(!c.growthPts)c.growthPts={atk:0,hp:0,def:0,spd:0,nrg:0,luck:0,eva:0};if(c.freePoints==null)c.freePoints=0;
    });
    this.showMenu();
  },
  persist(){
    if(!Auth.user)return;const db=Auth.db();if(!db[Auth.user])return;
    db[Auth.user].save={round:this.round,hp:this.hp,maxHp:this.maxHp,gold:this.gold,
      deck:this.deck,relics:this.relics,ownedRelics:this.ownedRelics||[],ownedSkills:this.ownedSkills||[],heroBaseId:this.heroBaseId,bestRound:this.bestRound,totalWins:this.totalWins,totalGames:this.totalGames,leaguePoints:this.leaguePoints||0,buildings:this.buildings||{},tutStep:this.tutStep||0,companionName:this.companionName||'동료',blessings:this.blessings||0,winStreak:this.winStreak||0,tavernSlots:this.tavernSlots||null,tavernDate:this.tavernDate||null,savedFormations:this.savedFormations||[]};
    Auth.save(db);
  },
  logout(){this.persist();Auth.user=null;this.battleRunning=false;SFX.bgm(false);
    ['login-id','login-pw','signup-id','signup-pw','signup-pw2'].forEach(id=>{const e=document.getElementById(id);if(e)e.value='';});
    ['login-msg','signup-msg'].forEach(id=>{const e=document.getElementById(id);if(e)e.textContent='';});UI.show('title-screen');},
  // XP/Level is PER CARD, not global
  cardXpNext(card){return (card.level||1)*10;}, // Lv1=10, Lv2=20, Lv3=30...
  giveCardXp(card,xp){
    card.xp=(card.xp||0)+xp;
    let leveled=false;
    while(card.xp>=this.cardXpNext(card)){
      card.xp-=this.cardXpNext(card);
      card.level=(card.level||1)+1;
      card.freePoints=(card.freePoints||0)+5;
      leveled=true;
    }
    return leveled;
  },
  giveCardHonor(card,honor){card.honor=(card.honor||0)+honor;},
  getHeroLevel(){const h=this.deck.find(c=>c.isHero);return h?(h.level||1):1;},
  getActionPoints(){const lv=this.getHeroLevel();if(lv>=50)return 4;if(lv>=10)return 3;if(lv>=2)return 2;return 1;},
  getTotalHonor(){return this.deck.reduce((s,c)=>s+(c.honor||0),0);},

  // ---- MENU ----
  // ── TOWN BUILDINGS ──
  // cost = array[5] for levels 1~5. level 0 = ruins.
  checkTutorial(trigger){
    if(this.tutStep>=this.TUT_STEPS.length)return;
    const step=this.TUT_STEPS[this.tutStep];
    if(step&&step.trigger===trigger){
      setTimeout(()=>this.showTutorial(),300);
    }
  },

  // ---- UPGRADE — now in Castle ----
});

// Expose for legacy onclick="Game.foo()" bindings in HTML strings.
// Same object identity — subsequent 5x_game_*.js augment via Object.assign.
window.Game = RoF.Game;