// Game Town (마을/건물/NPC/튜토리얼)
// Generated by docs/_split_game.py — Phase 4
// DO NOT hand-edit keys — edit in original and re-run splitter if needed.

RoF.__gameKeys = RoF.__gameKeys || new Set();
(function(keys){
  for (const k of keys) {
    if (RoF.__gameKeys.has(k)) {
      console.error('[Game] 중복 키 감지:', k);
      RoF.__gameKeyError = true;
    }
    RoF.__gameKeys.add(k);
  }
})(["BUILDINGS", "NPCS", "getNpc", "renderNpcBar", "getBuildingLv", "initBuildings", "showMenu", "buildBuilding", "upgradeBuilding", "TUT_STEPS", "showTutorial", "tutNext", "tutSkip", "showUpgrade", "getRelicSlots"]);

Object.assign(RoF.Game, {
  // 2026-04-12 밤: 사용자가 design/prototypes/town_editor.html 로 드래그한 좌표 (1376×768 base 기준)
  // 원본: C:/Users/USER/Downloads/slot_coords_edited(2).json → design/refs/town/slot_coords.json
  // x/y = 중심점 % / w/h = 크기 % (container 기준)
  // 디자인 키 매핑: cathedral → church / arena → training
  BUILDINGS:[
    {id:'castle',name:'성',icon:'🏰',desc:'퀘스트 & 동료 단련',cost:[0,30,80,180,400],
      x:52.3,y:25.6,w:22.1,h:51.4,action:'showCastle',
      lvNames:['오두막','목조관저','석조성채','왕의성','왕궁'],
      lvDesc:['Lv1: 기본 단련','Lv2: 단련비용 -10%','Lv3: 단련비용 -20%','Lv4: 등급업 4단계마다','Lv5: 단련 시 보너스+1']},
    {id:'gate',name:'차원의 문',icon:'🚪',desc:'리그 전투 참여',cost:[0,20,55,130,300],
      x:50.7,y:79.7,w:20.3,h:28.6,action:'startBattle',
      lvNames:['나무문','철문','성문','요새문','천공문'],
      lvDesc:['Lv1: 리그 참여 가능','Lv2: 승리 보상+20%','Lv3: 승리 보상+40%','Lv4: 리그점수+20%','Lv5: 전설 보상 확률↑']},
    {id:'forge',name:'대장간',icon:'⚒️',desc:'장비 제작 & 분해',cost:[10,30,75,170,380],
      x:24.1,y:35.2,w:16,h:28.6,action:'showForge',
      lvNames:['모루터','대장간','용광로','마법대장간','신의대장간'],
      lvDesc:['Lv1: 장비 제작 가능','Lv2: 제작비용 -10%','Lv3: 분해 수율 +20%','Lv4: 레어 제작 해금','Lv5: 전설 제작 해금']},
    {id:'shop',name:'상점',icon:'🏪',desc:'비전/유물 구매',cost:[15,40,90,200,450],
      x:74,y:24.6,w:16,h:27.3,action:'showShop',
      lvNames:['노점','잡화점','상점','교역소','대상회'],
      lvDesc:['Lv1: 기본 상점 개점','Lv2: 상품 4→5개','Lv3: 할인 -10%','Lv4: 희귀 상품 등장','Lv5: 전설 상품 등장']},
    {id:'tavern',name:'선술집',icon:'🍺',desc:'용병 고용',cost:[10,30,75,170,380],
      x:37.9,y:51.8,w:16,h:28.6,action:'showTavern',
      lvNames:['주막','선술집','주점','대주점','영웅의전당'],
      lvDesc:['Lv1: 용병 고용 가능','Lv2: 용병 4→5명','Lv3: 고용비 -10%','Lv4: 실버 용병 등장↑','Lv5: 골드 용병 등장↑']},
    {id:'training',name:'콜로세움',icon:'🏟️',desc:'동료 수련 & 경험',cost:[10,25,65,150,350],
      x:83.46,y:133.23,w:18,h:28,action:'showTraining',
      lvNames:['빈터','훈련장','검투장','투기장','콜로세움'],
      lvDesc:['Lv1: 기본 수련 가능','Lv2: 수련 경험+20%','Lv3: 수련 경험+40%','Lv4: 합동 수련 해금','Lv5: 명예 수련 해금']},
    {id:'library',name:'서고',icon:'📋',desc:'전력 편성 & 생명의 서',cost:[5,18,50,120,280],
      x:37.2,y:18.5,w:14.5,h:27.3,action:'showDeckView',
      lvNames:['책장','서재','서고','도서관','대도서관'],
      lvDesc:['Lv1: 전력 편성 & 생명의 서','Lv2: 적 정보 해금','Lv3: 비전 설명 상세화','Lv4: 모의 전투 해금','Lv5: 숨겨진 기록 해금']},
    {id:'church',name:'대성당',icon:'⛪',desc:'치료 & 장례',cost:[8,22,55,130,300],
      x:69.3,y:48.2,w:19,h:37.5,action:'showChurch',
      lvNames:['기도처','예배당','교회','성당','대성당'],
      lvDesc:['Lv1: 치료 & 장례 가능','Lv2: 치료비용 -10%','Lv3: 장례 명예+20%','Lv4: 치료비용 -20%','Lv5: 무료 치료 1회/전투']},
  ],

  // ── BUILDING NPCs (level 1~5) ──
  NPCS:{
    castle:[
      {icon:'👴',name:'늙은 조언자',greet:'영웅이여... 동료를 단련시키시오.',noGold:'골드가 부족하오. 전투에서 벌어오시오.',upgrade:'성이 더 웅장해졌소!'},
      {icon:'🧙',name:'궁정마법사',greet:'오셨군요. 누구를 단련시킬까요?',noGold:'금고가 텅 비었습니다.',upgrade:'마법의 기운이 성에 깃들었습니다.'},
      {icon:'📜',name:'재상',greet:'영웅이시여, 오늘의 전략을 논하시죠.',noGold:'국고가 바닥이옵니다, 전하.',upgrade:'석조 성채의 위엄이 느껴지는군요.'},
      {icon:'rand',pool:[{icon:'🤴',name:'왕자'},{icon:'👸',name:'공주'}],greet:['아버지를 대신하여 환영합니다.','왕녀로서 환영합니다, 영웅이여.'],noGold:'왕실 금고도 한계가 있습니다.',upgrade:'왕의 성에 걸맞은 힘이 깃들었소.'},
      {icon:'rand',pool:[{icon:'👑',name:'왕'},{icon:'👑',name:'여왕'}],greet:['운명의 영웅이여, 왕궁에 오셨소.','운명의 영웅이여, 여왕이 맞이합니다.'],noGold:'왕국의 재정을 먼저 살피시오.',upgrade:'왕궁의 영광이 온 대륙에 퍼지리라.'},
    ],
    gate:[
      {icon:'👦',name:'소년 파수꾼',greet:'어... 안녕하세요! 밖에 무서운 것들이 많아요!',noGold:'',upgrade:'문이 튼튼해졌어요!'},
      {icon:'💂',name:'문지기',greet:'오늘은 누구를 쓰러뜨릴 건가!',noGold:'',upgrade:'철문의 위엄! 적도 함부로 못 오겠지.'},
      {icon:'⚔️',name:'근위대장',greet:'성문을 열겠습니다. 무운을 빕니다!',noGold:'',upgrade:'성문이 한층 견고해졌습니다.'},
      {icon:'🛡️',name:'성문장',greet:'영웅이시여, 출전 준비가 되셨습니까?',noGold:'',upgrade:'요새문의 위엄에 적이 떨고 있습니다.'},
      {icon:'🦅',name:'수호기사단장',greet:'천공문이 열립니다. 영광을 안고 돌아오십시오!',noGold:'',upgrade:'천공문... 신의 영역이 가까워지고 있군요.'},
    ],
    forge:[
      {icon:'👦',name:'견습공',greet:'아직 서툴지만... 뭐 만들어 드릴까요?',noGold:'재료 살 골드가 없어요...',upgrade:'드디어 진짜 모루가 생겼어요!'},
      {icon:'🔨',name:'대장장이',greet:'...뭘 만들어야 하지?',noGold:'쇠도 없이 뭘 만들라는 거야.',upgrade:'용광로의 불길이 활활 타오르는군.'},
      {icon:'🔥',name:'화로장인',greet:'좋은 쇠가 필요하군. 뭘 만들까?',noGold:'좋은 재료엔 골드가 필요하지.',upgrade:'마법대장간의 불꽃은 다르지!'},
      {icon:'⚒️',name:'마법대장장이',greet:'마력이 깃든 장비를 만들 수 있소.',noGold:'마법 재료는 공짜가 아니오.',upgrade:'신의 불꽃이 대장간에 내려왔소!'},
      {icon:'🌟',name:'신의대장장이',greet:'신의 불꽃으로 무엇이든 만들어 보이리다.',noGold:'신의 재료조차 골드가 필요하다오.',upgrade:'전설의 대장간이 완성되었소!'},
    ],
    shop:[
      {icon:'👵',name:'행상인',greet:'어머, 손님! 좋은 물건 많아요~',noGold:'에고... 돈이 없으시구먼.',upgrade:'드디어 가게를 차렸어요!'},
      {icon:'🧑',name:'잡화상인',greet:'어서 오세요! 오늘의 추천 상품이 있습니다.',noGold:'외상은 안 됩니다~',upgrade:'상점이 넓어져서 물건이 더 많아졌죠!'},
      {icon:'💰',name:'무역상',greet:'호호, 좋은 눈을 가지셨군요.',noGold:'신용이 필요합니다. 골드로 보여주시죠.',upgrade:'교역로가 열려서 희귀한 물건도 들어옵니다.'},
      {icon:'🎩',name:'대상인',greet:'귀한 분이시군요. 특별한 물건을 보여드리죠.',noGold:'대상인도 외상은 곤란합니다.',upgrade:'대륙 최고의 교역소입니다!'},
      {icon:'👑',name:'왕실상인',greet:'왕실이 보증하는 최상급 물품입니다.',noGold:'왕실에서도 대금은 필요합니다.',upgrade:'대상회의 명성이 대륙을 뒤흔듭니다!'},
    ],
    tavern:[
      {icon:'🧑',name:'주막주인',greet:'어서 와! 마실 것부터 줄까?',noGold:'돈 없으면 물이라도 마셔.',upgrade:'선술집으로 키웠지!'},
      {icon:'🍺',name:'주모',greet:'새 동료를 찾고 있나? 여기 좀 봐!',noGold:'골드가 없으면 구경만 하게.',upgrade:'더 많은 용병들이 모이기 시작했어!'},
      {icon:'🎭',name:'정보상',greet:'쉿... 특별한 용병 정보가 있어.',noGold:'정보도, 용병도 공짜는 없지.',upgrade:'소문이 퍼져서 실력자들이 모여들고 있어.'},
      {icon:'👑',name:'용병단장',greet:'내 수하 중 최정예를 보내주지.',noGold:'최정예에겐 그에 걸맞은 대가가 필요하지.',upgrade:'영웅급 전사들까지 찾아오는군!'},
      {icon:'⚔️',name:'영웅의전당 관리자',greet:'전설의 영웅들이 당신의 부름을 기다립니다.',noGold:'영웅에게도 예우가 필요합니다.',upgrade:'이곳은 이제 대륙 최고의 영웅 집결지입니다.'},
    ],
    training:[
      {icon:'👦',name:'허수아비',greet:'...저를 때려도 됩니다.',noGold:'',upgrade:'드디어 진짜 교관이 왔어요!'},
      {icon:'🗡️',name:'검술교관',greet:'자세가 흐트러졌다! 다시!',noGold:'훈련 장비를 살 골드가 없군.',upgrade:'훈련 시설이 좋아졌군!'},
      {icon:'⚔️',name:'전투사범',greet:'실전처럼 훈련해야 살아남는다.',noGold:'좋은 훈련엔 투자가 필요하다.',upgrade:'검투장이라니... 제대로 단련시키겠다!'},
      {icon:'🛡️',name:'장군',greet:'영웅이여, 오늘의 훈련 메뉴를 정하겠소.',noGold:'군사 훈련에도 예산이 필요하오.',upgrade:'투기장의 함성이 들린다!'},
      {icon:'👑',name:'대원수',greet:'콜로세움에서 최강의 전사를 만들어 보이겠소.',noGold:'최고의 훈련엔 최고의 투자가 필요하오.',upgrade:'전설의 콜로세움이 완성되었소!'},
    ],
    library:[
      {icon:'📖',name:'서생',greet:'아... 조용히 해주세요, 읽는 중이에요.',noGold:'',upgrade:'책이 많아졌어요!'},
      {icon:'🧓',name:'학자',greet:'무엇이 궁금한가? 기록을 찾아보지.',noGold:'',upgrade:'더 많은 지식이 모였군.'},
      {icon:'📚',name:'현자',greet:'지식은 가장 강력한 무기라네.',noGold:'',upgrade:'이 서고의 지식은 대단하군!'},
      {icon:'🔮',name:'대현자',greet:'과거와 미래의 기록이 여기 있다네.',noGold:'',upgrade:'도서관의 마법 기록이 완성되었네!'},
      {icon:'🌟',name:'전지전능의 눈',greet:'모든 것이 보인다... 모든 진실이.',noGold:'',upgrade:'대도서관에 세상의 모든 지식이 담겼도다.'},
    ],
    church:[
      {icon:'🙏',name:'수녀',greet:'신의 축복이 함께하길... 다친 동료가 있나요?',noGold:'기도는 무료입니다... 하지만 치료는...',upgrade:'예배당이 생겼어요!'},
      {icon:'⛪',name:'사제',greet:'신의 은총으로 상처를 치유하겠습니다.',noGold:'헌금이 부족합니다만...',upgrade:'교회의 신성한 힘이 강해졌습니다.'},
      {icon:'📿',name:'주교',greet:'영웅이시여, 동료들의 상처를 보여주십시오.',noGold:'교회도 운영 자금이 필요합니다.',upgrade:'성당의 축복이 온 마을에 퍼집니다.'},
      {icon:'✝️',name:'대주교',greet:'신의 기적으로 어떤 상처도 치유하리다.',noGold:'기적에도 신의 뜻에 맞는 헌금이 필요합니다.',upgrade:'대성당의 빛이 어둠을 물리칩니다!'},
      {icon:'👼',name:'성녀',greet:'영혼의 안식과 치유... 모두 신의 뜻입니다.',noGold:'신께서도 때로는 기다리라 하십니다.',upgrade:'대성당이 완성되니 기적이 일어나는군요.'},
    ],
  },

  getNpc(buildingId){
    const lv=this.getBuildingLv(buildingId)||1;
    const npcs=this.NPCS[buildingId];
    if(!npcs)return{icon:'❓',name:'???',greet:'...',noGold:'',upgrade:'',img:''};
    const raw=npcs[Math.min(lv-1,npcs.length-1)];
    const lvNum=Math.min(lv,npcs.length);
    // Handle random gender NPCs
    if(raw.icon==='rand'&&raw.pool){
      const seed=(Auth.user||'').split('').reduce((s,c)=>s+c.charCodeAt(0),0);
      const pick=raw.pool[seed%raw.pool.length];
      const greet=Array.isArray(raw.greet)?raw.greet[seed%raw.greet.length]:raw.greet;
      const suffix=seed%raw.pool.length===0?'a':'b';
      const img=`img/npc_${buildingId}_${lvNum}${suffix}.png`;
      return{icon:pick.icon,name:pick.name,greet,noGold:raw.noGold,upgrade:raw.upgrade,img};
    }
    const img=`img/npc_${buildingId}_${lvNum}.png`;
    return{...raw,img};
  },

  renderNpcBar(buildingId,contextMsg){
    const npc=this.getNpc(buildingId);
    const msg=contextMsg||npc.greet;
    const iconHtml=npc.img?`<img src="${npc.img}" style="width:56px;height:56px;border-radius:50%;border:2px solid #8b6914;object-fit:cover;">`:`<span style="font-size:2.2rem;">${npc.icon}</span>`;
    return `<div class="npc-bar"><div class="npc-icon">${iconHtml}</div><div class="npc-speech"><div class="npc-name">${npc.name}</div><div class="npc-text">"${msg}"</div></div></div>`;
  },

  getBuildingLv(id){const v=this.buildings[id];if(v===true)return 1;return v||0;},

  initBuildings(){
    if(!this.buildings)this.buildings={};
    this.BUILDINGS.forEach(b=>{
      if(this.buildings[b.id]==null){
        this.buildings[b.id]=b.cost[0]===0?1:0;
      }
      if(this.buildings[b.id]===true)this.buildings[b.id]=1;
      if(this.buildings[b.id]===false)this.buildings[b.id]=0;
    });
  },

  showMenu(){
    UI.show('menu-screen');SFX.bgm('town');
    this.initBuildings();
    const hero=this.deck.find(c=>c.isHero);
    const hLv=hero?(hero.level||1):1;
    const lg=this.getLeague();const lp=this.leaguePoints||0;

    // HUD
    document.getElementById('menu-welcome').textContent=`⭐ ${Auth.user} Lv.${hLv}`;
    document.getElementById('town-league').innerHTML=`<span style="color:${lg.color};">${lg.icon} ${lg.name} (${lp}점)</span>`;
    document.getElementById('town-gold').textContent=this.gold;
    document.getElementById('town-bless').textContent=this.blessings||0;
    // 추가 화폐 표시
    const gemsEl=document.getElementById('town-gems');
    if(gemsEl)gemsEl.textContent=this.gems||0;
    const graceEl=document.getElementById('town-grace');
    if(graceEl)graceEl.textContent=this.divineGrace||0;
    document.getElementById('town-ap').innerHTML=`⚡<span>${this.getActionPoints()}</span>`;
    document.getElementById('town-deck-count').textContent=this.deck.length;
    const injuredCount=this.deck.filter(c=>c.injured&&!c.isHero).length;
    const existingInj=document.getElementById('town-injured');
    if(existingInj)existingInj.remove();
    if(injuredCount>0){
      const injEl=document.createElement('div');injEl.className='th-stat';injEl.id='town-injured';
      injEl.innerHTML=`<span style="color:#ff4444;">⚠ 부상 ${injuredCount}</span>`;
      document.querySelector('.town-hud-right').appendChild(injEl);
    }

    // Stars
    const sky=document.getElementById('town-sky');
    if(!sky.children.length){for(let i=0;i<30;i++){const s=document.createElement('div');s.className='star';s.style.left=Math.random()*100+'%';s.style.top=Math.random()*100+'%';s.style.animationDelay=Math.random()*3+'s';sky.appendChild(s);}}

    // Buildings
    const tc=document.getElementById('town-container');tc.innerHTML='';
    this.BUILDINGS.forEach(b=>{
      const lv=this.getBuildingLv(b.id);
      const built=lv>0;
      const maxLv=b.cost.length;
      const div=document.createElement('div');
      div.className=`town-building ${built?'built':'ruins'}`;
      div.setAttribute('data-id', b.id);
      // 편집기로 설정한 크기(%) 기준 중심점 배치
      div.style.left=b.x+'%';
      div.style.top=b.y+'%';
      div.style.width=(b.w||14)+'%';
      div.style.height=(b.h||28)+'%';
      div.style.transform='translate(-50%,-50%)';
      const lvName=(b.lvNames&&lv>0)?b.lvNames[lv-1]:b.name;
      const castleLv=this.getBuildingLv('castle');
      // 2026-04-12 밤: 새 마을 맵 — img/town/*.png (성벽 내부 cutout) 우선 사용
      const bImg=`img/town/${b.id}.png`;
      const bImgFallback=`img/building_${b.id}.png`;
      if(built){
        const canUpgrade=lv<b.cost.length;
        const upgBlocked=b.id!=='castle'&&lv>=castleLv;
        // 2026-04-12 밤: div 가 편집기 설정 w/h(%) 로 크기 잡음. img 는 div 100% 채움 + contain.
        const imgStyle=`width:100%;height:100%;object-fit:contain;border-radius:0;`;
        div.innerHTML=`<div class="tb-icon" style="width:100%;height:100%;"><img src="${bImg}" onerror="this.src='${bImgFallback}'" style="${imgStyle}"></div><div class="tb-label" style="position:absolute;bottom:-18px;left:50%;transform:translateX(-50%);white-space:nowrap;">${lvName} <span style="font-size:.5rem;color:#ffd700;">Lv.${lv}</span></div>${canUpgrade?`<div class="tb-upgrade" data-bid="${b.id}" style="position:absolute;bottom:-32px;left:50%;transform:translateX(-50%);white-space:nowrap;">${upgBlocked?`🔒 성 Lv.${lv+1} 필요`:`🔨 증축 (${b.cost[lv]}💰)`}</div>`:'<div class="tb-upgrade" style="position:absolute;bottom:-32px;left:50%;transform:translateX(-50%);color:#44ff88;white-space:nowrap;">✅ 최고 경지</div>'}`;
        div.querySelector('.tb-icon').onclick=(e)=>{e.stopPropagation();SFX.play('click');if(this[b.action])this[b.action]();};
        div.querySelector('.tb-label').onclick=(e)=>{e.stopPropagation();SFX.play('click');if(this[b.action])this[b.action]();};
        const upgEl=div.querySelector('.tb-upgrade');
        if(upgEl&&canUpgrade&&!upgBlocked){
          upgEl.onclick=(e)=>{e.stopPropagation();this.upgradeBuilding(b);};
        }
      } else {
        div.innerHTML=`<div class="tb-icon" style="width:70px;height:70px;border:2px dashed rgba(255,255,255,.15);border-radius:10px;display:flex;align-items:center;justify-content:center;background:rgba(0,0,0,.2);"><div style="font-size:1.5rem;opacity:.3;">➕</div></div><div class="tb-label">${b.name}</div><div class="tb-cost">🔨 ${b.cost[0]}💰</div>`;
        div.onclick=()=>this.buildBuilding(b);
      }
      tc.appendChild(div);
    });

    // Walking NPCs (only add once, and only if buildings exist)
    if(!document.querySelector('.town-npc')){
      const npcs=['🚶','🚶‍♂️','🧙','⚔️','🛡️','🏹'];
      const routes=[
        {cls:'walk-right',top:'75%',delay:0},
        {cls:'walk-left',top:'70%',delay:5},
        {cls:'walk-right',top:'82%',delay:10},
        {cls:'walk-left',top:'65%',delay:3},
        {cls:'walk-up',left:'30%',delay:7},
        {cls:'walk-up',left:'70%',delay:12},
      ];
      routes.forEach((r,i)=>{
        const npc=document.createElement('div');npc.className=`town-npc ${r.cls}`;
        npc.textContent=npcs[i%npcs.length];
        if(r.top)npc.style.top=r.top;
        if(r.left)npc.style.left=r.left;
        npc.style.animationDelay=r.delay+'s';
        tc.appendChild(npc);
      });
    }

    // Deck preview
    const md=document.getElementById('menu-deck');md.innerHTML='';
    this.deck.forEach(c=>{const d=mkMini(c);md.appendChild(d);});
    this.persist();
    // Tutorial triggers
    this.checkTutorial('town_first');
    if(this.getBuildingLv('library')>0&&this.tutStep===1)this.checkTutorial('library_built');
    if(this.totalWins+this.totalGames>0&&this.tutStep===5)this.checkTutorial('back_after_first');
    if(this.getBuildingLv('tavern')>0&&this.tutStep===6)this.checkTutorial('tavern_built');
    if(this.deck.some(c=>c.injured&&!c.isHero)&&this.tutStep===11)this.checkTutorial('first_injury');
    if(this.getBuildingLv('church')>0&&this.tutStep===12)this.checkTutorial('church_built');
  },

  buildBuilding(b){
    const cost=b.cost[0];
    if(this.gold<cost){
      UI.modal('건설 불가',`${b.icon} ${b.name} 건설에 ${cost}💰가 필요합니다.\n현재 골드: ${this.gold}💰`,null);
      return;
    }
    UI.modal(`${b.icon} ${b.name} 건설`,`${b.desc}\n\n${b.lvDesc[0]}\n\n건설 비용: ${cost}💰\n현재 골드: ${this.gold}💰\n\n건설하시겠습니까?`,()=>{
      this.gold-=cost;
      this.buildings[b.id]=1;
      SFX.play('build');
      this.persist();this.showMenu();
    });
  },

  upgradeBuilding(b){
    const lv=this.getBuildingLv(b.id);
    const maxLv=b.cost.length;
    if(lv>=maxLv){UI.modal(`${b.icon} ${b.name}`,`이미 최고 경지에 도달하였습니다! (Lv.${lv}/${maxLv})`,null);return;}
    // Castle level requirement: other buildings can't exceed castle level
    const castleLv=this.getBuildingLv('castle');
    if(b.id!=='castle'&&lv>=castleLv){
      UI.modal('🏰 성 증축 필요',`${b.icon} ${b.name}을(를) Lv.${lv+1}로 증축하려면\n먼저 성을 Lv.${lv+1} 이상으로 증축해야 합니다.\n\n현재 성: Lv.${castleLv}`,null);
      return;
    }
    const cost=b.cost[lv];
    const nextDesc=b.lvDesc[lv]||'';
    if(this.gold<cost){
      UI.modal('증축 불가',`${b.icon} ${b.name} Lv.${lv+1} 증축에 ${cost}💰가 필요합니다.\n현재 골드: ${this.gold}💰`,null);
      return;
    }
    UI.modal(`${b.icon} ${b.name} 증축`,`Lv.${lv} → Lv.${lv+1}\n\n${nextDesc}\n\n비용: ${cost}💰\n현재 골드: ${this.gold}💰\n\n증축하시겠습니까?`,()=>{
      this.gold-=cost;
      this.buildings[b.id]=lv+1;
      SFX.play('rarity_up');
      const flash=document.createElement('div');flash.className='upgrade-flash';document.body.appendChild(flash);setTimeout(()=>flash.remove(),600);
      this.persist();this.showMenu();
    });
  },

  TUT_STEPS:[
    {id:0,trigger:'town_first',speaker:'companion',text:'안녕, 나는 {name}. 신께서 당신을 돕도록 보내셨어.\n여기가 우리의 영지인데... 아직 볼품없지?\n먼저 서고를 지어서 우리 전력을 파악하자.',highlight:'library'},
    {id:1,trigger:'library_built',speaker:'companion',text:'좋아, 서고가 생겼네! 여기서 우리 전력과 세상의 적들을 살펴볼 수 있어.\n이제 나무문을 열고 리그에 출전해보자.\n브론즈 리그부터 시작이야. 준비됐지?',highlight:'gate'},
    {id:2,trigger:'first_battle',speaker:'companion',text:'출전할 동료를 고르는 거야. 영웅은 자동 출전!\n내가 옆에서 싸워줄 테니 걱정 마.\n참, 영웅이 쓰러지면 지는 거니까 조심해!'},
    {id:3,trigger:'first_survive',speaker:'companion',text:'해냈어! 라운드를 버텼다!\n이제 행동력을 써서 동료를 소환하거나 전투기술을 익힐 수 있어.\n시간 제한이 있으니까 빨리 판단해!'},
    {id:4,trigger:'first_battle_end',speaker:'companion',text:'첫 전투 끝! 전리품 상자를 잘 골라봐.\n마을로 돌아가서 영지를 발전시키자.\n운명의 왕좌까지... 아직 멀지만 같이 가보자!'},
    {id:5,trigger:'back_after_first',speaker:'companion',text:'골드가 생겼네! 주막을 지어서 함께 싸울 동료를 모집하자.\n강한 전사일수록 더 많은 골드가 필요하지만, 그만한 값어치가 있어.',highlight:'tavern'},
    {id:6,trigger:'tavern_built',speaker:'companion',text:'주막이 열렸어! 여기서 골드를 지불하고 전사들을 영입할 수 있어.\n마음에 드는 동료가 없으면 2골드로 다른 전사를 불러올 수도 있지.',highlight:'tavern'},
    {id:7,trigger:'first_recruit',speaker:'companion',text:'새 동료가 합류했어! 좋아, 점점 강해지고 있어.\n이제 성에 가서 동료들을 단련시켜보자.\n골드를 바치면 더 강하게 성장할 수 있어.',highlight:'castle'},
    {id:8,trigger:'first_upgrade',speaker:'companion',text:'단련 완료! 성장할 때마다 능력치 포인트 5개를 받는 거 알지?\n서고에서 동료를 선택하면 원하는 능력치에 직접 배분할 수 있어.\n어디에 투자할지는 전략이야!',highlight:'library'},
    {id:9,trigger:'first_stat_alloc',speaker:'companion',text:'능력치 배분까지 해냈네! 이제 기본은 다 익혔어.\n참, 건물 위에서 오른쪽 클릭하면 증축할 수 있어.\n건물이 성장하면 더 좋은 혜택이 열린다구!'},
    {id:10,trigger:'first_defeat',speaker:'companion',text:'패전했지만 걱정 마!\n영웅은 신의 축복으로 반드시 되살아나.\n하지만 동료들은... 부상을 입을 수 있어.\n교회에서 치유하거나 장례를 치러줘야 해.'},
    {id:11,trigger:'first_injury',speaker:'companion',text:'부상당한 동료가 있어!\n교회를 세워서 치유하자. 부상 상태로는 출전할 수 없어!',highlight:'church'},
    {id:12,trigger:'church_built',speaker:'companion',text:'교회가 세워졌어! 치료에는 골드가 들지만,\n장례를 치르면 영웅의 명예가 올라가.\n강한 동료는 살리고, 약한 동료는 보내주는 것도 전략이야.',highlight:'church'},
    {id:13,trigger:'reach_silver',speaker:'companion',text:'실버 리그 달성! 대단한데?\n이제부터 진짜 강한 도전자들이 나타날 거야.\n대장간이나 상점도 곧 필요해질 거야. 멈추지 말고 나아가자!'},
  ],

  showTutorial(){
    const step=this.TUT_STEPS.find(s=>s.id===this.tutStep);
    if(!step||this.tutStep>=this.TUT_STEPS.length)return;
    const cName=this.companionName||'동료';
    const comp=this.deck.find(c=>c.isCompanion);
    const cIcon=comp?comp.icon:'🗡️';
    // Resolve speaker
    let speakerLabel=step.speaker;
    if(step.speaker==='companion')speakerLabel=`${cIcon} ${cName}`;
    // Replace {name} in text
    const text=step.text.replace(/\{name\}/g,cName);
    // Create overlay
    const ov=document.createElement('div');ov.className='tut-overlay';ov.id='tut-overlay';
    const box=document.createElement('div');box.className='tut-box';
    box.innerHTML=`<div class="tut-speaker">${speakerLabel}</div>
      <div class="tut-text">${text.replace(/\n/g,'<br>')}</div>
      <div style="display:flex;gap:8px;justify-content:center;">
        <button class="btn btn-s" onclick="Game.tutNext()">확인</button>
        <button class="btn btn-s btn-red" onclick="Game.tutSkip()" style="font-size:.7rem;">튜토리얼 끄기</button>
      </div>`;
    ov.appendChild(box);document.body.appendChild(ov);
    // Highlight building
    if(step.highlight){
      const bEls=document.querySelectorAll('.town-building');
      bEls.forEach(el=>{
        const label=el.querySelector('.tb-label');
        if(label&&label.textContent.includes(this.BUILDINGS.find(b=>b.id===step.highlight)?.name)){
          el.classList.add('tut-highlight');
        }
      });
    }
  },
  tutNext(){
    const ov=document.getElementById('tut-overlay');if(ov)ov.remove();
    document.querySelectorAll('.tut-highlight').forEach(el=>el.classList.remove('tut-highlight'));
    this.tutStep++;this.persist();
  },
  tutSkip(){
    const ov=document.getElementById('tut-overlay');if(ov)ov.remove();
    document.querySelectorAll('.tut-highlight').forEach(el=>el.classList.remove('tut-highlight'));
    this.tutStep=99;this.persist();
  },
  showUpgrade(){this.showCastle();},

  // ---- DECK VIEW (상태확인) ----
  getRelicSlots(){return Math.max(1,Math.floor(this.getHeroLevel()/2));},

  // === LEAGUE SYSTEM ===
});
