// Game Tavern (술집)
// Generated by docs/_split_game.py — Phase 4
// DO NOT hand-edit keys — edit in original and re-run splitter if needed.

RoF.__gameKeys = RoF.__gameKeys || new Set();
(function(keys){
  for (const k of keys) {
    if (RoF.__gameKeys.has(k)) {
      console.error('[Game] 중복 키 감지:', k);
      RoF.__gameKeyError = true;
    }
    RoF.__gameKeys.add(k);
  }
// 2026-04-29: 영웅 = 유저 카드 1장 고정. 영웅 영입 시스템 폐기 (showTavernHero/Entry/genHeroRecruitCards 삭제).
//   - _tavTab 상태도 폐기 (탭 자체 없음)
//   - showTavernUnit 은 호환성 위해 유지 (다른 곳에서 호출), 탭 활성화 코드 제거 후 안내+카드만 갱신
})(["showTavern", "showTavernUnit", "_generateTavernSlots", "_ensureTavernSlots", "genTavernCards", "refreshTavern"]);

Object.assign(RoF.Game, {
  showTavern(){
    UI.show('tavern-screen');
    document.getElementById('tav-name').textContent=`👤 ${Auth.user}`;
    document.getElementById('tav-gold').textContent=this.gold;
    document.getElementById('tav-deck').textContent=this.deck.length;
    // NPC (2026-04-24: noGold 필드 폐기 — 골드 부족 시 별도 안내문)
    const npc=this.getNpc('tavern');
    const msg=this.gold<5?'돈 없으면 물이라도 마시고 가게.':npc.greet;
    const existing=document.getElementById('tav-npc');if(existing)existing.remove();
    document.getElementById('tav-info').insertAdjacentHTML('afterend',`<div id="tav-npc">${this.renderNpcBar('tavern',msg)}</div>`);
    this.showTavernUnit();
  },
  showTavernUnit(){
    document.getElementById('tav-info').textContent='골드를 지불하고 동료를 영입하세요';
    this.genTavernCards();
  },

  // Generate tavern slots (saved to persist)
  // 2026-04-24: 건물 Lv 시스템 폐기 — slot count 4 고정, pickRar 입력에서 tavLv 가중치 제거.
  _generateTavernSlots(){
    const count=4;
    const slots=[];
    const usedIds=new Set();  // P0-1: 같은 선술집 갱신 안에서 동일 유닛 id 중복 금지 (아트 중복 → 저예산 시그널)
    for(let i=0;i<count;i++){
      const r=pickRar(this.getHeroLevel(),'tavern');
      let pool=UNITS.filter(u=>u.rarity===r&&!u.id.startsWith('h_')&&!usedIds.has(u.id));
      // pool 소진 시: 등급 제한 풀고 dedup 유지
      if(!pool.length)pool=UNITS.filter(u=>!u.id.startsWith('h_')&&!usedIds.has(u.id));
      // 그래도 없으면(소규모 DB) 중복 허용 폴백
      if(!pool.length)pool=UNITS.filter(u=>!u.id.startsWith('h_'));
      const b=pool[Math.floor(Math.random()*pool.length)];
      usedIds.add(b.id);
      const cost=({bronze:5,silver:8,gold:12,legendary:18,divine:25})[b.rarity]||5;
      slots.push({...b,uid:uid(),level:1,equips:[],maxHp:b.hp,cost});
    }
    return slots;
  },
  _ensureTavernSlots(){
    // Daily auto-refresh check
    const today=new Date().toDateString();
    if(this.tavernDate!==today||!this.tavernSlots){
      this.tavernSlots=this._generateTavernSlots();
      this.tavernDate=today;
      this.persist();
    }
  },
  genTavernCards(){
    this._ensureTavernSlots();
    const g=document.getElementById('tav-grid');g.innerHTML='';
    this.tavernSlots.forEach((c,idx)=>{
      if(!c){
        // Empty slot (hired already)
        const empty=document.createElement('div');empty.style.cssText='width:200px;min-height:290px;border:2px dashed #333;border-radius:8px;display:flex;align-items:center;justify-content:center;color:#444;font-size:.85rem;';
        empty.textContent='빈 자리';
        g.appendChild(empty);
        return;
      }
      const cost=c.cost||5;
      const el=mkCardElV4(c);  // V4 Illuminated Manuscript (2026-04-20 Step 4)
      const btn=document.createElement('div');btn.style.cssText='text-align:center;margin-top:4px;';
      btn.innerHTML=`<button class="btn btn-s btn-green" ${this.gold<cost||this.deck.length>=this.maxDeck?'disabled':''}>${cost}💰 영입</button>`;
      btn.querySelector('button').onclick=(e)=>{e.stopPropagation();
        if(this.gold<cost||this.deck.length>=this.maxDeck)return;
        this.gold-=cost;
        const hired={...c};delete hired.cost;
        this.deck.push(hired);
        SFX.play('card_reveal');this.checkTutorial('first_recruit');
        if(c.rarity==='legendary'||c.rarity==='divine'){const rv=document.createElement('div');rv.className='tavern-reveal legendary-reveal';document.body.appendChild(rv);setTimeout(()=>rv.remove(),1000);SFX.play('rarity_up');}
        else if(c.rarity==='gold'){const rv=document.createElement('div');rv.className='tavern-reveal gold-reveal';document.body.appendChild(rv);setTimeout(()=>rv.remove(),800);}
        document.getElementById('tav-info').textContent=`✅ ${c.name} 영입 완료!`;
        // Remove from slot
        this.tavernSlots[idx]=null;
        this.persist();this.showTavernUnit();
      };
      const wrap=document.createElement('div');wrap.className='tavern-card-wrap';wrap.appendChild(el);wrap.appendChild(btn);g.appendChild(wrap);
      el.classList.add('tavern-card-inner');el.classList.add('flipping');setTimeout(()=>el.classList.remove('flipping'),600);
    });
  },

  refreshTavern(){
    if(this.gold<2){document.getElementById('tav-info').textContent='⚠️ 골드가 부족합니다!';return;}
    this.gold-=2;
    this.tavernSlots=this._generateTavernSlots();
    SFX.play('click');this.persist();this.showTavernUnit();
  },

  // ---- BATTLE ----
  // One battle = roguelike. Pick cards (by command slots) → fight rounds → all temp stuff resets after.
});
