// Game Deck (덱 보기/도감/카드 상세)
// Generated by docs/_split_game.py — Phase 4
// DO NOT hand-edit keys — edit in original and re-run splitter if needed.

RoF.__gameKeys = RoF.__gameKeys || new Set();
(function(keys){
  for (const k of keys) {
    if (RoF.__gameKeys.has(k)) {
      console.error('[Game] 중복 키 감지:', k);
      RoF.__gameKeyError = true;
    }
    RoF.__gameKeys.add(k);
  }
})(["_dvTab", "showDeckTab", "showCodexTab", "showCodexView", "_codexFilter", "renderCodex", "showCodexDetail", "showDeckView", "equipOwnedSkill", "showDeckCardFocus", "closeDeckCardFocus", "showRelicDetail", "equipSkill"]);

Object.assign(RoF.Game, {
  _dvTab:'deck',
  showDeckTab(){
    this._dvTab='deck';
    document.getElementById('deck-tab').style.display='';
    document.getElementById('codex-tab').style.display='none';
    document.getElementById('tab-deck').style.borderColor='#ffd700';document.getElementById('tab-deck').style.color='#ffd700';
    document.getElementById('tab-codex').style.borderColor='';document.getElementById('tab-codex').style.color='';
  },
  showCodexTab(){
    this._dvTab='codex';
    document.getElementById('deck-tab').style.display='none';
    document.getElementById('codex-tab').style.display='';
    document.getElementById('tab-codex').style.borderColor='#ffd700';document.getElementById('tab-codex').style.color='#ffd700';
    document.getElementById('tab-deck').style.borderColor='';document.getElementById('tab-deck').style.color='';
    this.renderCodex();
  },
  // 2026-04-28: 도서관 NPC "생명의 서 확인하기" 진입용 wrapper.
  // showDeckView() 가 deckview-screen 진입 + HUD + default(deck) 탭 셋업을 마친 뒤 codex 탭으로 전환.
  showCodexView(){
    this.showDeckView();
    this.showCodexTab();
  },
  _codexFilter:'all',
  renderCodex(filter){
    if(filter)this._codexFilter=filter;
    const f=this._codexFilter;
    // Filters
    const fd=document.getElementById('codex-filters');fd.innerHTML='';
    const filters=[{id:'all',label:'전체'},{id:'bronze',label:'일반'},{id:'silver',label:'희귀'},{id:'gold',label:'고귀한'},{id:'legendary',label:'전설의'},{id:'divine',label:'신'}];
    filters.forEach(ft=>{
      const btn=document.createElement('button');btn.className='btn btn-s';
      btn.style.cssText=`padding:3px 10px;font-size:.7rem;${f===ft.id?'border-color:#ffd700;color:#ffd700;':''}`;
      btn.textContent=ft.label;btn.onclick=()=>this.renderCodex(ft.id);fd.appendChild(btn);
    });
    // Grid — show all non-hero UNITS
    const grid=document.getElementById('codex-grid');grid.innerHTML='';
    const owned=new Set(this.deck.map(c=>c.id));
    // Filter units (exclude hero templates)
    let pool=UNITS.filter(u=>!u.id.startsWith('h_'));
    if(f!=='all')pool=pool.filter(u=>u.rarity===f);
    if(!pool.length){grid.innerHTML='<div style="color:#555;font-size:.85rem;padding:20px;">해당 혈통의 동료가 없습니다</div>';return;}
    pool.forEach(u=>{
      const have=owned.has(u.id);
      const el=mkCardElV4(u);  // Step 5A-1: V4 프레임 (2026-04-21)
      if(!have){el.style.filter='grayscale(.7) brightness(.5)';el.style.opacity='.6';}
      el.onclick=()=>this.showCodexDetail(u,have);
      grid.appendChild(el);
    });
    // Summary
    const total=UNITS.filter(u=>!u.id.startsWith('h_')).length;
    const ownedCount=UNITS.filter(u=>!u.id.startsWith('h_')&&owned.has(u.id)).length;
    const summary=document.createElement('div');summary.style.cssText='width:100%;text-align:center;font-size:.75rem;color:#888;padding:8px;';
    summary.textContent=`수집: ${ownedCount}/${total} (${Math.floor(ownedCount/total*100)}%)`;
    grid.prepend(summary);
  },
  showCodexDetail(u,owned){
    const m=document.getElementById('detail-modal');
    const ct=document.getElementById('detail-content');
    const elemColor=ELEM_COLOR[u.element]||'#aaa';
    ct.innerHTML=`
      <div style="text-align:center;margin-bottom:10px;">
        <div style="font-size:2.5rem;">${u.icon}</div>
        <div style="font-size:1.2rem;color:#fff;font-weight:bold;">${u.name}</div>
        <div style="font-size:.8rem;color:#aaa;">${u.type||''} · ${ROLE_L[u.role]||''} · ${R_LABEL[u.rarity]||''}</div>
        <div style="font-size:.8rem;"><span style="color:${elemColor};">${ELEM_ICON[u.element]||''} ${ELEM_L[u.element]||'무속성'}</span> · ${u.race||'?'}</div>
        <div style="font-size:.8rem;margin-top:4px;color:${owned?'#44ff88':'#ff4444'};">${owned?'✅ 보유 중':'❌ 미보유'}</div>
      </div>
      <div style="border-top:1px solid #333;padding-top:8px;margin-bottom:8px;">
        <div style="font-size:.85rem;color:#fff;margin-bottom:4px;">📊 기본 능력치</div>
        <div style="display:flex;flex-wrap:wrap;gap:6px;font-size:.8rem;">
          <span class="st-atk">⚔ 공격 ${u.atk}</span><span class="st-hp">♥ 체력 ${u.hp}</span>
          <span class="st-def">🛡 방어 ${u.def||0}</span><span class="st-spd">💨 스피드 ${u.spd}</span>
          <span style="color:#ffdd44;">⚡ 에너지 ${u.nrg||0}</span><span style="color:#44ff88;">🍀 행운 ${u.luck||0}</span>
          <span style="color:#ff88cc;">💫 회피 ${u.eva||0}</span><span style="color:#88ddff;">🔮 마회피 ${u.meva||0}</span>
        </div>
      </div>
      <div style="border-top:1px solid #333;padding-top:8px;">
        <div style="font-size:.85rem;color:#fff;margin-bottom:4px;">⚡ 비전</div>
        <div style="font-size:.75rem;color:#ddd;">${u.skillDesc||'없음'}</div>
        ${u.bonusTrigger?`<div style="font-size:.7rem;color:#ff88cc;margin-top:4px;">🎲 보너스: ${u.bonusTrigger.desc}</div>`:''}
      </div>`;
    m.classList.add('active');
  },

  showDeckView(){
    UI.show('deckview-screen');
    this._dvTab='deck';this.showDeckTab();
    document.getElementById('dv-name').textContent=`👤 ${Auth.user}`;
    document.getElementById('dv-slots').textContent=this.getCommandSlots();
    document.getElementById('dv-rslots').textContent=this.getRelicSlots();
    const npc=this.getNpc('library');
    const existing=document.getElementById('lib-npc');if(existing)existing.remove();
    document.getElementById('tab-deck').parentElement.insertAdjacentHTML('afterend',`<div id="lib-npc">${this.renderNpcBar('library')}</div>`);
    // Section title counts (N/M)
    const totalUnits=UNITS.filter(u=>!u.id.startsWith('h_')).length;
    const ownedUnits=this.deck.filter(c=>!c.isHero).length;
    const ownedSk=(this.ownedSkills||[]).length, totalSk=SKILLS_DB.length;
    const ownedRl=(this.ownedRelics||[]).length, totalRl=RELICS_DB.length;
    document.querySelectorAll('#deck-tab .dv-title').forEach(e=>e.remove());
    // Onboarding (empty starter)
    const onb=document.getElementById('dv-onboarding');if(onb)onb.remove();
    if(ownedUnits===0&&ownedSk===0&&ownedRl===0){
      const ob=document.createElement('div');ob.id='dv-onboarding';ob.className='dv-onboarding';
      ob.innerHTML=`💡 첫 동료를 영입하세요<br><span>선술집에서 5골드로 브론즈 동료 영입 가능</span><br><button class="btn btn-s" data-action="game.showTavern" style="margin-top:6px;">🍺 선술집으로</button>`;
      document.getElementById('deck-tab').prepend(ob);
    }
    // Units
    const g=document.getElementById('dv-grid');g.innerHTML='';
    g.insertAdjacentHTML('beforebegin',`<div class="dv-title">👥 동료 (${ownedUnits}/${totalUnits})</div>`);
    this.deck.forEach(c=>{
      const el=mkCardElV4(c);  // Step 5A-1: V4 프레임 (2026-04-21)
      // 2026-04-27: 클릭 → 중앙 확대 focus (전투 char-focus 와 동형). 기존 showCardDetail 모달 폐기.
      el.onclick=()=>this.showDeckCardFocus(c);
      g.appendChild(el);
    });
    const emptyU=Math.max(0,Math.min(6,totalUnits-ownedUnits));
    const hintN=ownedUnits===0?3:0;  // P0-2: 동료 0명일 때만 첫 3칸을 힌트로 승격
    for(let i=0;i<emptyU;i++){
      if(i<hintN){
        g.insertAdjacentHTML('beforeend','<div class="empty-slot hint" title="선술집에서 영입"><span class="es-icon">⚔</span><span class="es-label">선술집에서<br>영입</span></div>');
      } else {
        g.insertAdjacentHTML('beforeend','<div class="empty-slot" title="동료를 영입하면 여기에 표시됩니다">?</div>');
      }
    }
    // Skills
    const sg=document.getElementById('dv-skills');sg.innerHTML='';
    sg.insertAdjacentHTML('beforebegin',`<div class="dv-title">💎 비전 (${ownedSk}/${totalSk})</div>`);
    const skills=this.ownedSkills||[];
    if(!skills.length){
      for(let i=0;i<6;i++)sg.insertAdjacentHTML('beforeend','<div class="empty-slot" title="전투 보상으로 비전을 획득하세요">?</div>');
    } else {
      skills.forEach(sk=>{
        const el=mkRelicEl(sk);  // V4 로 kind 자동 판별 (effect 있으면 '비전')
        // Show equipped status
        const equipped=this.deck.find(c=>(c.equips||[]).some(e=>e.uid===sk.uid));
        if(equipped){
          const tag=document.createElement('div');tag.style.cssText='text-align:center;font-size:.65rem;color:#44ff88;margin-top:2px;';
          tag.textContent=`→ ${equipped.icon}${equipped.name}에 장착`;
          el.appendChild(tag);
        } else {
          const tag=document.createElement('div');tag.style.cssText='text-align:center;font-size:.65rem;color:#888;margin-top:2px;';
          tag.textContent='미장착 (클릭하여 장착)';
          el.appendChild(tag);
        }
        el.onclick=()=>{
          if(equipped){
            // Unequip
            UI.modal('비전 해제',`${equipped.icon}${equipped.name}에서 ${sk.icon}${sk.name}을 해제하시겠습니까?`,()=>{
              equipped.equips=equipped.equips.filter(e=>e.uid!==sk.uid);
              SFX.play('click');this.persist();this.showDeckView();
            });
          } else {
            // Equip to a unit
            this.equipOwnedSkill(sk);
          }
        };
        sg.appendChild(el);
      });
    }
    // Relics
    const rg=document.getElementById('dv-relics');rg.innerHTML='';
    rg.insertAdjacentHTML('beforebegin',`<div class="dv-title">🏺 유물 (${ownedRl}/${totalRl})</div>`);
    if(!this.ownedRelics||!this.ownedRelics.length){
      for(let i=0;i<6;i++)rg.insertAdjacentHTML('beforeend','<div class="empty-slot" title="차원의 균열에서 유물을 획득하세요">?</div>');
    } else {
      this.ownedRelics.forEach(r=>{
        const el=mkRelicEl(r);
        el.onclick=()=>this.showRelicDetail(r);
        rg.appendChild(el);
      });
    }
  },

  equipOwnedSkill(sk){
    const modal=document.getElementById('equip-modal');
    document.getElementById('equip-title').textContent='비전 장착 대상 선택';
    document.getElementById('equip-skill-info').textContent=`${sk.icon} ${sk.name}: ${sk.desc}`;
    const targets=document.getElementById('equip-targets');targets.innerHTML='';
    this.deck.forEach(c=>{
      const d=document.createElement('div');d.className=`deck-mini ${c.rarity||'bronze'}`;d.style.cursor='pointer';
      d.innerHTML=`<div class="dm-icon">${c.icon}</div><div class="dm-name">${c.isHero?'⭐':''}${c.name}</div>`;
      d.onclick=()=>{
        c.equips=c.equips||[];
        c.equips.push({icon:sk.icon,name:sk.name,id:sk.id,uid:sk.uid});
        applySkillToUnit(sk,c);
        modal.classList.remove('active');SFX.play('magic');this.persist();this.showDeckView();
      };targets.appendChild(d);});
    modal.classList.add('active');
  },

  // 2026-04-27: showCardDetail (detail-modal 텍스트 설명창) 폐기.
  //   대체: showDeckCardFocus — 전투 char-focus 와 동형 UI (중앙 V4 카드 확대 + 보유 스킬카드 row).
  //   trait 시스템 / freePoints 분배 / 비전 해제 버튼 모두 폐기. 단련은 castle 에서.
  showDeckCardFocus(c){
    const overlay = document.getElementById('dv-focus');
    if(!overlay) return;
    const mainCard = overlay.querySelector('.dvf-main-card');
    const skillRow = overlay.querySelector('.dvf-skill-row');
    if(!mainCard || !skillRow) return;

    // 1) 중앙 카드 — V4 컴포넌트로 currentHp/curNrg 반영해서 큰 사이즈로 렌더.
    mainCard.innerHTML='';
    const cardEl = mkCardElV4(c);
    mainCard.appendChild(cardEl);

    // 2) 스킬 row — 전투 char-focus 와 동일하게 buildUnitSkillSet 결과 표시.
    //    Battle.buildUnitSkillSet 가 export 되어 있으면 사용 (정확). 미정의 시 기본 스킬만 표시.
    let skills = [];
    try {
      if(window.Battle && typeof Battle.buildUnitSkillSet === 'function'){
        skills = Battle.buildUnitSkillSet(c).filter(s=>s && s.passive!==true);
      }
    } catch(e){ skills = []; }

    skillRow.innerHTML='';
    if(!skills.length){
      const empty=document.createElement('div');
      empty.className='dvf-skill-empty';
      empty.textContent='전투 시 사용할 스킬이 없습니다.';
      skillRow.appendChild(empty);
    } else {
      skills.forEach(sk=>{
        const slot=document.createElement('div');
        slot.className='dvf-skill-card';
        const skImg = (typeof Battle !== 'undefined' && Battle.resolveImg) ? Battle.resolveImg(sk.imgKey) : null;
        slot.innerHTML=`
          <div class="bsc-card-img">${skImg?`<img src="${skImg}" alt="">`:''}</div>
          <div class="bsc-cost">⚡${sk.cost ?? 0}${sk.tpCost > 1 ? ' TP' + sk.tpCost : ''}</div>
          <div class="bsc-name">${sk.name||''}</div>
          <div class="bsc-desc">${sk.desc||''}</div>`;
        skillRow.appendChild(slot);
      });
    }

    overlay.classList.add('active');
  },
  closeDeckCardFocus(){
    const overlay = document.getElementById('dv-focus');
    if(overlay) overlay.classList.remove('active');
  },

  showRelicDetail(r){
    const m=document.getElementById('detail-modal');
    const ct=document.getElementById('detail-content');
    ct.innerHTML=`
      <div style="text-align:center;margin-bottom:10px;">
        <div style="font-size:2.5rem;">${r.icon}</div>
        <div style="font-size:1.2rem;color:#fff;font-weight:bold;">${r.name}</div>
        <div style="font-size:.8rem;color:#aaa;">유물 · ${R_LABEL[r.rarity]||''}</div>
      </div>
      <div style="border-top:1px solid #333;padding-top:8px;">
        <div style="font-size:.85rem;color:#ddd;">${r.desc}</div>
      </div>
    `;
    m.classList.add('active');
  },

  // ---- TAVERN (용병 고용) ----
  equipSkill(skillData){
    const modal=document.getElementById('equip-modal');
    document.getElementById('equip-skill-info').textContent=`${skillData.icon} ${skillData.name}: ${skillData.desc}`;
    const targets=document.getElementById('equip-targets');targets.innerHTML='';
    this.deck.forEach(c=>{
      const d=document.createElement('div');d.className=`deck-mini ${c.rarity||'bronze'}`;d.style.cursor='pointer';
      d.innerHTML=`<div class="dm-icon">${c.icon}</div><div class="dm-name">${c.isHero?'⭐':''}${c.name}</div>`;
      d.onclick=()=>{
        applySkillToUnit(skillData,c);
        c.equips=c.equips||[];c.equips.push({icon:skillData.icon,name:skillData.name,id:skillData.id});
        modal.classList.remove('active');SFX.play('magic');
      };targets.appendChild(d);});
    modal.classList.add('active');
  },
});
