// Game Deck (덱 보기/도감/카드 상세)
// Generated by docs/_split_game.py — Phase 4
// DO NOT hand-edit keys — edit in original and re-run splitter if needed.

RoF.__gameKeys = RoF.__gameKeys || new Set();
(function(keys){
  for (const k of keys) {
    if (RoF.__gameKeys.has(k)) {
      console.error('[Game] 중복 키 감지:', k);
      RoF.__gameKeyError = true;
    }
    RoF.__gameKeys.add(k);
  }
})(["_dvTab", "showDeckTab", "showCodexTab", "_codexFilter", "renderCodex", "showCodexDetail", "showDeckView", "equipOwnedSkill", "showCardDetail", "showRelicDetail", "equipSkill"]);

Object.assign(RoF.Game, {
  _dvTab:'deck',
  showDeckTab(){
    this._dvTab='deck';
    document.getElementById('deck-tab').style.display='';
    document.getElementById('codex-tab').style.display='none';
    document.getElementById('tab-deck').style.borderColor='#ffd700';document.getElementById('tab-deck').style.color='#ffd700';
    document.getElementById('tab-codex').style.borderColor='';document.getElementById('tab-codex').style.color='';
  },
  showCodexTab(){
    this._dvTab='codex';
    document.getElementById('deck-tab').style.display='none';
    document.getElementById('codex-tab').style.display='';
    document.getElementById('tab-codex').style.borderColor='#ffd700';document.getElementById('tab-codex').style.color='#ffd700';
    document.getElementById('tab-deck').style.borderColor='';document.getElementById('tab-deck').style.color='';
    this.renderCodex();
  },
  _codexFilter:'all',
  renderCodex(filter){
    if(filter)this._codexFilter=filter;
    const f=this._codexFilter;
    // Filters
    const fd=document.getElementById('codex-filters');fd.innerHTML='';
    const filters=[{id:'all',label:'전체'},{id:'bronze',label:'브론즈'},{id:'silver',label:'실버'},{id:'gold',label:'골드'},{id:'legendary',label:'전설'},{id:'divine',label:'신'}];
    filters.forEach(ft=>{
      const btn=document.createElement('button');btn.className='btn btn-s';
      btn.style.cssText=`padding:3px 10px;font-size:.7rem;${f===ft.id?'border-color:#ffd700;color:#ffd700;':''}`;
      btn.textContent=ft.label;btn.onclick=()=>this.renderCodex(ft.id);fd.appendChild(btn);
    });
    // Grid — show all non-hero UNITS
    const grid=document.getElementById('codex-grid');grid.innerHTML='';
    const owned=new Set(this.deck.map(c=>c.id));
    // Filter units (exclude hero templates)
    let pool=UNITS.filter(u=>!u.id.startsWith('h_'));
    if(f!=='all')pool=pool.filter(u=>u.rarity===f);
    if(!pool.length){grid.innerHTML='<div style="color:#555;font-size:.85rem;padding:20px;">해당 혈통의 동료가 없습니다</div>';return;}
    pool.forEach(u=>{
      const have=owned.has(u.id);
      const el=mkCardEl(u);
      if(!have){el.style.filter='grayscale(.7) brightness(.5)';el.style.opacity='.6';}
      el.onclick=()=>this.showCodexDetail(u,have);
      grid.appendChild(el);
    });
    // Summary
    const total=UNITS.filter(u=>!u.id.startsWith('h_')).length;
    const ownedCount=UNITS.filter(u=>!u.id.startsWith('h_')&&owned.has(u.id)).length;
    const summary=document.createElement('div');summary.style.cssText='width:100%;text-align:center;font-size:.75rem;color:#888;padding:8px;';
    summary.textContent=`수집: ${ownedCount}/${total} (${Math.floor(ownedCount/total*100)}%)`;
    grid.prepend(summary);
  },
  showCodexDetail(u,owned){
    const m=document.getElementById('detail-modal');
    const ct=document.getElementById('detail-content');
    const elemColor=ELEM_COLOR[u.element]||'#aaa';
    ct.innerHTML=`
      <div style="text-align:center;margin-bottom:10px;">
        <div style="font-size:2.5rem;">${u.icon}</div>
        <div style="font-size:1.2rem;color:#fff;font-weight:bold;">${u.name}</div>
        <div style="font-size:.8rem;color:#aaa;">${u.type||''} · ${ROLE_L[u.role]||''} · ${R_LABEL[u.rarity]||''}</div>
        <div style="font-size:.8rem;"><span style="color:${elemColor};">${ELEM_ICON[u.element]||''} ${ELEM_L[u.element]||'무속성'}</span> · ${u.race||'?'}</div>
        <div style="font-size:.8rem;margin-top:4px;color:${owned?'#44ff88':'#ff4444'};">${owned?'✅ 보유 중':'❌ 미보유'}</div>
      </div>
      <div style="border-top:1px solid #333;padding-top:8px;margin-bottom:8px;">
        <div style="font-size:.85rem;color:#fff;margin-bottom:4px;">📊 기본 능력치</div>
        <div style="display:flex;flex-wrap:wrap;gap:6px;font-size:.8rem;">
          <span class="st-atk">⚔ 공격 ${u.atk}</span><span class="st-hp">♥ 체력 ${u.hp}</span>
          <span class="st-def">🛡 방어 ${u.def||0}</span><span class="st-spd">💨 스피드 ${u.spd}</span>
          <span style="color:#ffdd44;">⚡ 에너지 ${u.nrg||0}</span><span style="color:#44ff88;">🍀 행운 ${u.luck||0}</span>
          <span style="color:#ff88cc;">💫 회피 ${u.eva||0}</span><span style="color:#88ddff;">🔮 마회피 ${u.meva||0}</span>
        </div>
      </div>
      <div style="border-top:1px solid #333;padding-top:8px;">
        <div style="font-size:.85rem;color:#fff;margin-bottom:4px;">⚡ 비전</div>
        <div style="font-size:.75rem;color:#ddd;">${u.skillDesc||'없음'}</div>
        ${u.bonusTrigger?`<div style="font-size:.7rem;color:#ff88cc;margin-top:4px;">🎲 보너스: ${u.bonusTrigger.desc}</div>`:''}
      </div>`;
    m.classList.add('active');
  },

  showDeckView(){
    UI.show('deckview-screen');
    this._dvTab='deck';this.showDeckTab();
    document.getElementById('dv-name').textContent=`👤 ${Auth.user}`;
    document.getElementById('dv-slots').textContent=this.getCommandSlots();
    document.getElementById('dv-rslots').textContent=this.getRelicSlots();
    const npc=this.getNpc('library');
    const existing=document.getElementById('lib-npc');if(existing)existing.remove();
    document.getElementById('tab-deck').parentElement.insertAdjacentHTML('afterend',`<div id="lib-npc">${this.renderNpcBar('library')}</div>`);
    // Units
    const g=document.getElementById('dv-grid');g.innerHTML='';
    this.deck.forEach(c=>{
      const el=mkCardEl(c);
      el.onclick=()=>this.showCardDetail(c);
      g.appendChild(el);
    });
    // Skills
    const sg=document.getElementById('dv-skills');sg.innerHTML='';
    const skills=this.ownedSkills||[];
    if(!skills.length){
      sg.innerHTML='<div style="color:#555;font-size:.8rem;">습득한 비전 없음</div>';
    } else {
      skills.forEach(sk=>{
        const el=mkRelicEl(sk);el.querySelector('.card-type').textContent='비전';
        // Show equipped status
        const equipped=this.deck.find(c=>(c.equips||[]).some(e=>e.uid===sk.uid));
        if(equipped){
          const tag=document.createElement('div');tag.style.cssText='text-align:center;font-size:.65rem;color:#44ff88;margin-top:2px;';
          tag.textContent=`→ ${equipped.icon}${equipped.name}에 장착`;
          el.appendChild(tag);
        } else {
          const tag=document.createElement('div');tag.style.cssText='text-align:center;font-size:.65rem;color:#888;margin-top:2px;';
          tag.textContent='미장착 (클릭하여 장착)';
          el.appendChild(tag);
        }
        el.onclick=()=>{
          if(equipped){
            // Unequip
            UI.modal('비전 해제',`${equipped.icon}${equipped.name}에서 ${sk.icon}${sk.name}을 해제하시겠습니까?`,()=>{
              equipped.equips=equipped.equips.filter(e=>e.uid!==sk.uid);
              SFX.play('click');this.persist();this.showDeckView();
            });
          } else {
            // Equip to a unit
            this.equipOwnedSkill(sk);
          }
        };
        sg.appendChild(el);
      });
    }
    // Relics
    const rg=document.getElementById('dv-relics');rg.innerHTML='';
    if(!this.ownedRelics||!this.ownedRelics.length){
      rg.innerHTML='<div style="color:#555;font-size:.8rem;">소지한 유물 없음</div>';
    } else {
      this.ownedRelics.forEach(r=>{
        const el=mkRelicEl(r);
        el.onclick=()=>this.showRelicDetail(r);
        rg.appendChild(el);
      });
    }
  },

  equipOwnedSkill(sk){
    const modal=document.getElementById('equip-modal');
    document.getElementById('equip-title').textContent='비전 장착 대상 선택';
    document.getElementById('equip-skill-info').textContent=`${sk.icon} ${sk.name}: ${sk.desc}`;
    const targets=document.getElementById('equip-targets');targets.innerHTML='';
    this.deck.forEach(c=>{
      const d=document.createElement('div');d.className=`deck-mini ${c.rarity||'bronze'}`;d.style.cursor='pointer';
      d.innerHTML=`<div class="dm-icon">${c.icon}</div><div class="dm-name">${c.isHero?'⭐':''}${c.name}</div>`;
      d.onclick=()=>{
        c.equips=c.equips||[];
        c.equips.push({icon:sk.icon,name:sk.name,id:sk.id,uid:sk.uid});
        applySkillToUnit(sk,c);
        modal.classList.remove('active');SFX.play('magic');this.persist();this.showDeckView();
      };targets.appendChild(d);});
    modal.classList.add('active');
  },

  showCardDetail(c){
    const m=document.getElementById('detail-modal');
    const ct=document.getElementById('detail-content');
    const equips=c.equips||[];
    const gp=c.growthPts||{atk:0,hp:0,def:0,spd:0,nrg:0,luck:0,eva:0};
    const fp=c.freePoints||0;
    const elemColor=ELEM_COLOR[c.element]||'#aaa';
    ct.innerHTML=`
      <div style="text-align:center;margin-bottom:10px;">
        <div style="font-size:2.5rem;">${c.icon}</div>
        <div style="font-size:1.2rem;color:#fff;font-weight:bold;">${c.isHero?'⭐ ':''}${c.name}</div>
        ${c.heroClass?`<div style="font-size:.85rem;color:#ccc;">${c.heroClass}</div>`:''}
        <div style="font-size:.8rem;color:#aaa;">${c.type||''} · ${ROLE_L[c.role]||''} · ${R_LABEL[c.rarity]||''}</div>
        <div style="font-size:.8rem;"><span style="color:${elemColor};">${ELEM_ICON[c.element]||''} ${ELEM_L[c.element]||'무속성'}</span> · ${c.race==='human'?'인간':c.race||'?'}</div>
        <div style="font-size:.75rem;color:#ffd700;">Lv.${c.level||1} | 경험: ${c.xp||0}/${(c.level||1)*10} | ⭐ ${c.honor||0}명예</div>
        <div style="font-size:.7rem;color:#ffaa44;">지휘권: ${c.isHero?'무료(자동)':(c.level||1)} | ${c.range==='ranged'?'🏹 원거리':'⚔️ 근접'}</div>
        ${fp>0?`<div style="font-size:.85rem;color:#44ff88;margin-top:4px;">🟢 배분 가능 포인트: ${fp}</div>`:''}
      </div>
      <div style="border-top:1px solid #333;padding-top:8px;margin-bottom:8px;">
        <div style="font-size:.85rem;color:#fff;margin-bottom:4px;">📊 능력치 <span style="font-size:.7rem;color:#888;">(기본+성장)</span></div>
        <div id="stat-alloc-grid"></div>
      </div>
      <div style="border-top:1px solid #333;padding-top:8px;margin-bottom:8px;">
        <div style="font-size:.85rem;color:#fff;margin-bottom:4px;">🏷️ 특성</div>
        <div style="display:flex;flex-wrap:wrap;gap:6px;margin-bottom:6px;">${getTraits(c).map(tid=>{const tr=TRAITS[tid];return tr?`<span style="font-size:.75rem;padding:2px 8px;border-radius:4px;background:rgba(0,0,0,.4);border:1px solid ${tr.color};color:${tr.color};">${tr.icon} ${tr.name}: ${tr.desc}</span>`:''}).join('')||'<span style="color:#555;font-size:.75rem;">없음</span>'}</div>
        <div style="font-size:.85rem;color:#fff;margin-bottom:4px;">⚡ 고유 비전</div>
        <div style="font-size:.75rem;color:#ddd;">${c.skillDesc||'없음'}</div>
        ${c.bonusTrigger?`<div style="font-size:.7rem;color:#ff88cc;margin-top:4px;">🎲 보너스: ${c.bonusTrigger.desc}</div>`:''}
        ${c.action&&c.action!=='attack'?`<div style="font-size:.7rem;color:#ffaa44;margin-top:2px;">⚠️ 행동: ${({none:'공격불가 (피격 전용)',counter:'반격 전용',skill_only:'비전만 사용'})[c.action]||c.action}</div>`:''}
      </div>
      <div style="border-top:1px solid #333;padding-top:8px;">
        <div style="font-size:.85rem;color:#fff;margin-bottom:4px;">🔧 장착 장비/비전 (${equips.length}개)</div>
        <div id="detail-equips"></div>
      </div>
    `;
    // Stat allocation grid
    const sg=document.getElementById('stat-alloc-grid');
    const statDefs=[
      {key:'atk',label:'⚔ 공격',color:'#ff6644',val:c.atk,grow:gp.atk||0},
      {key:'hp',label:'♥ 체력',color:'#44cc66',val:c.hp,grow:gp.hp||0},
      {key:'def',label:'🛡 방어',color:'#aaddff',val:c.def||0,grow:gp.def||0},
      {key:'spd',label:'💨 스피드',color:'#66ccff',val:c.spd||0,grow:gp.spd||0},
      {key:'nrg',label:'⚡ 에너지',color:'#ffdd44',val:c.nrg||0,grow:gp.nrg||0},
      {key:'luck',label:'🍀 행운',color:'#44ff88',val:c.luck||0,grow:gp.luck||0},
      {key:'eva',label:'💫 회피',color:'#ff88cc',val:c.eva||0,grow:gp.eva||0},
    ];
    statDefs.forEach(s=>{
      const row=document.createElement('div');
      row.style.cssText='display:flex;align-items:center;gap:6px;padding:3px 0;font-size:.8rem;';
      row.innerHTML=`<span style="color:${s.color};width:90px;">${s.label}</span>
        <span style="color:#fff;width:30px;text-align:right;">${s.val}</span>
        <span style="color:#44ff88;font-size:.7rem;width:40px;">${s.grow>0?'(+'+s.grow+')':''}</span>`;
      if(fp>0){
        const btn=document.createElement('button');
        btn.className='btn btn-s btn-green';btn.style.cssText='padding:1px 8px;font-size:.65rem;margin-left:auto;';
        btn.textContent='+1';
        btn.onclick=()=>{
          if(!c.freePoints||c.freePoints<=0)return;
          c.freePoints--;
          if(!c.growthPts)c.growthPts={atk:0,hp:0,def:0,spd:0,nrg:0,luck:0,eva:0};
          c.growthPts[s.key]=(c.growthPts[s.key]||0)+1;
          // Apply stat immediately
          if(s.key==='hp'){c.hp+=1;c.maxHp=(c.maxHp||c.hp)+1;}
          else{c[s.key]=(c[s.key]||0)+1;}
          SFX.play('click');this.persist();this.checkTutorial('first_stat_alloc');this.showCardDetail(c);
        };
        row.appendChild(btn);
      }
      sg.appendChild(row);
    });
    // Non-growable stats
    const fixedStats=document.createElement('div');
    fixedStats.style.cssText='display:flex;flex-wrap:wrap;gap:6px;font-size:.75rem;margin-top:6px;padding-top:6px;border-top:1px solid #222;';
    fixedStats.innerHTML=`<span style="color:#88ddff;">🔮 마법회피 ${c.meva||0}</span>
      <span style="color:#aaddff;">🛡️ 보호막 ${c.shield||0}</span>
      <span class="st-hp">💗 체력회복 ${c.hpReg||0}/턴</span>
      <span class="st-nrg">🔋 에너지회복 ${c.nrgReg||0}/턴</span>`;
    sg.appendChild(fixedStats);

    const eqDiv=document.getElementById('detail-equips');
    if(!equips.length){
      eqDiv.innerHTML='<div style="color:#555;font-size:.75rem;">장착된 것 없음</div>';
    } else {
      equips.forEach((eq,i)=>{
        const row=document.createElement('div');
        row.style.cssText='display:flex;align-items:center;justify-content:space-between;padding:4px 0;border-bottom:1px solid #222;';
        row.innerHTML=`<span style="font-size:.8rem;">${eq.icon} ${eq.name}</span>`;
        const btn=document.createElement('button');
        btn.className='btn btn-s btn-red';btn.style.cssText='padding:2px 8px;font-size:.65rem;';
        btn.textContent='해제';
        btn.onclick=()=>{
          c.equips.splice(i,1);
          this.persist();SFX.play('click');
          this.showCardDetail(c);
        };
        row.appendChild(btn);eqDiv.appendChild(row);
      });
    }
    m.classList.add('active');
  },

  showRelicDetail(r){
    const m=document.getElementById('detail-modal');
    const ct=document.getElementById('detail-content');
    ct.innerHTML=`
      <div style="text-align:center;margin-bottom:10px;">
        <div style="font-size:2.5rem;">${r.icon}</div>
        <div style="font-size:1.2rem;color:#fff;font-weight:bold;">${r.name}</div>
        <div style="font-size:.8rem;color:#aaa;">유물 · ${R_LABEL[r.rarity]||''}</div>
      </div>
      <div style="border-top:1px solid #333;padding-top:8px;">
        <div style="font-size:.85rem;color:#ddd;">${r.desc}</div>
      </div>
    `;
    m.classList.add('active');
  },

  // ---- TAVERN (용병 고용) ----
  equipSkill(skillData){
    const modal=document.getElementById('equip-modal');
    document.getElementById('equip-skill-info').textContent=`${skillData.icon} ${skillData.name}: ${skillData.desc}`;
    const targets=document.getElementById('equip-targets');targets.innerHTML='';
    this.deck.forEach(c=>{
      const d=document.createElement('div');d.className=`deck-mini ${c.rarity||'bronze'}`;d.style.cursor='pointer';
      d.innerHTML=`<div class="dm-icon">${c.icon}</div><div class="dm-name">${c.isHero?'⭐':''}${c.name}</div>`;
      d.onclick=()=>{
        applySkillToUnit(skillData,c);
        c.equips=c.equips||[];c.equips.push({icon:skillData.icon,name:skillData.name});
        modal.classList.remove('active');SFX.play('magic');
      };targets.appendChild(d);});
    modal.classList.add('active');
  },
});
