// Game Castle (성/리그/대장간/교회/훈련)
// Generated by docs/_split_game.py — Phase 4
// DO NOT hand-edit keys — edit in original and re-run splitter if needed.

RoF.__gameKeys = RoF.__gameKeys || new Set();
(function(keys){
  for (const k of keys) {
    if (RoF.__gameKeys.has(k)) {
      console.error('[Game] 중복 키 감지:', k);
      RoF.__gameKeyError = true;
    }
    RoF.__gameKeys.add(k);
  }
})(["showCastle", "showCastleUpgradeTab", "showCastleQuestTab", "showForge", "showChurch", "showTraining", "showShop", "showTemple", "showInn", "LEAGUES", "getLeague", "getLeagueProgress"]);

Object.assign(RoF.Game, {
  showCastle(){
    UI.show('castle-screen');
    const npc=this.getNpc('castle');
    const injured=this.deck.filter(c=>c.injured).length;
    // 2026-04-24: noGold 필드 폐기 — 골드 부족 시 별도 안내문 사용. 부상자 알림 우선, 없으면 기본 인사.
    const msg=this.gold<3?'국고가 비어있구려. 전투에서 벌어오시오.':injured>0?`부상자가 ${injured}명이나... 먼저 교회에 다녀오시오.`:npc.greet;
    document.querySelector('#castle-screen .hud').insertAdjacentHTML('afterend',
      `<div id="castle-npc">${this.renderNpcBar('castle',msg)}</div>`);
    // Remove duplicate on re-render
    const prev=document.querySelectorAll('#castle-npc');if(prev.length>1)prev[0].remove();
    this._castleTab='upgrade';
    this.showCastleUpgradeTab();
  },
  showCastleUpgradeTab(){
    this._castleTab='upgrade';
    document.getElementById('castle-tab-quest').style.borderColor='';document.getElementById('castle-tab-quest').style.color='';
    document.getElementById('castle-tab-upgrade').style.borderColor='#ffd700';document.getElementById('castle-tab-upgrade').style.color='#ffd700';
    document.getElementById('castle-quest-area').style.display='none';
    document.getElementById('castle-upgrade-area').style.display='';
    // Reuse existing upgrade logic
    document.getElementById('castle-gold').textContent=this.gold;
    const g=document.getElementById('castle-upgrade-grid');g.innerHTML='';
    this.deck.forEach(c=>{
      const cost=(c.level||1)*3;
      const el=mkCardElV4(c);
      const btn=document.createElement('div');btn.style.cssText='text-align:center;margin-top:4px;';
      btn.innerHTML=`<button class="btn btn-s btn-green" ${this.gold<cost?'disabled':''}>${cost}💰 단련</button>`;
      btn.querySelector('button').onclick=(e)=>{e.stopPropagation();
        if(this.gold<cost)return;this.gold-=cost;
        const oldRar=c.rarity;
        c.level=(c.level||1)+1;c.freePoints=(c.freePoints||0)+5;
        if(c.level%5===0){const ni=R_ORDER.indexOf(c.rarity);if(ni<R_ORDER.length-1){c.rarity=R_ORDER[ni+1];}}
        const rarChanged=c.rarity!==oldRar;
        if(rarChanged){SFX.play('rarity_up');
          const burst=document.createElement('div');burst.className='rarity-burst';document.body.appendChild(burst);setTimeout(()=>burst.remove(),1000);
        } else {SFX.play('upgrade');
          const flash=document.createElement('div');flash.className='upgrade-flash';document.body.appendChild(flash);setTimeout(()=>flash.remove(),600);
        }
        const cardEl=el.parentElement;if(cardEl){const pp=document.createElement('div');pp.className='upgrade-particles';
          for(let pi=0;pi<12;pi++){const pt=document.createElement('div');pt.className='upgrade-particle';const angle=Math.random()*Math.PI*2;const dist=30+Math.random()*40;pt.style.setProperty('--px',Math.cos(angle)*dist+'px');pt.style.setProperty('--py',Math.sin(angle)*dist+'px');pt.style.background=rarChanged?'#a335ee':'#ffd700';pp.appendChild(pt);}
          cardEl.style.position='relative';cardEl.appendChild(pp);setTimeout(()=>pp.remove(),800);
          el.classList.add('upgrade-card-glow');setTimeout(()=>el.classList.remove('upgrade-card-glow'),600);
        }
        this.persist();this.checkTutorial('first_upgrade');setTimeout(()=>this.showCastleUpgradeTab(),rarChanged?800:400);};
      const wrap=document.createElement('div');wrap.appendChild(el);wrap.appendChild(btn);g.appendChild(wrap);
    });
  },
  showCastleQuestTab(){
    this._castleTab='quest';
    document.getElementById('castle-tab-upgrade').style.borderColor='';document.getElementById('castle-tab-upgrade').style.color='';
    document.getElementById('castle-tab-quest').style.borderColor='#ffd700';document.getElementById('castle-tab-quest').style.color='#ffd700';
    document.getElementById('castle-upgrade-area').style.display='none';
    document.getElementById('castle-quest-area').style.display='';
    document.getElementById('castle-quest-area').innerHTML='<div style="color:#888;text-align:center;padding:40px;font-size:.9rem;">📜 왕의 퀘스트가 곧 준비됩니다...<br><br><span style="font-size:.75rem;color:#555;">퀘스트 시스템 개발 중</span></div>';
  },

  showForge(){
    UI.modal('⚒️ 대장간','장비 제작과 분해 기능이 곧 열립니다.\n\n(장비 시스템 준비 중)',null);
  },

  showChurch(){
    UI.show('church-screen');
    document.getElementById('church-gold').textContent=this.gold;
    const injured=this.deck.filter(c=>c.injured&&!c.isHero);
    const npc=this.getNpc('church');
    const msg=injured.length?npc.greet:`부상자가 없군요. 평화로운 날입니다.`;
    const existing=document.getElementById('church-npc');if(existing)existing.remove();
    document.getElementById('church-info').insertAdjacentHTML('afterend',`<div id="church-npc">${this.renderNpcBar('church',msg)}</div>`);
    const g=document.getElementById('church-grid');g.innerHTML='';
    // 2026-04-24: 건물 Lv 시스템 폐기 — discount/honorBonus 단계별 보너스 제거.
    const discount=0;
    const honorBonus=1;
    if(!injured.length){
      g.innerHTML='<div style="color:#888;text-align:center;padding:40px;font-size:.9rem;">부상당한 동료가 없습니다.<br><span style="font-size:.75rem;color:#555;">전투에서 쓰러진 동료가 이곳에 옵니다.</span></div>';
      return;
    }
    injured.forEach(c=>{
      const cost=Math.max(1,Math.floor((c.level||1)*2*(1-discount)));
      const honorGain=Math.floor(((c.level||1)*3+(c.honor||0)*0.1)*honorBonus);
      const el=mkCardElV4(c);
      el.style.filter='grayscale(.5) brightness(.7)';
      const wrap=document.createElement('div');wrap.style.textAlign='center';
      wrap.appendChild(el);
      // Injury badge
      const badge=document.createElement('div');badge.style.cssText='color:#ff4444;font-size:.75rem;margin-top:4px;';
      badge.textContent='🩹 부상 — 출전 불가';wrap.appendChild(badge);
      // Buttons
      const btns=document.createElement('div');btns.style.cssText='display:flex;gap:6px;justify-content:center;margin-top:6px;';
      // Revive button
      const revBtn=document.createElement('button');revBtn.className='btn btn-s btn-green';
      revBtn.textContent=`✨ 치료 (${cost}💰)`;revBtn.disabled=this.gold<cost;
      revBtn.onclick=()=>{
        UI.modal('✨ 치료 확인',`${c.icon} ${c.name}을(를) ${cost}💰로 치료하시겠습니까?\n\n부상이 치유되고 HP/에너지가 만전으로 회복됩니다.`,()=>{
          // 2026-04-27: injured 해제 + 영구 currentHp/curNrg 풀 reset (전투 종료 시 깎인 상태 폐기).
          this.gold-=cost;c.injured=false;c.currentHp=c.hp;c.curNrg=c.nrg||0;
          SFX.play('heal');
          const flash=document.createElement('div');flash.className='upgrade-flash';document.body.appendChild(flash);setTimeout(()=>flash.remove(),600);
          this.persist();this.showChurch();
        });
      };
      btns.appendChild(revBtn);
      // Funeral button
      const funBtn=document.createElement('button');funBtn.className='btn btn-s btn-purple';
      funBtn.textContent=`⚰️ 장례 (+${honorGain}명예)`;
      funBtn.onclick=()=>{
        UI.modal('⚰️ 영면의 의식',`${c.icon} ${c.name}을(를) 영면에 들게 하시겠습니까?\n\n동료는 영원히 떠나지만,\n영웅의 명예가 ${honorGain} 상승합니다.`,()=>{
          // Remove from deck
          this.deck=this.deck.filter(x=>x.uid!==c.uid);
          // Give honor to hero
          const hero=this.deck.find(x=>x.isHero);
          if(hero)hero.honor=(hero.honor||0)+honorGain;
          SFX.play('death');
          this.persist();this.showChurch();
        });
      };
      btns.appendChild(funBtn);
      wrap.appendChild(btns);g.appendChild(wrap);
    });
  },

  showTraining(){
    UI.modal('🏟️ 훈련장','동료 수련 기능이 곧 열립니다.\n\n골드를 사용하여 동료에게 경험을 쌓게 할 수 있습니다.\n\n(수련 시스템 준비 중)',null);
  },

  showShop(){
    UI.modal('🎭 암시장','비전과 유물 6 원소 로테이션 상점이 곧 문을 엽니다.\n\n(암시장 시스템 준비 중)',null);
  },

  // 2026-04-24: temple / inn 죽은 버튼 살리기. 본 시스템 구현 전까지 모달 안내.
  showTemple(){
    UI.modal('🔮 신전','제1세대 6 신을 모신 신전입니다.\n\n역대 점유자 회랑 · 명예의 전당 · 꺼진 신좌의 방이 곧 열립니다.\n\n(신전 시스템 준비 중)',null);
  },

  // 2026-04-27: 여관 = 휴식 → 살아있는 동료 전원 HP/NRG 풀 회복 (무료, 부상자 제외).
  // 부상자(죽은 자) 회복은 교회 골드 치료. 여관은 살아있는 동료의 누적 소모만 회복.
  showInn(){
    const alive=this.deck.filter(c=>!c.injured);
    const needRest=alive.filter(c=>{
      const hpCur=c.currentHp!=null?c.currentHp:c.hp;
      const nrgCur=c.curNrg!=null?c.curNrg:0;
      return hpCur<c.hp||nrgCur<(c.nrg||0);
    });
    if(needRest.length===0){
      UI.modal('🛏️ 여관','동료 전원이 만전입니다.\n\n다음 전투를 준비하세요.',null);
      return;
    }
    const lines=needRest.map(c=>{
      const hpCur=c.currentHp!=null?c.currentHp:c.hp;
      const nrgCur=c.curNrg!=null?c.curNrg:0;
      return `• ${c.icon||'🗡️'} ${c.name} — HP ${hpCur}/${c.hp}, ⚡${nrgCur}/${c.nrg||0}`;
    }).join('\n');
    UI.modal('🛏️ 여관 휴식',`${needRest.length}명의 동료가 휴식이 필요합니다.\n\n${lines}\n\n잠을 청해 만전으로 회복하시겠습니까?`,()=>{
      alive.forEach(c=>{c.currentHp=c.hp;c.curNrg=c.nrg||0;});
      SFX.play('heal');
      this.persist();
      UI.modal('🛏️ 휴식 완료','동료 전원이 만전으로 회복되었습니다.',null);
    });
  },

  // ── TUTORIAL ──
  LEAGUES:[
    {id:'bronze',   name:'브론즈',    min:0,    max:99,    color:'#cd7f32', icon:'🥉'},
    {id:'silver',   name:'실버',      min:100,  max:299,   color:'#c0c0c0', icon:'🥈'},
    {id:'gold',     name:'골드',      min:300,  max:599,   color:'#ffd700', icon:'🥇'},
    {id:'platinum', name:'플래티넘',  min:600,  max:999,   color:'#00cccc', icon:'💎'},
    {id:'diamond',  name:'다이아',    min:1000, max:1499,  color:'#00aaff', icon:'💠'},
    {id:'master',   name:'마스터',    min:1500, max:1999,  color:'#aa44ff', icon:'👑'},
    {id:'divine',   name:'신의 영역', min:2000, max:99999, color:'#ff4444', icon:'⚡'},
  ],
  getLeague(){
    const p=this.leaguePoints||0;
    return this.LEAGUES.find(l=>p>=l.min&&p<=l.max)||this.LEAGUES[0];
  },
  getLeagueProgress(){
    const l=this.getLeague();const p=this.leaguePoints||0;
    return Math.min(100,Math.floor((p-l.min)/(l.max-l.min+1)*100));
  },

});
