// Game Battle (전투 흐름 + 스킬 시스템)
// Generated by docs/_split_game.py — Phase 4
// DO NOT hand-edit keys — edit in original and re-run splitter if needed.

RoF.__gameKeys = RoF.__gameKeys || new Set();
(function(keys){
  for (const k of keys) {
    if (RoF.__gameKeys.has(k)) {
      console.error('[Game] 중복 키 감지:', k);
      RoF.__gameKeyError = true;
    }
    RoF.__gameKeys.add(k);
  }
})(["battleState", "selectedForBattle", "selectedRelics", "getCommandSlots", "getUsedSlots", "generateBot", "showMatchmaking", "startBattleFromMatch", "startBattle", "_startBattleInner", "renderCardSelect", "saveFormation", "loadFormation", "_applyFormation", "confirmCardSelect", "launchBattle", "genEnemy", "runBattleRound", "enemyMirrorDeploy", "enemyRoundActions", "_enemySingleAction"]);

Object.assign(RoF.Game, {
  battleState:null, // {pCards, eCards, currentRound, battleDeck, battleRelics}
  selectedForBattle:[], // uids of unit cards selected
  selectedRelics:[], // uids of relics selected

  getCommandSlots(){
    // 2026-04-13: 최소 4 보장 → 영웅 + 동료 4 = 총 5슬롯 확정
    // 영웅 레벨이 올라가면 더 많은 고레벨 동료를 수용할 지휘권 제공
    const hero=this.deck.find(c=>c.isHero);
    const lv=hero?(hero.level||1):1;
    return Math.max(4, lv);
  },

  getUsedSlots(){
    const hero=this.deck.find(c=>c.isHero);
    return this.selectedForBattle
      .filter(u=>u!==(hero?hero.uid:''))
      .reduce((sum,uid)=>{const c=this.deck.find(x=>x.uid===uid);return sum+(c?(c.level||1):1);},0);
  },

  // ── BOT MATCHMAKING ──
  generateBot(){
    const lg=this.getLeague();const lgIdx=this.LEAGUES.indexOf(lg);
    // Pick league ±1
    const botLgIdx=Math.max(0,Math.min(this.LEAGUES.length-1,lgIdx+Math.floor(Math.random()*3)-1));
    const botLg=this.LEAGUES[botLgIdx];
    const botName=enemyName();
    // Pick random hero gender + element + role
    const el=ELEMENTS[Math.floor(Math.random()*ELEMENTS.length)];
    const roles=['melee','ranged','support'];
    const role=roles[Math.floor(Math.random()*roles.length)];
    const gender=Math.random()<0.5?'m':'f';
    const heroBase=RoF.Data.createHero({gender, role, element:el});
    const roleName=HERO_ROLES.find(r=>r.id===role)?.name||'전사';
    return{name:botName,league:botLg,element:el,role:roleName,heroBase,
      heroIcon:heroBase.icon,level:Math.max(1,this.getHeroLevel()+Math.floor(Math.random()*3)-1)};
  },

  showMatchmaking(){
    UI.show('match-screen');SFX.bgm('match');
    const hero=this.deck.find(c=>c.isHero);
    const lg=this.getLeague();
    const box=document.getElementById('match-box');
    const heroClass=hero?(hero.heroClass||hero.type):'';
    const heroElem=hero?hero.element:'';
    // Phase 1: Searching — 내 쪽만 card-v2, 상대는 물음표 플레이스홀더
    box.innerHTML=`
      <div class="match-search" style="font-size:1.2rem;">⚔️ 도전자를 찾는 중<span class="dots">...</span></div>
      <div class="match-row" style="display:flex;align-items:center;justify-content:center;gap:40px;width:100%;margin-top:20px;">
        <div class="match-side match-enemy" style="text-align:center;">
          <div class="match-placeholder" style="width:280px;height:490px;border-radius:15px;border:3px dashed #444;background:rgba(0,0,0,.4);display:flex;align-items:center;justify-content:center;margin:0 auto;">
            <div style="font-size:4rem;opacity:.3;animation:dotPulse 1s infinite;">❓</div>
          </div>
          <div style="color:#555;font-size:1.1rem;font-weight:bold;margin-top:8px;">검색중...</div>
        </div>
        <div class="match-vs" style="opacity:.3;font-size:2.4rem;font-weight:bold;">VS</div>
        <div class="match-side match-player" style="text-align:center;" id="match-player-side"></div>
      </div>`;
    // V4 카드 삽입 (내 영웅)
    if(hero){
      const myCard=mkCardElV4(hero);myCard.classList.add('match-card');
      const side=document.getElementById('match-player-side');
      side.appendChild(myCard);
      const cap=document.createElement('div');cap.style.cssText='margin-top:8px;';
      cap.innerHTML=`<div style="color:#fff;font-size:1.3rem;font-weight:bold;font-family:'Cinzel','Georgia',serif;">${Auth.user}</div>
        <div style="color:${lg.color};font-size:.9rem;">${lg.icon} ${lg.name} Lv.${this.getHeroLevel()}</div>`;
      side.appendChild(cap);
    }
    // Phase 2: Found (after 2-3 sec)
    const delay=1500+Math.random()*1500;
    setTimeout(()=>{
      const bot=this.generateBot();
      this._currentBot=bot;
      SFX.play('magic');
      box.innerHTML=`
        <div style="color:#44ff88;font-size:1.2rem;margin-bottom:15px;" class="match-found">도전자가 나타났다!</div>
        <div class="match-row match-found" style="display:flex;align-items:center;justify-content:center;gap:40px;width:100%;">
          <div class="match-side match-enemy" style="text-align:center;" id="match-enemy-side"></div>
          <div class="match-vs" style="font-size:2.4rem;font-weight:bold;">VS</div>
          <div class="match-side match-player" style="text-align:center;" id="match-player-side"></div>
        </div>
        <div id="match-countdown" style="color:#ffcc44;font-size:1rem;margin-top:15px;text-align:center;">⏳ <span id="match-cd-num">15</span>초 후 자동 출전</div>
        <div style="display:flex;gap:15px;justify-content:center;margin-top:10px;">
          <button class="btn" onclick="Game._matchCDClear&&Game._matchCDClear();Game.startBattleFromMatch()" style="font-size:1.2rem;">⚔️ 출전!</button>
          <button class="btn btn-s btn-red" onclick="Game._matchCDClear&&Game._matchCDClear();Game.showMenu()">철수</button>
        </div>`;
      // 상대 V4 카드
      const enemySide=document.getElementById('match-enemy-side');
      const botCard=mkCardElV4(bot.heroBase);botCard.classList.add('match-card');
      enemySide.appendChild(botCard);
      const ecap=document.createElement('div');ecap.style.cssText='margin-top:8px;';
      ecap.innerHTML=`<div style="color:#fff;font-size:1.3rem;font-weight:bold;font-family:'Cinzel','Georgia',serif;">${bot.name}</div>
        <div style="color:${bot.league.color};font-size:.9rem;">${bot.league.icon} ${bot.league.name} Lv.${bot.level}</div>
        <div style="color:#aaa;font-size:.8rem;">${bot.roleName||bot.role} · ${ELEM_ICON[bot.element]} ${ELEM_L[bot.element]}</div>`;
      enemySide.appendChild(ecap);
      // 내 V4 카드
      if(hero){
        const mySide=document.getElementById('match-player-side');
        const myCard=mkCardElV4(hero);myCard.classList.add('match-card');
        mySide.appendChild(myCard);
        const pcap=document.createElement('div');pcap.style.cssText='margin-top:8px;';
        pcap.innerHTML=`<div style="color:#fff;font-size:1.3rem;font-weight:bold;font-family:'Cinzel','Georgia',serif;">${Auth.user}</div>
          <div style="color:${lg.color};font-size:.9rem;">${lg.icon} ${lg.name} Lv.${this.getHeroLevel()}</div>
          <div style="color:#aaa;font-size:.8rem;">${heroClass} · ${heroElem?ELEM_ICON[heroElem]+' '+ELEM_L[heroElem]:''}</div>`;
        mySide.appendChild(pcap);
      }
      // 15초 카운트다운 → 자동 출전
      let cdLeft=15;
      const cdNum=document.getElementById('match-cd-num');
      this._matchCDClear=()=>{if(this._matchCDTimer){clearInterval(this._matchCDTimer);this._matchCDTimer=null;}};
      this._matchCDTimer=setInterval(()=>{
        cdLeft--;
        const el=document.getElementById('match-cd-num');
        if(el)el.textContent=cdLeft;
        if(cdLeft<=0){
          this._matchCDClear();
          if(document.getElementById('match-screen')&&document.getElementById('match-screen').classList.contains('active')){
            this.startBattleFromMatch();
          }
        }
      },1000);
    },delay);
  },

  startBattleFromMatch(){
    // 매칭 확인 후 → 바로 전투 (배치 없음)
    const battleDeck=this.deck.filter(c=>this.selectedForBattle.includes(c.uid));
    const battleRelics=(this.ownedRelics||[]).filter(r=>this.selectedRelics.includes(r.uid));
    this._deckSnapshot=this.deck.map(c=>({...c,equips:[...(c.equips||[])]}));
    this.battleState={currentRound:0,pCards:null,eCards:null,battleDeck:battleDeck.map(c=>({...c,equips:[...(c.equips||[])]})),battleRelics:battleRelics};
    this.launchBattle();
  },

  startBattle(){
    // 2026-04-24: 건물 Lv 시스템 폐기 — gate 건설 가드 제거 (모든 건물 항상 활성).
    this.checkTutorial('first_battle');
    this.selectedForBattle=[];this.selectedRelics=[];
    this._startBattleInner();
  },

  _startBattleInner(){
    const nonHero=this.deck.filter(c=>!c.isHero);
    const hasRelics=(this.ownedRelics||[]).length>0;
    if(nonHero.length===0&&!hasRelics){
      const hero=this.deck.find(c=>c.isHero);
      if(hero)this.selectedForBattle=[hero.uid];
      this.confirmCardSelect();
      return;
    }
    UI.show('cardselect-screen');
    document.getElementById('cs-name').textContent=`👤 ${Auth.user}`;
    document.getElementById('cs-slots').textContent=this.getCommandSlots();
    this.renderCardSelect();
  },

  renderCardSelect(){
    const grid=document.getElementById('cs-grid');
    const selDiv=document.getElementById('cs-selected');
    const maxSlots=this.getCommandSlots();
    grid.innerHTML='';selDiv.innerHTML='';

    const hero=this.deck.find(c=>c.isHero);
    if(hero&&!this.selectedForBattle.includes(hero.uid)){
      this.selectedForBattle=[hero.uid,...this.selectedForBattle.filter(u=>u!==hero.uid)];
    }

    const usedSlots=this.getUsedSlots();

    // Show ALL cards in grid (hero included, marked as auto)
    this.deck.forEach(c=>{
      const isInjured=!!c.injured;
      const isSel=this.selectedForBattle.includes(c.uid);
      const cardCost=c.isHero?0:(c.level||1);
      const selUnitCount=this.selectedForBattle.filter(uid=>uid!==(hero?hero.uid:'')).length;
      const canAdd=!isSel&&!c.isHero&&!isInjured&&(usedSlots+cardCost<=maxSlots)&&selUnitCount<4;
      const el=mkCardElV4(c);
      if(c.isHero){
        el.style.opacity='1';
        el.classList.add('selected');
      } else if(isInjured){
        el.style.opacity='.3';el.style.filter='grayscale(.8)';
      } else {
        el.style.opacity=isSel?'1':canAdd?'.6':'.25';
        if(isSel)el.classList.add('selected');
      }
      const badge=document.createElement('div');
      badge.style.cssText='text-align:center;font-size:.7rem;margin-top:2px;';
      if(c.isHero){badge.style.color='#ffd700';badge.textContent='⭐ 자동 출전';}
      else if(isInjured){badge.style.color='#ff4444';badge.textContent='🩹 부상 — 교회에서 치유 필요';}
      else{badge.style.color=isSel?'#44ff88':'#ffaa44';badge.textContent=isSel?'✅ 출전 중':`지휘권 ${cardCost} 소비`;}
      // V4 카드는 overflow:hidden 이라 badge 를 카드 밖에 두기 위해 wrapper 로 감쌈
      const wrap=document.createElement('div');
      wrap.className='cs-card-wrap';
      wrap.appendChild(el);
      wrap.appendChild(badge);
      if(!c.isHero&&!isInjured){
        el.onclick=()=>{
          if(isSel){this.selectedForBattle=this.selectedForBattle.filter(u=>u!==c.uid);}
          else{
            if(selUnitCount>=4){document.getElementById('cs-info').textContent=`⚠️ 최대 4명까지 출전 가능!`;return;}
            if(usedSlots+cardCost>maxSlots){document.getElementById('cs-info').textContent=`⚠️ 지휘권 부족! (필요:${cardCost}, 남은:${maxSlots-usedSlots})`;return;}
            this.selectedForBattle.push(c.uid);
          }
          SFX.play('click');this.renderCardSelect();
        };
      }
      grid.appendChild(wrap);
    });

    // Show selected in top area
    const allSel=this.deck.filter(c=>this.selectedForBattle.includes(c.uid));
    allSel.forEach(c=>{
      const mini=mkMini(c);
      mini.style.width='60px';mini.style.height='80px';
      mini.querySelector('.dm-icon').style.fontSize='1.5rem';
      selDiv.appendChild(mini);
    });

    // Relic selection
    const maxRSlots=this.getRelicSlots();
    const rGrid=document.getElementById('cs-relics-grid');rGrid.innerHTML='';
    const rSelDiv=document.getElementById('cs-relics-selected');rSelDiv.innerHTML='';
    const owned=this.ownedRelics||[];
    const usedR=this.selectedRelics.length;

    owned.forEach(r=>{
      const isSel=this.selectedRelics.includes(r.uid);
      const el=mkRelicEl(r);
      el.style.opacity=isSel?'1':usedR<maxRSlots?'.6':'.25';
      if(isSel)el.style.boxShadow='0 0 12px rgba(170,102,255,.5)';
      el.onclick=()=>{
        if(isSel){this.selectedRelics=this.selectedRelics.filter(u=>u!==r.uid);}
        else{
          if(usedR>=maxRSlots){document.getElementById('cs-info').textContent=`⚠️ 유물 보유량 초과! (최대 ${maxRSlots})`;return;}
          this.selectedRelics.push(r.uid);
        }
        SFX.play('click');this.renderCardSelect();
      };
      rGrid.appendChild(el);
    });
    if(!owned.length)rGrid.innerHTML='<div style="color:#555;font-size:.75rem;">소지한 유물 없음</div>';

    // Show selected relics
    const selR=owned.filter(r=>this.selectedRelics.includes(r.uid));
    selR.forEach(r=>{
      const d=document.createElement('div');d.style.cssText='text-align:center;font-size:.7rem;';
      d.innerHTML=`<span style="font-size:1.3rem;">${r.icon}</span><br><span style="color:#ccc;">${r.name}</span>`;
      rSelDiv.appendChild(d);
    });
    if(!selR.length)rSelDiv.innerHTML='<div style="color:#555;font-size:.75rem;">유물 미선택</div>';

    const newUsed=this.getUsedSlots();
    const finalUnitCount=this.selectedForBattle.filter(uid=>uid!==(hero?hero.uid:'')).length;
    document.getElementById('cs-info').textContent=`동료 ${finalUnitCount}/4 | 지휘권 ${newUsed}/${maxSlots} | 유물 ${usedR}/${maxRSlots}`;
    document.getElementById('cs-rslots').textContent=maxRSlots;
    document.getElementById('cs-go-btn').disabled=false;
  },

  saveFormation(){
    const f={units:[...this.selectedForBattle],relics:[...this.selectedRelics]};
    this.savedFormations=this.savedFormations||[];
    if(this.savedFormations.length>=3)this.savedFormations.shift(); // max 3
    this.savedFormations.push(f);
    this.persist();SFX.play('upgrade');
    document.getElementById('cs-info').textContent=`📜 편성이 기억되었습니다! (${this.savedFormations.length}/3)`;
  },
  loadFormation(){
    if(!this.savedFormations||!this.savedFormations.length){
      document.getElementById('cs-info').textContent='⚠️ 저장된 편성이 없습니다. 먼저 "편성 기억"을 눌러주세요.';return;
    }
    // Show selection if multiple
    if(this.savedFormations.length===1){
      this._applyFormation(this.savedFormations[0]);return;
    }
    const items=this.savedFormations.map((f,i)=>`편성 ${i+1}: 동료 ${f.units.length}명, 유물 ${f.relics.length}개`).join('\n');
    // Use last saved
    this._applyFormation(this.savedFormations[this.savedFormations.length-1]);
  },
  _applyFormation(f){
    // Only apply units that still exist in deck
    const validUnits=f.units.filter(uid=>this.deck.some(c=>c.uid===uid&&!c.injured));
    const validRelics=f.relics.filter(uid=>(this.ownedRelics||[]).some(r=>r.uid===uid));
    this.selectedForBattle=validUnits;this.selectedRelics=validRelics;
    SFX.play('card_reveal');
    this.renderCardSelect();
    document.getElementById('cs-info').textContent=`📜 편성이 소환되었습니다! (동료 ${validUnits.length}명)`;
  },

  confirmCardSelect(){
    const battleDeck=this.deck.filter(c=>this.selectedForBattle.includes(c.uid));
    if(!battleDeck.find(c=>c.isHero)){
      document.getElementById('cs-info').textContent='⚠️ 영웅이 필요합니다!';return;
    }
    // 편성 완료 → 매칭 화면으로
    this.showMatchmaking();
  },

  launchBattle(){
    const bs=this.battleState;
    if(!bs || !bs.battleDeck){
      console.warn('[launchBattle] battleState not ready — confirmCardSelect 이전 경로일 수 있음');
      return;
    }
    if(!bs.pCards){
      bs.pCards=bs.battleDeck.map(c=>({...c,currentHp:c.hp,maxBHp:c.maxHp||c.hp,side:'player',row:c.formRow||'front',frozen:0,poisoned:0,revived:false,invincible:0,curNrg:0,curShield:c.shield||0,burn:0}));
      bs.battleRelics.forEach(r=>applyRelicBattle(r,bs.pCards));
      const rawE=this.genEnemy();
      rawE.forEach(c=>{c.row=(c.type==='전사'||c.type==='야수')?'front':'back';});
      bs.eCards=rawE.map(c=>({...c,currentHp:c.hp,maxBHp:c.maxHp||c.hp,side:'enemy',frozen:0,poisoned:0,revived:false,invincible:0,curNrg:0,curShield:c.shield||0,burn:0}));
      this.enemyMirrorDeploy(bs);
    }
    if(!bs.currentRound)bs.currentRound=1;// 첫 진입시만
    this.persist();
    // PHASE 3 시네마틱 전투 어댑터 (블로커 #3 배선)
    // FEATURE.CINEMATIC_BATTLE=true 이면 v2 엔진으로 라우트. 실패 시 레거시 fallback.
    if(RoF && RoF.FEATURE && RoF.FEATURE.CINEMATIC_BATTLE
       && RoF.Battle && typeof RoF.Battle.startFromLegacyBS === 'function'){
      const ok = RoF.Battle.startFromLegacyBS(bs);
      if(ok !== false) return;
      console.warn('[battle] v2 adapter failed, fallback to legacy TurnBattle');
    }
    TurnBattle.start(bs);
  },

  genEnemy(){
    // Match enemy to player's hero level & deployed card rarities
    const myHero=this.deck.find(c=>c.isHero);
    const myLv=myHero?(myHero.level||1):1;
    const myRar=myHero?(myHero.rarity||'bronze'):'bronze';
    // Enemy hero: same rarity tier as player hero (±1 random)
    const ri=R_ORDER.indexOf(myRar);
    const eRarIdx=Math.max(0,Math.min(R_ORDER.length-2,ri+Math.floor(Math.random()*3)-1));
    const heroRar=R_ORDER[eRarIdx];
    const heroPool=UNITS.filter(u=>u.rarity===heroRar);
    const hBase=(heroPool.length?heroPool:UNITS)[Math.floor(Math.random()*(heroPool.length||UNITS.length))];
    // Enemy hero level = player hero level (±1)
    const eLv=Math.max(1,myLv+Math.floor(Math.random()*3)-1);
    const scale=1+(eLv-1)*.1;
    const eHero={...hBase,uid:'eh_'+uid(),name:enemyName(),isHero:true,rarity:heroRar,level:eLv,equips:[],
      atk:Math.round(hBase.atk*scale),hp:Math.round(hBase.hp*scale),maxHp:Math.round(hBase.hp*scale),def:Math.round(hBase.def*scale)};
    return [eHero];
  },

  // Add a random minion to enemy (called between rounds)

  async runBattleRound(){
   try{
    const bs=this.battleState;
    const pCards=bs.pCards,eCards=bs.eCards;
    const rd=bs.currentRound; // Round N = N attacks each

    this.battleRunning=true;this.skipReq=false;this.battleSpeed=Math.floor(500/this.battleMultiplier);
    document.getElementById('b-round').textContent=rd;
    document.getElementById('b-hp').textContent=this.hp;
    document.getElementById('battle-log').innerHTML='';
    document.getElementById('b-status').textContent='전투 중...';

    // Reset frozen/poison each round
    [...pCards,...eCards].forEach(c=>{c.frozen=0;c.poisoned=0;});

    this.renderBF(pCards,eCards);
    this.log(`═══ 라운드 ${rd} (${rd}번 공격) ═══`,'');

    for(let atNum=0;atNum<rd&&this.battleRunning;atNum++){
      this.log(`── 공격 ${atNum+1}/${rd} ──`,'');
      document.getElementById('b-banner').textContent=`⚔️ 라운드${rd} — 공격 ${atNum+1}/${rd}`;

      const all=[...pCards,...eCards].filter(c=>c.currentHp>0).sort((a,b)=>{
        const af=a.skill==='first_strike'?100:0,bf=b.skill==='first_strike'?100:0;
        return(b.spd+bf)-(a.spd+af);});

      for(const u of all){
        if(u.currentHp<=0||!this.battleRunning)continue;
        if(u.frozen>0){u.frozen--;this.log(`${u.icon} 빙결!`,'ability-log');continue;}
        const foes=(u.side==='player'?eCards:pCards).filter(c=>c.currentHp>0);
        const allies=(u.side==='player'?pCards:eCards).filter(c=>c.currentHp>0);
        if(!foes.length)break;

        // === REGEN (턴 시작) ===
        if(u.hpReg>0){u.currentHp=Math.min(u.currentHp+(u.hpReg||0),u.maxBHp);}
        u.curNrg=(u.curNrg||0)+(u.nrgReg||0);
        // Status ticks
        if(u.burn>0){const bd=u.burnDmg||2;u.currentHp-=bd;u.burn--;this.showDmg(u,bd,false);this.log(`${u.icon} 화상-${bd}`,'ability-log');if(u.currentHp<=0){u.currentHp=0;continue;}}
        if(u.noHeal>0)u.noHeal--;

        // === CHECK ACTION TYPE ===
        const uAction=u.action||'attack'; // 'attack','none','counter','skill_only'

        // === PASSIVE SKILLS (공격 전) ===
        const sk=u.skill,skT=u.skillType||'passive',skCh=u.skillChance||1,skNrg=u.skillNrg||0;
        let packBonus=0;
        // Passive skills that modify attack or state
        if(sk==='pack')packBonus=allies.filter(c=>c.type==='야수').length*2;
        if(sk==='frenzy'&&u.currentHp<=u.maxBHp*.5){this.log(`${u.icon} 광기!`,'ability-log');}

        // === TARGET ===
        const taunts=foes.filter(c=>c.skill==='taunt');
        const frontFoes=foes.filter(c=>c.row==='front');
        let targetPool=taunts.length?taunts:frontFoes.length?frontFoes:foes;
        let target=targetPool[Math.floor(Math.random()*targetPool.length)];
        // Player target override (if set and valid, not taunted)
        if(u.side==='player'&&this._playerTarget&&!taunts.length){
          const pt=foes.find(c=>c.uid===this._playerTarget&&c.currentHp>0);
          if(pt)target=pt;
        }

        // === DAMAGE CALC ===
        let atk=u.atk+packBonus;let isCrit=false;
        const critCh=Math.min(.05+(u.luck||0)*.015,.6);
        if(sk==='crit'&&Math.random()<skCh){atk*=3;isCrit=true;this.log(`${u.icon} 급소!`,'ability-log');}
        else if(Math.random()<critCh){atk*=2;isCrit=true;}
        if(sk==='frenzy'&&u.currentHp<=u.maxBHp*.5)atk*=2;
        // 2026-04-21: rage 스탯 제거 — 분노 시 atk 증폭 로직 삭제.

        let strikes=1;
        // Active skill: double_cast / multi_head (check energy)
        if(sk==='double_cast'&&skT==='active'&&u.curNrg>=skNrg&&Math.random()<skCh){strikes=2;u.curNrg-=skNrg;this.log(`${u.icon} 더블캐스트!`,'ability-log');}
        if(sk==='multi_head'&&skT==='active'&&u.curNrg>=skNrg&&Math.random()<skCh){strikes=Math.min(3,foes.length);u.curNrg-=skNrg;this.log(`${u.icon} 다두공격!`,'ability-log');}

        // === ATTACK PHASE (non-attackers skip) ===
        if(uAction!=='none'&&uAction!=='skill_only'){
          await this.showAction(u,isCrit?'치명타!':'공격!',target);
          for(let s=0;s<strikes;s++){
            let ct=sk==='multi_head'?foes[s%foes.length]:target;
            if(!ct||ct.currentHp<=0){const al=foes.filter(c=>c.currentHp>0);if(!al.length)break;ct=al[0];}
            let dmg=atk;
            const isMagic=u.type==='마법사';
            if(sk!=='pierce'){const dr=ct.def||0;const armorVal=(ct.skill==='armor')?((ct.skillArmor!=null)?ct.skillArmor:3):0;dmg=(ct.skill==='armor')?Math.max(1,dmg-dr-armorVal):Math.max(1,dmg-Math.floor(dr*.5));}
            const evaC=Math.min(.05+(ct.eva||0)*.02,.6);
            if(!isMagic&&Math.random()<(ct.skill==='dodge'?Math.min(evaC+.3,.7):evaC)){this.log(`${ct.icon} 회피!`,'ability-log');continue;}
            if(isMagic){const mevaC=Math.min(.05+(ct.meva||0)*.025,.5);if(Math.random()<mevaC){this.log(`${ct.icon} 마법회피!`,'ability-log');continue;}}
            if(ct.invincible>0){ct.invincible--;this.log(`${ct.icon} 무적!`,'ability-log');continue;}
            if(ct.divineShield){ct.divineShield=false;this.log(`${ct.icon} 신성방패!`,'ability-log');continue;}
            // 2026-04-19 P1-A: 반사신경 (proc_nullify_hit) — 확률로 피격 무효
            if(ct._procNullifyHit && Math.random()*100 < ct._procNullifyHit){this.log(`${ct.icon} 반사신경! 피해 무효`,'ability-log');continue;}
            if((ct.curShield||0)>0){const ab=Math.min(ct.curShield,dmg);ct.curShield-=ab;dmg-=ab;if(ab>0)this.log(`${ct.icon} 보호막-${ab}`,'ability-log');}
            dmg=Math.max(0,dmg);
            ct.currentHp-=dmg;
            this.showAtkEffect(u,ct);SFX.play(isMagic?'magic':'slash');SFX.play('hit');
            this.showDmg(ct,dmg,isCrit);
            this.log(`${u.icon}${u.name}→${ct.icon}${ct.name} ${dmg}${isCrit?' 치명타!':''}`,'atk-log');
            // 2026-04-19 P1-A: 이중 캐스팅 (proc_double_cast) — 확률로 데미지 한 번 더
            if(u._procDoubleCast && Math.random()*100 < u._procDoubleCast && ct.currentHp>0){
              ct.currentHp -= dmg;
              this.showDmg(ct, dmg, false);
              this.log(`${u.icon} 이중 캐스팅! 추가 ${dmg}`,'ability-log');
            }
            // On-attack triggers
            const bt=u.bonusTrigger;
            if(bt&&bt.on==='attack'&&Math.random()<bt.chance){
              if(bt.effect==='double_arrow'){ct.currentHp-=Math.floor(dmg*.5);this.log(`${u.icon} 쌍발!`,'ability-log');}
              if(bt.effect==='cleave'){const adj=foes.filter(c=>c.currentHp>0&&c.uid!==ct.uid);if(adj.length){adj[0].currentHp-=Math.floor(dmg*.5);this.log(`${u.icon} 광역!`,'ability-log');}}
              if(bt.effect==='backstab'){ct.currentHp-=Math.floor(dmg*.5);this.log(`${u.icon} 기습!`,'ability-log');}
              if(bt.effect==='headshot'){ct.currentHp-=Math.floor(ct.maxBHp*.1);this.log(`${u.icon} 헤드샷!`,'ability-log');}
              if(bt.effect==='frostbite'){ct.spd=Math.max(1,(ct.spd||5)-3);}
              if(bt.effect==='regen_head'){u.currentHp=Math.min(u.currentHp+8,u.maxBHp);this.showHeal(u,8);}
            }
            // On-hit triggers (defender)
            const dbt=ct.bonusTrigger;
            if(dbt&&dbt.on==='hit'&&Math.random()<dbt.chance&&ct.currentHp>0&&!u._noCounter){
              if(dbt.effect==='counter'&&(u.range||'melee')==='melee'&&ct.row==='front'){u._noCounter=true;const cd=Math.floor(ct.atk*.5);u.currentHp-=cd;this.showDmg(u,cd,false);this.log(`${ct.icon} 반격! ${cd}`,'ability-log');u._noCounter=false;}
              else if(dbt.effect==='thorns'){const td=(dbt.value!=null)?dbt.value:4;u.currentHp-=td;this.showDmg(u,td,false);this.log(`${ct.icon} 가시!`,'ability-log');}
              else if(dbt.effect==='flame_aura'){u.currentHp-=5;this.showDmg(u,5,false);this.log(`${ct.icon} 화염오라!`,'ability-log');}
              else if(dbt.effect==='mirror_break'){u.def=Math.max(0,(u.def||0)-2);}
              else if(dbt.effect==='energy_burst'){(ct.side==='player'?pCards:eCards).filter(a=>a.currentHp>0).forEach(a=>{a.curNrg=(a.curNrg||0)+2;});}
            }
            // Passive drain/steal
            if(sk==='drain'&&Math.random()<skCh){const h=Math.floor(dmg*.5);u.currentHp=Math.min(u.currentHp+h,u.maxBHp);this.showHeal(u,h);}
            if(sk==='life_steal'&&Math.random()<skCh){u.currentHp=Math.min(u.currentHp+dmg,u.maxBHp);this.showHeal(u,dmg);}
            if(sk==='freeze'&&skT==='active'&&u.curNrg>=skNrg&&Math.random()<skCh){ct.frozen=1;u.curNrg-=skNrg;this.log(`${ct.icon} 빙결!`,'ability-log');}
            // Death + kill triggers
            if(ct.currentHp<=0){
              if(this._reviveIfCan(ct)){this.triggerSlowMo(1200,'revive');}
              else{
                ct.currentHp=0;SFX.play('death');this.log(`${ct.icon} 쓰러짐!`,'atk-log');this.triggerSlowMo(800,'kill');
                const kbt=u.bonusTrigger;
                if(kbt&&kbt.on==='kill'&&Math.random()<kbt.chance){
                  if(kbt.effect==='howl'){allies.filter(c=>c.type==='야수'&&c.currentHp>0).forEach(a=>{a.atk+=1;});}
                  if(kbt.effect==='stealth'){u._stealthNext=true;}
                  if(kbt.effect==='soul_harvest'){u.atk+=3;}
                  if(kbt.effect==='raise_dead'){(u.side==='player'?pCards:eCards).push({...ct,uid:'z_'+uid(),name:'좀비'+ct.name,side:u.side,isHero:false,currentHp:Math.floor(ct.maxBHp*.3),maxBHp:Math.floor(ct.maxBHp*.3),atk:Math.floor(ct.atk*.5),skill:'none',equips:[],bonusTrigger:null});}
                }
              }
            }
            // Attacker died from counter/thorns
            if(u.currentHp<=0){u.currentHp=0;break;}
          }
        }

        // === ACTIVE SKILLS (공격 후 발동) — all units ===
        // Skip if player manually activated this turn
        if(u._manualUsed){u._manualUsed=false;}
        else{
        if(sk==='aoe'&&skT==='active'&&u.curNrg>=skNrg&&Math.random()<skCh){
          u.curNrg-=skNrg;const d=3;foes.filter(c=>c.currentHp>0).forEach(e=>{e.currentHp-=d;this.showDmg(e,d,false);if(e.currentHp<=0 && !this._reviveIfCan(e)) e.currentHp=0;});
          this.log(`${u.icon} 화염! 전체${d} (에너지-${skNrg})`,'ability-log');
        }
        if(sk==='breath'&&skT==='active'&&u.curNrg>=skNrg&&Math.random()<skCh){
          u.curNrg-=skNrg;const d=5;foes.filter(c=>c.currentHp>0).forEach(e=>{e.currentHp-=d;this.showDmg(e,d,false);if(e.currentHp<=0 && !this._reviveIfCan(e)) e.currentHp=0;});
          this.log(`${u.icon} 브레스! 전체${d} (에너지-${skNrg})`,'ability-log');
        }
        if(sk==='heal_self'&&skT==='active'&&u.curNrg>=skNrg&&Math.random()<skCh&&!(u.noHeal>0)){
          u.curNrg-=skNrg;const h=4;u.currentHp=Math.min(u.currentHp+h,u.maxBHp);this.showHeal(u,h);SFX.play('heal');
          this.log(`${u.icon} 자가치유+${h} (에너지-${skNrg})`,'heal-log');
        }
        if(sk==='heal_ally'&&skT==='active'&&u.curNrg>=skNrg&&Math.random()<skCh){
          const w=allies.filter(c=>c.currentHp<c.maxBHp&&c.uid!==u.uid&&!(c.noHeal>0));
          if(w.length){u.curNrg-=skNrg;const t=w.reduce((a,b)=>a.currentHp<b.currentHp?a:b);const h=5;t.currentHp=Math.min(t.currentHp+h,t.maxBHp);this.showHeal(t,h);SFX.play('heal');this.log(`${u.icon}→${t.icon} 치유+${h} (에너지-${skNrg})`,'heal-log');}
        }
        if(sk==='inspire'&&skT==='active'&&u.curNrg>=skNrg&&Math.random()<skCh){
          u.curNrg-=skNrg;allies.forEach(a=>{if(a.uid!==u.uid)a.atk+=2;});this.log(`${u.icon} 고무! 아군 공격+2 (에너지-${skNrg})`,'ability-log');
        }
        if(sk==='mass_heal'&&skT==='active'&&u.curNrg>=skNrg&&Math.random()<skCh){
          u.curNrg-=skNrg;allies.forEach(a=>{a.currentHp=Math.min(a.currentHp+3,a.maxBHp);});SFX.play('heal');this.log(`${u.icon} 대치유! 아군전체 HP+3 (에너지-${skNrg})`,'heal-log');
        }
        if(sk==='dark_bolt'&&skT==='active'&&u.curNrg>=skNrg&&Math.random()<skCh){
          u.curNrg-=skNrg;const t=foes.filter(c=>c.currentHp>0);if(t.length){const dt=t[Math.floor(Math.random()*t.length)];dt.currentHp-=8;this.showDmg(dt,8,false);this.log(`${u.icon} 암흑탄! ${dt.icon}-8 (에너지-${skNrg})`,'ability-log');}
        }
        if(sk==='aura_buff'&&skT==='active'&&u.curNrg>=skNrg&&Math.random()<skCh){
          u.curNrg-=skNrg;allies.forEach(a=>{a.atk+=1;a.def=(a.def||0)+1;});this.log(`${u.icon} 오라! 아군 공격+1 방어+1 (에너지-${skNrg})`,'ability-log');
        }
        // Bonus trigger: on skill (re-get bt since it may be scoped inside attack block)
        const bt=u.bonusTrigger;
        if(bt&&bt.on==='skill'&&Math.random()<bt.chance){
          if(bt.effect==='group_heal'){allies.forEach(a=>{a.currentHp=Math.min(a.currentHp+2,a.maxBHp);});this.log(`${u.icon} 집단치유!`,'heal-log');}
          if(bt.effect==='bless'){const ra=allies.filter(c=>c.currentHp>0);if(ra.length){const t=ra[Math.floor(Math.random()*ra.length)];t.curShield=(t.curShield||0)+3;this.log(`${t.icon} 축복! 보호막+3`,'ability-log');}}
          if(bt.effect==='ignite'){foes.filter(c=>c.currentHp>0).forEach(e=>{e.burn=2;e.burnDmg=3;});this.log(`${u.icon} 점화! 적전체 화상2턴`,'ability-log');}
          if(bt.effect==='encore'){u.curNrg+=(skNrg*.5);this.log(`${u.icon} 앙코르! 에너지환원`,'ability-log');}
          if(bt.effect==='divine_shield'){u.divineShield=true;this.log(`${u.icon} 신성방패!`,'ability-log');}
          if(bt.effect==='arcane_burst'){foes.filter(c=>c.currentHp>0).forEach(e=>{e.currentHp-=2;this.showDmg(e,2,false);});this.log(`${u.icon} 비전폭발! 전체-2`,'ability-log');}
          if(bt.effect==='curse'){const t=foes.filter(c=>c.currentHp>0);if(t.length){t[0].noHeal=2;this.log(`${t[0].icon} 저주! 회복불가2턴`,'ability-log');}}
          if(bt.effect==='inferno'){foes.filter(c=>c.currentHp>0).forEach(e=>{e.burn=2;e.burnDmg=2;});this.log(`${u.icon} 업화! 적전체 화상`,'ability-log');}
        }
        } // end else (manual skill check)
        // Stealth from previous kill
        if(u._stealthNext){u._stealthNext=false;u.eva+=100;}

        // Poison tick
        if(u.poisoned>0){u.currentHp-=2;u.poisoned--;this.showDmg(u,2,false);if(u.currentHp<=0)u.currentHp=0;}

        this.renderBF(pCards,eCards);
        if(!this.skipReq)await wait(this.battleSpeed);

        // Check hero deaths → battle ends immediately
        const pH=pCards.find(c=>c.isHero);const eH=eCards.find(c=>c.isHero);
        if(pH&&pH.currentHp<=0){this.battleRunning=false;break;}
        if(eH&&eH.currentHp<=0){this.battleRunning=false;break;}
      }
      // Check after each attack cycle
      const pH=pCards.find(c=>c.isHero);const eH=eCards.find(c=>c.isHero);
      if(!pH||pH.currentHp<=0||!eH||eH.currentHp<=0)break;
    }

    SFX.bgm(false);
    const pH=pCards.find(c=>c.isHero);const eH=eCards.find(c=>c.isHero);
    const enemyHeroDead=eH&&eH.currentHp<=0;
    const myHeroDead=pH&&pH.currentHp<=0;

    if(enemyHeroDead){
      // === VICTORY ===
      this.totalWins++;SFX.play('fanfare');
      // Victory banner + sparkles
      const vb=document.createElement('div');vb.className='victory-banner';vb.textContent='승전!';document.body.appendChild(vb);setTimeout(()=>vb.remove(),2000);
      const sp=document.createElement('div');sp.className='victory-particles';for(let i=0;i<20;i++){const s=document.createElement('div');s.className='victory-sparkle';s.textContent=['✨','⭐','💫','🌟'][i%4];s.style.left=Math.random()*100+'%';s.style.animationDelay=Math.random()*1+'s';sp.appendChild(s);}document.body.appendChild(sp);setTimeout(()=>sp.remove(),3000);
      const goldR=10,xpR=10,honorR=10,lpR=15;
      this.gold+=goldR;this.leaguePoints=Math.max(0,(this.leaguePoints||0)+lpR);
      if(this.leaguePoints>=100&&this.tutStep===13)this.checkTutorial('reach_silver');
      // Give XP & honor to each participating card (find originals in deck)
      const participated=bs.battleDeck.map(c=>c.uid);
      const levelUps=[];
      this.deck.filter(c=>participated.includes(c.uid)).forEach(c=>{
        if(this.giveCardXp(c,xpR))levelUps.push(c.name);
        this.giveCardHonor(c,honorR);
      });
      this.persist();
      this.showBattleEnd(true,goldR,xpR,honorR,levelUps);
    } else if(myHeroDead){
      // === DEFEAT ===
      const goldR=3,xpR=10,honorR=1,lpR=-5;
      this.gold+=goldR;this.leaguePoints=Math.max(0,(this.leaguePoints||0)+lpR);
      const participated=bs.battleDeck.map(c=>c.uid);
      const levelUps=[];
      this.deck.filter(c=>participated.includes(c.uid)).forEach(c=>{
        if(this.giveCardXp(c,xpR))levelUps.push(c.name);
        this.giveCardHonor(c,honorR);
      });
      SFX.play('death');
      // Hero death overlay + slowmo
      const hdo=document.createElement('div');hdo.className='hero-death-overlay';document.body.appendChild(hdo);setTimeout(()=>hdo.remove(),2000);
      this.persist();
      this.showBattleEnd(false,goldR,xpR,honorR,levelUps);
    } else {
      // === Round survived, no hero dead → choices then next round ===
      this.skipReq=false;
      this.showRoundChoice();
    }
   }catch(err){console.error('Battle error:',err);this.log(`⚠️ 에러: ${err.message}`,'atk-log');SFX.bgm(false);this.battleRunning=false;}
  },

  // Show choices between rounds (NO rewards, just choices)
  // Enemy AI picks from same 3 choices, prefers best option
  // Enemy mirrors player's initial deployment (similar units/skills/relics)
  enemyMirrorDeploy(bs){
    const myHero=this.deck.find(c=>c.isHero);
    const myLv=myHero?(myHero.level||1):1;
    const diff=this.totalWins+this.getHeroLevel(); // 난이도 변수 (스킬/유물 등급용)
    const scale=1+(myLv-1)*.1;
    const playerUnits=bs.pCards.filter(c=>!c.isHero);
    const playerRelics=bs.battleRelics.length;
    // Collect player unit rarities to match
    const pRarities=playerUnits.map(c=>c.rarity||'bronze');

    // Add similar number of units matching player's rarity spread
    const eMinionCount=Math.max(0,playerUnits.length+Math.floor(Math.random()*3)-1);
    for(let i=0;i<eMinionCount;i++){
      // Pick rarity similar to player's units
      const targetRar=pRarities.length?pRarities[i%pRarities.length]:'bronze';
      const ri=R_ORDER.indexOf(targetRar);
      const eRi=Math.max(0,Math.min(R_ORDER.length-2,ri+Math.floor(Math.random()*3)-1));
      const r=R_ORDER[eRi];
      let pool=UNITS.filter(u=>u.rarity===r&&!u.id.startsWith('h_'));if(!pool.length)pool=UNITS.filter(u=>u.rarity==='bronze'&&!u.id.startsWith('h_'));
      const b=pool[Math.floor(Math.random()*pool.length)];
      const m={...b,uid:'e_'+uid(),level:Math.max(1,myLv+Math.floor(Math.random()*2)-1),equips:[],
        atk:Math.round(b.atk*scale),hp:Math.round(b.hp*scale),maxHp:Math.round(b.hp*scale),def:Math.round(b.def*scale),
        currentHp:Math.round(b.hp*scale),maxBHp:Math.round(b.hp*scale),side:'enemy',
        row:(b.type==='전사'||b.type==='야수')?'front':'back',frozen:0,poisoned:0,revived:false,invincible:0,curNrg:0,curShield:b.shield||0,burn:0};
      bs.eCards.push(m);
    }

    // Add similar number of skills to random units
    const eSkillCount=Math.max(0,Math.floor(playerUnits*0.7)+Math.floor(Math.random()*2));
    const eAlive=bs.eCards.filter(c=>c.currentHp>0);
    for(let i=0;i<eSkillCount&&eAlive.length;i++){
      const r=pickRar(diff*.3);let pool=SKILLS_DB.filter(s=>s.rarity===r);if(!pool.length)pool=SKILLS_DB;
      const sk=pool[Math.floor(Math.random()*pool.length)];
      const t=eAlive[Math.floor(Math.random()*eAlive.length)];
      applySkillToUnit(sk,t);t.equips=t.equips||[];t.equips.push({icon:sk.icon,name:sk.name,id:sk.id});
    }

    // Apply similar number of relics
    const eRelicCount=Math.max(0,playerRelics+Math.floor(Math.random()*2)-1);
    for(let i=0;i<eRelicCount;i++){
      const r=pickRar(diff*.3);let pool=RELICS_DB.filter(x=>x.rarity===r);if(!pool.length)pool=RELICS_DB;
      const rl=pool[Math.floor(Math.random()*pool.length)];
      applyRelicBattle(rl,bs.eCards);
    }
  },

  // AI performs multiple actions based on AP with situational awareness
  enemyRoundActions(bs){
    const ap=this.getActionPoints();
    const msgs=[];
    for(let a=0;a<ap;a++){
      const msg=this._enemySingleAction(bs);
      if(msg)msgs.push(msg);
    }
    return msgs;
  },
  _enemySingleAction(bs){
    const eAlive=bs.eCards.filter(c=>c.currentHp>0);
    const eHero=bs.eCards.find(c=>c.isHero&&c.currentHp>0);
    const diff=this.totalWins+this.getHeroLevel();
    const scale=1+diff*.08;
    const rd=bs.currentRound;

    // Situational AI: assess what's needed
    const unitCount=eAlive.filter(c=>!c.isHero).length;
    const heroHpPct=eHero?(eHero.currentHp/eHero.maxBHp):1;
    const hasSkillTargets=eAlive.some(c=>!c.isHero&&(c.equips||[]).length<2);

    // Priority 1: Potion if hero low HP
    if(eHero&&heroHpPct<0.3&&!(bs._ePotionCd>0)){
      const heal=Math.floor(eHero.maxBHp*.5);
      eHero.currentHp=Math.min(eHero.currentHp+heal,eHero.maxBHp);
      bs._ePotionCd=2;
      return `적 영웅이 포션 사용! HP+${heal}`;
    }

    // Priority 2: Add units if outnumbered or too few
    let choice;
    if(unitCount<=1) choice='add_card';
    else if(unitCount<=3&&Math.random()<0.5) choice='add_card';
    else if(hasSkillTargets&&Math.random()<0.4) choice='pick_skill';
    else if(Math.random()<0.4) choice='pick_relic';
    else choice='add_card';

    if(choice==='add_card'){
      const candidates=[];
      for(let i=0;i<3;i++){
        const r=pickRar(rd*.5,'battle');let pool=UNITS.filter(u=>u.rarity===r&&!u.id.startsWith('h_'));if(!pool.length)pool=UNITS.filter(u=>!u.id.startsWith('h_'));
        const b=pool[Math.floor(Math.random()*pool.length)];
        candidates.push({...b,uid:'e_'+uid(),level:1,equips:[],
          atk:Math.round(b.atk*scale),hp:Math.round(b.hp*scale),maxHp:Math.round(b.hp*scale),def:Math.round(b.def*scale)});
      }
      const rarVal={divine:5,legendary:4,gold:3,silver:2,bronze:1};
      candidates.sort((a,b)=>(rarVal[b.rarity]||0)-(rarVal[a.rarity]||0)||(b.atk-a.atk));
      const pick=candidates[0];
      const dup=eAlive.find(x=>x.id===pick.id);
      if(dup){fuseCard(dup);dup.currentHp=dup.maxBHp=dup.hp;return `${dup.icon}${dup.name} 합성→${R_LABEL[dup.rarity]}`;}
      pick.currentHp=pick.hp;pick.maxBHp=pick.maxHp;pick.side='enemy';
      pick.row=(pick.type==='전사'||pick.type==='야수')?'front':'back';
      pick.frozen=0;pick.poisoned=0;pick.revived=false;pick.invincible=0;
      bs.eCards.push(pick);
      return `${pick.icon}${pick.name}(${R_LABEL[pick.rarity]}) 고용`;
    } else if(choice==='pick_skill'){
      const updated=bs.eCards.filter(c=>c.currentHp>0);
      if(updated.length){
        const r=pickRar(rd*.4);let pool=SKILLS_DB.filter(s=>s.rarity===r);if(!pool.length)pool=SKILLS_DB;
        const sk=pool[Math.floor(Math.random()*pool.length)];
        // Prefer units with fewer equips
        const sorted=[...updated].sort((a,b)=>((a.equips||[]).length)-((b.equips||[]).length));
        const t=sorted[0];
        applySkillToUnit(sk,t);t.equips=t.equips||[];t.equips.push({icon:sk.icon,name:sk.name,id:sk.id});
        return `${t.icon}${t.name}에 ${sk.icon}${sk.name}`;
      }
      return '';
    } else {
      const updated=bs.eCards.filter(c=>c.currentHp>0);
      const r=pickRar(rd*.4);let pool=RELICS_DB.filter(x=>x.rarity===r);if(!pool.length)pool=RELICS_DB;
      const rl=pool[Math.floor(Math.random()*pool.length)];
      applyRelicBattle(rl,updated);
      return `${rl.icon}${rl.name} 유물 장착`;
    }
  },

  // ── 부활 공통 헬퍼 (2026-04-19 P1-A) ──
  // grant_rebirth 패시브로 _rebirthHp/_rebirthNrg 가 스탬프된 유닛을 사망 시 부활.
  // 기존 하드코딩(HP 50% 복구) 은 폴백으로 유지.
  _reviveIfCan(u){
    if(u.skill!=='rebirth' || u.revived) return false;
    u.currentHp = u._rebirthHp || Math.floor((u.maxBHp||u.hp||1)*.5);
    if(u._rebirthNrg != null) u.curNrg = Math.max(u.curNrg||0, u._rebirthNrg);
    u.revived = true;
    if(this.log) this.log(`${u.icon} 부활!`,'ability-log');
    return true;
  },
});
