// Game Battle (전투 흐름 + 스킬 시스템)
// Generated by docs/_split_game.py — Phase 4
// DO NOT hand-edit keys — edit in original and re-run splitter if needed.

RoF.__gameKeys = RoF.__gameKeys || new Set();
(function(keys){
  for (const k of keys) {
    if (RoF.__gameKeys.has(k)) {
      console.error('[Game] 중복 키 감지:', k);
      RoF.__gameKeyError = true;
    }
    RoF.__gameKeys.add(k);
  }
})(["battleState", "selectedForBattle", "selectedRelics", "getCommandSlots", "getUsedSlots", "generateBot", "showMatchmaking", "startBattleFromMatch", "startBattle", "_startBattleInner", "renderCardSelect", "saveFormation", "loadFormation", "_applyFormation", "confirmCardSelect", "launchBattle", "genEnemy", "runBattleRound", "enemyMirrorDeploy", "enemyRoundActions", "_enemySingleAction", "_roundTimer", "_roundTimerLeft", "showRoundChoice", "_startRoundTimer", "_stopRoundTimer", "_revealAndFinish", "doRoundChoice", "showBattleEnd", "equipSkillPermanent", "equipSkillBattle", "_lastTarget", "showAction", "log", "cycleSpeed", "_skillQueue", "_targetMode", "_targetCallback", "_playerTarget", "updateSkillBar", "_manualSkill", "_enterTargetMode", "_executeSkill", "setPlayerTarget", "skipBattle", "triggerSlowMo", "renderBF", "_lootPicked", "afterBattle", "rerollPick", "finishPick", "finishRound", "askFormationForNextRound", "newRun"]);

Object.assign(RoF.Game, {
  battleState:null, // {pCards, eCards, currentRound, battleDeck, battleRelics}
  selectedForBattle:[], // uids of unit cards selected
  selectedRelics:[], // uids of relics selected

  getCommandSlots(){
    const hero=this.deck.find(c=>c.isHero);
    return hero?(hero.level||1):1; // 출전권 = 영웅카드 레벨
  },

  getUsedSlots(){
    const hero=this.deck.find(c=>c.isHero);
    return this.selectedForBattle
      .filter(u=>u!==(hero?hero.uid:''))
      .reduce((sum,uid)=>{const c=this.deck.find(x=>x.uid===uid);return sum+(c?(c.level||1):1);},0);
  },

  // ── BOT MATCHMAKING ──
  generateBot(){
    const lg=this.getLeague();const lgIdx=this.LEAGUES.indexOf(lg);
    // Pick league ±1
    const botLgIdx=Math.max(0,Math.min(this.LEAGUES.length-1,lgIdx+Math.floor(Math.random()*3)-1));
    const botLg=this.LEAGUES[botLgIdx];
    const botName=enemyName();
    // Pick random hero element + role
    const el=ELEMENTS[Math.floor(Math.random()*ELEMENTS.length)];
    const roles=['melee','ranged','support'];
    const role=roles[Math.floor(Math.random()*roles.length)];
    const heroId=getHeroId(el,role);
    const heroBase=UNITS.find(u=>u.id===heroId)||UNITS[0];
    const roleName=HERO_ROLES.find(r=>r.id===role)?.name||'전사';
    return{name:botName,league:botLg,element:el,role:roleName,heroBase,
      heroIcon:heroBase.icon,level:Math.max(1,this.getHeroLevel()+Math.floor(Math.random()*3)-1)};
  },

  showMatchmaking(){
    UI.show('match-screen');SFX.bgm('match');
    const hero=this.deck.find(c=>c.isHero);
    const lg=this.getLeague();
    const box=document.getElementById('match-box');
    const heroImg=hero?getCardImg(hero):'';
    const heroClass=hero?(hero.heroClass||hero.type):'';
    const heroElem=hero?hero.element:'';
    // Phase 1: Searching
    box.innerHTML=`
      <div class="match-search" style="font-size:1.2rem;">⚔️ 도전자를 찾는 중<span class="dots">...</span></div>
      <div style="display:flex;align-items:center;justify-content:center;gap:30px;width:100%;margin-top:20px;">
        <!-- 상대 (왼쪽, 미확인) -->
        <div style="text-align:center;flex:1;">
          <div style="width:35vw;max-width:250px;aspect-ratio:1;border-radius:15px;border:3px dashed #444;background:rgba(0,0,0,.4);display:flex;align-items:center;justify-content:center;margin:0 auto;">
            <div style="font-size:4rem;opacity:.3;animation:dotPulse 1s infinite;">❓</div>
          </div>
          <div style="color:#555;font-size:1.1rem;font-weight:bold;margin-top:8px;">검색중...</div>
        </div>
        <!-- VS -->
        <div class="match-vs" style="opacity:.3;font-size:2rem;">⚔<br>VS<br>⚔</div>
        <!-- 나 (오른쪽) -->
        <div style="text-align:center;flex:1;">
          ${heroImg?`<img src="${heroImg}" style="width:35vw;max-width:250px;aspect-ratio:1;border-radius:15px;border:4px solid ${ELEM_COLOR[heroElem]||'#8b6914'};object-fit:cover;box-shadow:0 0 25px ${ELEM_COLOR[heroElem]||'rgba(0,0,0,.5)'};">`:`<div style="font-size:5rem;">${hero?hero.icon:'⚔️'}</div>`}
          <div style="color:#fff;font-size:1.3rem;font-weight:bold;margin-top:8px;font-family:'Cinzel','Georgia',serif;">${Auth.user}</div>
          <div style="color:${lg.color};font-size:.9rem;">${lg.icon} ${lg.name} Lv.${this.getHeroLevel()}</div>
        </div>
      </div>`;
    // Phase 2: Found (after 2-3 sec)
    const delay=1500+Math.random()*1500;
    setTimeout(()=>{
      const bot=this.generateBot();
      this._currentBot=bot;
      SFX.play('magic');
      const botImg=getCardImg(bot.heroBase);
      box.innerHTML=`
        <div style="color:#44ff88;font-size:1.2rem;margin-bottom:15px;" class="match-found">도전자가 나타났다!</div>
        <div style="display:flex;align-items:center;justify-content:center;gap:30px;width:100%;" class="match-found">
          <!-- 상대 (왼쪽) -->
          <div style="text-align:center;flex:1;">
            ${botImg?`<img src="${botImg}" style="width:35vw;max-width:250px;aspect-ratio:1;border-radius:15px;border:4px solid ${ELEM_COLOR[bot.element]||'#888'};object-fit:cover;box-shadow:0 0 25px ${ELEM_COLOR[bot.element]||'rgba(0,0,0,.5)'};">`:`<div style="font-size:5rem;">${ELEM_ICON[bot.element]}</div>`}
            <div style="color:#fff;font-size:1.3rem;font-weight:bold;margin-top:8px;font-family:'Cinzel','Georgia',serif;">${bot.name}</div>
            <div style="color:${bot.league.color};font-size:.9rem;">${bot.league.icon} ${bot.league.name} Lv.${bot.level}</div>
            <div style="color:#aaa;font-size:.8rem;">${bot.roleName||bot.role} · ${ELEM_ICON[bot.element]} ${ELEM_L[bot.element]}</div>
          </div>
          <!-- VS -->
          <div class="match-vs" style="font-size:2rem;">⚔<br>VS<br>⚔</div>
          <!-- 나 (오른쪽) -->
          <div style="text-align:center;flex:1;">
            ${heroImg?`<img src="${heroImg}" style="width:35vw;max-width:250px;aspect-ratio:1;border-radius:15px;border:4px solid ${ELEM_COLOR[heroElem]||'#8b6914'};object-fit:cover;box-shadow:0 0 25px ${ELEM_COLOR[heroElem]||'rgba(0,0,0,.5)'};">`:`<div style="font-size:5rem;">${hero?hero.icon:'⚔️'}</div>`}
            <div style="color:#fff;font-size:1.3rem;font-weight:bold;margin-top:8px;font-family:'Cinzel','Georgia',serif;">${Auth.user}</div>
            <div style="color:${lg.color};font-size:.9rem;">${lg.icon} ${lg.name} Lv.${this.getHeroLevel()}</div>
            <div style="color:#aaa;font-size:.8rem;">${heroClass} · ${heroElem?ELEM_ICON[heroElem]+' '+ELEM_L[heroElem]:''}</div>
          </div>
        </div>
        <div style="display:flex;gap:15px;justify-content:center;margin-top:20px;">
          <button class="btn" onclick="Game.startBattleFromMatch()" style="font-size:1.2rem;padding:14px 40px;">⚔️ 출전!</button>
          <button class="btn btn-s btn-red" onclick="Game.showMenu()">철수</button>
        </div>`;
    },delay);
  },

  startBattleFromMatch(){
    // 매칭 확인 후 → 바로 전투 (배치 없음)
    const battleDeck=this.deck.filter(c=>this.selectedForBattle.includes(c.uid));
    const battleRelics=(this.ownedRelics||[]).filter(r=>this.selectedRelics.includes(r.uid));
    this._deckSnapshot=this.deck.map(c=>({...c,equips:[...(c.equips||[])]}));
    this.battleState={currentRound:0,pCards:null,eCards:null,battleDeck:battleDeck.map(c=>({...c,equips:[...(c.equips||[])]})),battleRelics:battleRelics};
    this.launchBattle();
  },

  startBattle(){
    // 성문 클릭 → 편성부터
    if(this.getBuildingLv('gate')<1){UI.modal('🚪 성문 필요','성문을 건설해야 리그에 참여할 수 있습니다!',null);return;}
    this.checkTutorial('first_battle');
    this.selectedForBattle=[];this.selectedRelics=[];
    this._startBattleInner();
  },

  _startBattleInner(){
    const nonHero=this.deck.filter(c=>!c.isHero);
    const hasRelics=(this.ownedRelics||[]).length>0;
    if(nonHero.length===0&&!hasRelics){
      const hero=this.deck.find(c=>c.isHero);
      if(hero)this.selectedForBattle=[hero.uid];
      this.confirmCardSelect();
      return;
    }
    UI.show('cardselect-screen');
    document.getElementById('cs-name').textContent=`👤 ${Auth.user}`;
    document.getElementById('cs-slots').textContent=this.getCommandSlots();
    this.renderCardSelect();
  },

  renderCardSelect(){
    const grid=document.getElementById('cs-grid');
    const selDiv=document.getElementById('cs-selected');
    const maxSlots=this.getCommandSlots();
    grid.innerHTML='';selDiv.innerHTML='';

    const hero=this.deck.find(c=>c.isHero);
    if(hero&&!this.selectedForBattle.includes(hero.uid)){
      this.selectedForBattle=[hero.uid,...this.selectedForBattle.filter(u=>u!==hero.uid)];
    }

    const usedSlots=this.getUsedSlots();

    // Show ALL cards in grid (hero included, marked as auto)
    this.deck.forEach(c=>{
      const isInjured=!!c.injured;
      const isSel=this.selectedForBattle.includes(c.uid);
      const cardCost=c.isHero?0:(c.level||1);
      const selUnitCount=this.selectedForBattle.filter(uid=>uid!==(hero?hero.uid:'')).length;
      const canAdd=!isSel&&!c.isHero&&!isInjured&&(usedSlots+cardCost<=maxSlots)&&selUnitCount<4;
      const el=mkCardEl(c);
      if(c.isHero){
        el.style.opacity='1';
        el.style.boxShadow='0 0 15px rgba(255,215,0,.6)';
      } else if(isInjured){
        el.style.opacity='.3';el.style.filter='grayscale(.8)';
      } else {
        el.style.opacity=isSel?'1':canAdd?'.6':'.25';
        if(isSel)el.style.boxShadow='0 0 12px rgba(68,255,136,.5)';
      }
      const badge=document.createElement('div');
      badge.style.cssText='text-align:center;font-size:.7rem;margin-top:2px;';
      if(c.isHero){badge.style.color='#ffd700';badge.textContent='⭐ 자동 출전';}
      else if(isInjured){badge.style.color='#ff4444';badge.textContent='🩹 부상 — 교회에서 치유 필요';}
      else{badge.style.color=isSel?'#44ff88':'#ffaa44';badge.textContent=isSel?'✅ 출전 중':`지휘권 ${cardCost} 소비`;}
      el.appendChild(badge);
      if(!c.isHero&&!isInjured){
        el.onclick=()=>{
          if(isSel){this.selectedForBattle=this.selectedForBattle.filter(u=>u!==c.uid);}
          else{
            if(selUnitCount>=4){document.getElementById('cs-info').textContent=`⚠️ 최대 4명까지 출전 가능!`;return;}
            if(usedSlots+cardCost>maxSlots){document.getElementById('cs-info').textContent=`⚠️ 지휘권 부족! (필요:${cardCost}, 남은:${maxSlots-usedSlots})`;return;}
            this.selectedForBattle.push(c.uid);
          }
          SFX.play('click');this.renderCardSelect();
        };
      }
      grid.appendChild(el);
    });

    // Show selected in top area
    const allSel=this.deck.filter(c=>this.selectedForBattle.includes(c.uid));
    allSel.forEach(c=>{
      const mini=mkMini(c);
      mini.style.width='60px';mini.style.height='80px';
      mini.querySelector('.dm-icon').style.fontSize='1.5rem';
      selDiv.appendChild(mini);
    });

    // Relic selection
    const maxRSlots=this.getRelicSlots();
    const rGrid=document.getElementById('cs-relics-grid');rGrid.innerHTML='';
    const rSelDiv=document.getElementById('cs-relics-selected');rSelDiv.innerHTML='';
    const owned=this.ownedRelics||[];
    const usedR=this.selectedRelics.length;

    owned.forEach(r=>{
      const isSel=this.selectedRelics.includes(r.uid);
      const el=mkRelicEl(r);
      el.style.opacity=isSel?'1':usedR<maxRSlots?'.6':'.25';
      if(isSel)el.style.boxShadow='0 0 12px rgba(170,102,255,.5)';
      el.onclick=()=>{
        if(isSel){this.selectedRelics=this.selectedRelics.filter(u=>u!==r.uid);}
        else{
          if(usedR>=maxRSlots){document.getElementById('cs-info').textContent=`⚠️ 유물 보유량 초과! (최대 ${maxRSlots})`;return;}
          this.selectedRelics.push(r.uid);
        }
        SFX.play('click');this.renderCardSelect();
      };
      rGrid.appendChild(el);
    });
    if(!owned.length)rGrid.innerHTML='<div style="color:#555;font-size:.75rem;">소지한 유물 없음</div>';

    // Show selected relics
    const selR=owned.filter(r=>this.selectedRelics.includes(r.uid));
    selR.forEach(r=>{
      const d=document.createElement('div');d.style.cssText='text-align:center;font-size:.7rem;';
      d.innerHTML=`<span style="font-size:1.3rem;">${r.icon}</span><br><span style="color:#ccc;">${r.name}</span>`;
      rSelDiv.appendChild(d);
    });
    if(!selR.length)rSelDiv.innerHTML='<div style="color:#555;font-size:.75rem;">유물 미선택</div>';

    const newUsed=this.getUsedSlots();
    const finalUnitCount=this.selectedForBattle.filter(uid=>uid!==(hero?hero.uid:'')).length;
    document.getElementById('cs-info').textContent=`동료 ${finalUnitCount}/4 | 지휘권 ${newUsed}/${maxSlots} | 유물 ${usedR}/${maxRSlots}`;
    document.getElementById('cs-rslots').textContent=maxRSlots;
    document.getElementById('cs-go-btn').disabled=false;
  },

  saveFormation(){
    const f={units:[...this.selectedForBattle],relics:[...this.selectedRelics]};
    this.savedFormations=this.savedFormations||[];
    if(this.savedFormations.length>=3)this.savedFormations.shift(); // max 3
    this.savedFormations.push(f);
    this.persist();SFX.play('upgrade');
    document.getElementById('cs-info').textContent=`📜 편성이 기억되었습니다! (${this.savedFormations.length}/3)`;
  },
  loadFormation(){
    if(!this.savedFormations||!this.savedFormations.length){
      document.getElementById('cs-info').textContent='⚠️ 저장된 편성이 없습니다. 먼저 "편성 기억"을 눌러주세요.';return;
    }
    // Show selection if multiple
    if(this.savedFormations.length===1){
      this._applyFormation(this.savedFormations[0]);return;
    }
    const items=this.savedFormations.map((f,i)=>`편성 ${i+1}: 동료 ${f.units.length}명, 유물 ${f.relics.length}개`).join('\n');
    // Use last saved
    this._applyFormation(this.savedFormations[this.savedFormations.length-1]);
  },
  _applyFormation(f){
    // Only apply units that still exist in deck
    const validUnits=f.units.filter(uid=>this.deck.some(c=>c.uid===uid&&!c.injured));
    const validRelics=f.relics.filter(uid=>(this.ownedRelics||[]).some(r=>r.uid===uid));
    this.selectedForBattle=validUnits;this.selectedRelics=validRelics;
    SFX.play('card_reveal');
    this.renderCardSelect();
    document.getElementById('cs-info').textContent=`📜 편성이 소환되었습니다! (동료 ${validUnits.length}명)`;
  },

  confirmCardSelect(){
    const battleDeck=this.deck.filter(c=>this.selectedForBattle.includes(c.uid));
    if(!battleDeck.find(c=>c.isHero)){
      document.getElementById('cs-info').textContent='⚠️ 영웅이 필요합니다!';return;
    }
    // 편성 완료 → 매칭 화면으로
    this.showMatchmaking();
  },

  launchBattle(){
    const bs=this.battleState;
    if(!bs.pCards){
      bs.pCards=bs.battleDeck.map(c=>({...c,currentHp:c.hp,maxBHp:c.maxHp||c.hp,side:'player',row:c.formRow||'front',frozen:0,poisoned:0,revived:false,invincible:0,curNrg:0,curShield:c.shield||0,burn:0}));
      bs.battleRelics.forEach(r=>applyRelicBattle(r,bs.pCards));
      const rawE=this.genEnemy();
      rawE.forEach(c=>{c.row=(c.type==='전사'||c.type==='야수')?'front':'back';});
      bs.eCards=rawE.map(c=>({...c,currentHp:c.hp,maxBHp:c.maxHp||c.hp,side:'enemy',frozen:0,poisoned:0,revived:false,invincible:0,curNrg:0,curShield:c.shield||0,burn:0}));
      this.enemyMirrorDeploy(bs);
    }
    if(!bs.currentRound)bs.currentRound=1;// 첫 진입시만
    this.persist();
    TurnBattle.start(bs);
  },

  genEnemy(){
    // Match enemy to player's hero level & deployed card rarities
    const myHero=this.deck.find(c=>c.isHero);
    const myLv=myHero?(myHero.level||1):1;
    const myRar=myHero?(myHero.rarity||'bronze'):'bronze';
    // Enemy hero: same rarity tier as player hero (±1 random)
    const ri=R_ORDER.indexOf(myRar);
    const eRarIdx=Math.max(0,Math.min(R_ORDER.length-2,ri+Math.floor(Math.random()*3)-1));
    const heroRar=R_ORDER[eRarIdx];
    const heroPool=UNITS.filter(u=>u.rarity===heroRar);
    const hBase=(heroPool.length?heroPool:UNITS)[Math.floor(Math.random()*(heroPool.length||UNITS.length))];
    // Enemy hero level = player hero level (±1)
    const eLv=Math.max(1,myLv+Math.floor(Math.random()*3)-1);
    const scale=1+(eLv-1)*.1;
    const eHero={...hBase,uid:'eh_'+uid(),name:enemyName(),isHero:true,rarity:heroRar,level:eLv,equips:[],
      atk:Math.round(hBase.atk*scale),hp:Math.round(hBase.hp*scale),maxHp:Math.round(hBase.hp*scale),def:Math.round(hBase.def*scale)};
    return [eHero];
  },

  // Add a random minion to enemy (called between rounds)

  async runBattleRound(){
   try{
    const bs=this.battleState;
    const pCards=bs.pCards,eCards=bs.eCards;
    const rd=bs.currentRound; // Round N = N attacks each

    this.battleRunning=true;this.skipReq=false;this.battleSpeed=Math.floor(500/this.battleMultiplier);
    document.getElementById('b-round').textContent=rd;
    document.getElementById('b-hp').textContent=this.hp;
    document.getElementById('battle-log').innerHTML='';
    document.getElementById('b-status').textContent='전투 중...';

    // Reset frozen/poison each round
    [...pCards,...eCards].forEach(c=>{c.frozen=0;c.poisoned=0;});

    this.renderBF(pCards,eCards);
    this.log(`═══ 라운드 ${rd} (${rd}번 공격) ═══`,'');

    for(let atNum=0;atNum<rd&&this.battleRunning;atNum++){
      this.log(`── 공격 ${atNum+1}/${rd} ──`,'');
      document.getElementById('b-banner').textContent=`⚔️ 라운드${rd} — 공격 ${atNum+1}/${rd}`;

      const all=[...pCards,...eCards].filter(c=>c.currentHp>0).sort((a,b)=>{
        const af=a.skill==='first_strike'?100:0,bf=b.skill==='first_strike'?100:0;
        return(b.spd+bf)-(a.spd+af);});

      for(const u of all){
        if(u.currentHp<=0||!this.battleRunning)continue;
        if(u.frozen>0){u.frozen--;this.log(`${u.icon} 빙결!`,'ability-log');continue;}
        const foes=(u.side==='player'?eCards:pCards).filter(c=>c.currentHp>0);
        const allies=(u.side==='player'?pCards:eCards).filter(c=>c.currentHp>0);
        if(!foes.length)break;

        // === REGEN (턴 시작) ===
        if(u.hpReg>0){u.currentHp=Math.min(u.currentHp+(u.hpReg||0),u.maxBHp);}
        u.curNrg=(u.curNrg||0)+(u.nrgReg||0);
        // Status ticks
        if(u.burn>0){const bd=u.burnDmg||2;u.currentHp-=bd;u.burn--;this.showDmg(u,bd,false);this.log(`${u.icon} 화상-${bd}`,'ability-log');if(u.currentHp<=0){u.currentHp=0;continue;}}
        if(u.noHeal>0)u.noHeal--;

        // === CHECK ACTION TYPE ===
        const uAction=u.action||'attack'; // 'attack','none','counter','skill_only'

        // === PASSIVE SKILLS (공격 전) ===
        const sk=u.skill,skT=u.skillType||'passive',skCh=u.skillChance||1,skNrg=u.skillNrg||0;
        let packBonus=0;
        // Passive skills that modify attack or state
        if(sk==='pack')packBonus=allies.filter(c=>c.type==='야수').length*2;
        if(sk==='frenzy'&&u.currentHp<=u.maxBHp*.5){this.log(`${u.icon} 광기!`,'ability-log');}

        // === TARGET ===
        const taunts=foes.filter(c=>c.skill==='taunt');
        const frontFoes=foes.filter(c=>c.row==='front');
        let targetPool=taunts.length?taunts:frontFoes.length?frontFoes:foes;
        let target=targetPool[Math.floor(Math.random()*targetPool.length)];
        // Player target override (if set and valid, not taunted)
        if(u.side==='player'&&this._playerTarget&&!taunts.length){
          const pt=foes.find(c=>c.uid===this._playerTarget&&c.currentHp>0);
          if(pt)target=pt;
        }

        // === DAMAGE CALC ===
        let atk=u.atk+packBonus;let isCrit=false;
        const critCh=Math.min(.05+(u.luck||0)*.015,.6);
        if(sk==='crit'&&Math.random()<skCh){atk*=3;isCrit=true;this.log(`${u.icon} 급소!`,'ability-log');}
        else if(Math.random()<critCh){atk*=2;isCrit=true;}
        if(sk==='frenzy'&&u.currentHp<=u.maxBHp*.5)atk*=2;
        if((u.rage||0)>0&&u.currentHp<u.maxBHp*.7)atk+=Math.floor((u.rage||0)*.3);

        let strikes=1;
        // Active skill: double_cast / multi_head (check energy)
        if(sk==='double_cast'&&skT==='active'&&u.curNrg>=skNrg&&Math.random()<skCh){strikes=2;u.curNrg-=skNrg;this.log(`${u.icon} 더블캐스트!`,'ability-log');}
        if(sk==='multi_head'&&skT==='active'&&u.curNrg>=skNrg&&Math.random()<skCh){strikes=Math.min(3,foes.length);u.curNrg-=skNrg;this.log(`${u.icon} 다두공격!`,'ability-log');}

        // === ATTACK PHASE (non-attackers skip) ===
        if(uAction!=='none'&&uAction!=='skill_only'){
          await this.showAction(u,isCrit?'치명타!':'공격!',target);
          for(let s=0;s<strikes;s++){
            let ct=sk==='multi_head'?foes[s%foes.length]:target;
            if(!ct||ct.currentHp<=0){const al=foes.filter(c=>c.currentHp>0);if(!al.length)break;ct=al[0];}
            let dmg=atk;
            const isMagic=u.type==='마법사';
            if(sk!=='pierce'){const dr=ct.def||0;dmg=ct.skill==='armor'?Math.max(1,dmg-dr-3):Math.max(1,dmg-Math.floor(dr*.5));}
            const evaC=Math.min(.05+(ct.eva||0)*.02,.6);
            if(!isMagic&&Math.random()<(ct.skill==='dodge'?Math.min(evaC+.3,.7):evaC)){this.log(`${ct.icon} 회피!`,'ability-log');continue;}
            if(isMagic){const mevaC=Math.min(.05+(ct.meva||0)*.025,.5);if(Math.random()<mevaC){this.log(`${ct.icon} 마법회피!`,'ability-log');continue;}}
            if(ct.invincible>0){ct.invincible--;this.log(`${ct.icon} 무적!`,'ability-log');continue;}
            if(ct.divineShield){ct.divineShield=false;this.log(`${ct.icon} 신성방패!`,'ability-log');continue;}
            if((ct.curShield||0)>0){const ab=Math.min(ct.curShield,dmg);ct.curShield-=ab;dmg-=ab;if(ab>0)this.log(`${ct.icon} 보호막-${ab}`,'ability-log');}
            dmg=Math.max(0,dmg);
            ct.currentHp-=dmg;
            this.showAtkEffect(u,ct);SFX.play(isMagic?'magic':'slash');SFX.play('hit');
            this.showDmg(ct,dmg,isCrit);
            this.log(`${u.icon}${u.name}→${ct.icon}${ct.name} ${dmg}${isCrit?' 치명타!':''}`,'atk-log');
            // On-attack triggers
            const bt=u.bonusTrigger;
            if(bt&&bt.on==='attack'&&Math.random()<bt.chance){
              if(bt.effect==='double_arrow'){ct.currentHp-=Math.floor(dmg*.5);this.log(`${u.icon} 쌍발!`,'ability-log');}
              if(bt.effect==='cleave'){const adj=foes.filter(c=>c.currentHp>0&&c.uid!==ct.uid);if(adj.length){adj[0].currentHp-=Math.floor(dmg*.5);this.log(`${u.icon} 광역!`,'ability-log');}}
              if(bt.effect==='backstab'){ct.currentHp-=Math.floor(dmg*.5);this.log(`${u.icon} 기습!`,'ability-log');}
              if(bt.effect==='headshot'){ct.currentHp-=Math.floor(ct.maxBHp*.1);this.log(`${u.icon} 헤드샷!`,'ability-log');}
              if(bt.effect==='frostbite'){ct.spd=Math.max(1,(ct.spd||5)-3);}
              if(bt.effect==='regen_head'){u.currentHp=Math.min(u.currentHp+8,u.maxBHp);this.showHeal(u,8);}
            }
            // On-hit triggers (defender)
            const dbt=ct.bonusTrigger;
            if(dbt&&dbt.on==='hit'&&Math.random()<dbt.chance&&ct.currentHp>0&&!u._noCounter){
              if(dbt.effect==='counter'&&(u.range||'melee')==='melee'&&ct.row==='front'){u._noCounter=true;const cd=Math.floor(ct.atk*.5);u.currentHp-=cd;this.showDmg(u,cd,false);this.log(`${ct.icon} 반격! ${cd}`,'ability-log');u._noCounter=false;}
              else if(dbt.effect==='thorns'){u.currentHp-=4;this.showDmg(u,4,false);this.log(`${ct.icon} 가시!`,'ability-log');}
              else if(dbt.effect==='flame_aura'){u.currentHp-=5;this.showDmg(u,5,false);this.log(`${ct.icon} 화염오라!`,'ability-log');}
              else if(dbt.effect==='mirror_break'){u.def=Math.max(0,(u.def||0)-2);}
              else if(dbt.effect==='energy_burst'){(ct.side==='player'?pCards:eCards).filter(a=>a.currentHp>0).forEach(a=>{a.curNrg=(a.curNrg||0)+2;});}
            }
            // Passive drain/steal
            if(sk==='drain'&&Math.random()<skCh){const h=Math.floor(dmg*.5);u.currentHp=Math.min(u.currentHp+h,u.maxBHp);this.showHeal(u,h);}
            if(sk==='life_steal'&&Math.random()<skCh){u.currentHp=Math.min(u.currentHp+dmg,u.maxBHp);this.showHeal(u,dmg);}
            if(sk==='freeze'&&skT==='active'&&u.curNrg>=skNrg&&Math.random()<skCh){ct.frozen=1;u.curNrg-=skNrg;this.log(`${ct.icon} 빙결!`,'ability-log');}
            // Death + kill triggers
            if(ct.currentHp<=0){
              if(ct.skill==='rebirth'&&!ct.revived){ct.currentHp=Math.floor(ct.maxBHp*.5);ct.revived=true;this.log(`${ct.icon} 부활!`,'ability-log');this.triggerSlowMo(1200,'revive');}
              else{
                ct.currentHp=0;SFX.play('death');this.log(`${ct.icon} 쓰러짐!`,'atk-log');this.triggerSlowMo(800,'kill');
                const kbt=u.bonusTrigger;
                if(kbt&&kbt.on==='kill'&&Math.random()<kbt.chance){
                  if(kbt.effect==='howl'){allies.filter(c=>c.type==='야수'&&c.currentHp>0).forEach(a=>{a.atk+=1;});}
                  if(kbt.effect==='stealth'){u._stealthNext=true;}
                  if(kbt.effect==='soul_harvest'){u.atk+=3;}
                  if(kbt.effect==='raise_dead'){(u.side==='player'?pCards:eCards).push({...ct,uid:'z_'+uid(),name:'좀비'+ct.name,side:u.side,isHero:false,currentHp:Math.floor(ct.maxBHp*.3),maxBHp:Math.floor(ct.maxBHp*.3),atk:Math.floor(ct.atk*.5),skill:'none',equips:[],bonusTrigger:null});}
                }
              }
            }
            // Attacker died from counter/thorns
            if(u.currentHp<=0){u.currentHp=0;break;}
          }
        }

        // === ACTIVE SKILLS (공격 후 발동) — all units ===
        // Skip if player manually activated this turn
        if(u._manualUsed){u._manualUsed=false;}
        else{
        if(sk==='aoe'&&skT==='active'&&u.curNrg>=skNrg&&Math.random()<skCh){
          u.curNrg-=skNrg;const d=3;foes.filter(c=>c.currentHp>0).forEach(e=>{e.currentHp-=d;this.showDmg(e,d,false);if(e.currentHp<=0){if(e.skill==='rebirth'&&!e.revived){e.currentHp=Math.floor(e.maxBHp*.5);e.revived=true;}else e.currentHp=0;}});
          this.log(`${u.icon} 화염! 전체${d} (에너지-${skNrg})`,'ability-log');
        }
        if(sk==='breath'&&skT==='active'&&u.curNrg>=skNrg&&Math.random()<skCh){
          u.curNrg-=skNrg;const d=5;foes.filter(c=>c.currentHp>0).forEach(e=>{e.currentHp-=d;this.showDmg(e,d,false);if(e.currentHp<=0){if(e.skill==='rebirth'&&!e.revived){e.currentHp=Math.floor(e.maxBHp*.5);e.revived=true;}else e.currentHp=0;}});
          this.log(`${u.icon} 브레스! 전체${d} (에너지-${skNrg})`,'ability-log');
        }
        if(sk==='heal_self'&&skT==='active'&&u.curNrg>=skNrg&&Math.random()<skCh&&!(u.noHeal>0)){
          u.curNrg-=skNrg;const h=4;u.currentHp=Math.min(u.currentHp+h,u.maxBHp);this.showHeal(u,h);SFX.play('heal');
          this.log(`${u.icon} 자가치유+${h} (에너지-${skNrg})`,'heal-log');
        }
        if(sk==='heal_ally'&&skT==='active'&&u.curNrg>=skNrg&&Math.random()<skCh){
          const w=allies.filter(c=>c.currentHp<c.maxBHp&&c.uid!==u.uid&&!(c.noHeal>0));
          if(w.length){u.curNrg-=skNrg;const t=w.reduce((a,b)=>a.currentHp<b.currentHp?a:b);const h=5;t.currentHp=Math.min(t.currentHp+h,t.maxBHp);this.showHeal(t,h);SFX.play('heal');this.log(`${u.icon}→${t.icon} 치유+${h} (에너지-${skNrg})`,'heal-log');}
        }
        if(sk==='inspire'&&skT==='active'&&u.curNrg>=skNrg&&Math.random()<skCh){
          u.curNrg-=skNrg;allies.forEach(a=>{if(a.uid!==u.uid)a.atk+=2;});this.log(`${u.icon} 고무! 아군 공격+2 (에너지-${skNrg})`,'ability-log');
        }
        if(sk==='mass_heal'&&skT==='active'&&u.curNrg>=skNrg&&Math.random()<skCh){
          u.curNrg-=skNrg;allies.forEach(a=>{a.currentHp=Math.min(a.currentHp+3,a.maxBHp);});SFX.play('heal');this.log(`${u.icon} 대치유! 아군전체 HP+3 (에너지-${skNrg})`,'heal-log');
        }
        if(sk==='dark_bolt'&&skT==='active'&&u.curNrg>=skNrg&&Math.random()<skCh){
          u.curNrg-=skNrg;const t=foes.filter(c=>c.currentHp>0);if(t.length){const dt=t[Math.floor(Math.random()*t.length)];dt.currentHp-=8;this.showDmg(dt,8,false);this.log(`${u.icon} 암흑탄! ${dt.icon}-8 (에너지-${skNrg})`,'ability-log');}
        }
        if(sk==='aura_buff'&&skT==='active'&&u.curNrg>=skNrg&&Math.random()<skCh){
          u.curNrg-=skNrg;allies.forEach(a=>{a.atk+=1;a.def=(a.def||0)+1;});this.log(`${u.icon} 오라! 아군 공격+1 방어+1 (에너지-${skNrg})`,'ability-log');
        }
        // Bonus trigger: on skill (re-get bt since it may be scoped inside attack block)
        const bt=u.bonusTrigger;
        if(bt&&bt.on==='skill'&&Math.random()<bt.chance){
          if(bt.effect==='group_heal'){allies.forEach(a=>{a.currentHp=Math.min(a.currentHp+2,a.maxBHp);});this.log(`${u.icon} 집단치유!`,'heal-log');}
          if(bt.effect==='bless'){const ra=allies.filter(c=>c.currentHp>0);if(ra.length){const t=ra[Math.floor(Math.random()*ra.length)];t.curShield=(t.curShield||0)+3;this.log(`${t.icon} 축복! 보호막+3`,'ability-log');}}
          if(bt.effect==='ignite'){foes.filter(c=>c.currentHp>0).forEach(e=>{e.burn=2;e.burnDmg=3;});this.log(`${u.icon} 점화! 적전체 화상2턴`,'ability-log');}
          if(bt.effect==='encore'){u.curNrg+=(skNrg*.5);this.log(`${u.icon} 앙코르! 에너지환원`,'ability-log');}
          if(bt.effect==='divine_shield'){u.divineShield=true;this.log(`${u.icon} 신성방패!`,'ability-log');}
          if(bt.effect==='arcane_burst'){foes.filter(c=>c.currentHp>0).forEach(e=>{e.currentHp-=2;this.showDmg(e,2,false);});this.log(`${u.icon} 비전폭발! 전체-2`,'ability-log');}
          if(bt.effect==='curse'){const t=foes.filter(c=>c.currentHp>0);if(t.length){t[0].noHeal=2;this.log(`${t[0].icon} 저주! 회복불가2턴`,'ability-log');}}
          if(bt.effect==='inferno'){foes.filter(c=>c.currentHp>0).forEach(e=>{e.burn=2;e.burnDmg=2;});this.log(`${u.icon} 업화! 적전체 화상`,'ability-log');}
        }
        } // end else (manual skill check)
        // Stealth from previous kill
        if(u._stealthNext){u._stealthNext=false;u.eva+=100;}

        // Poison tick
        if(u.poisoned>0){u.currentHp-=2;u.poisoned--;this.showDmg(u,2,false);if(u.currentHp<=0)u.currentHp=0;}

        this.renderBF(pCards,eCards);
        if(!this.skipReq)await wait(this.battleSpeed);

        // Check hero deaths → battle ends immediately
        const pH=pCards.find(c=>c.isHero);const eH=eCards.find(c=>c.isHero);
        if(pH&&pH.currentHp<=0){this.battleRunning=false;break;}
        if(eH&&eH.currentHp<=0){this.battleRunning=false;break;}
      }
      // Check after each attack cycle
      const pH=pCards.find(c=>c.isHero);const eH=eCards.find(c=>c.isHero);
      if(!pH||pH.currentHp<=0||!eH||eH.currentHp<=0)break;
    }

    SFX.bgm(false);
    const pH=pCards.find(c=>c.isHero);const eH=eCards.find(c=>c.isHero);
    const enemyHeroDead=eH&&eH.currentHp<=0;
    const myHeroDead=pH&&pH.currentHp<=0;

    if(enemyHeroDead){
      // === VICTORY ===
      this.totalWins++;SFX.play('fanfare');
      // Victory banner + sparkles
      const vb=document.createElement('div');vb.className='victory-banner';vb.textContent='승전!';document.body.appendChild(vb);setTimeout(()=>vb.remove(),2000);
      const sp=document.createElement('div');sp.className='victory-particles';for(let i=0;i<20;i++){const s=document.createElement('div');s.className='victory-sparkle';s.textContent=['✨','⭐','💫','🌟'][i%4];s.style.left=Math.random()*100+'%';s.style.animationDelay=Math.random()*1+'s';sp.appendChild(s);}document.body.appendChild(sp);setTimeout(()=>sp.remove(),3000);
      const goldR=10,xpR=10,honorR=10,lpR=15;
      this.gold+=goldR;this.leaguePoints=Math.max(0,(this.leaguePoints||0)+lpR);
      if(this.leaguePoints>=100&&this.tutStep===13)this.checkTutorial('reach_silver');
      // Give XP & honor to each participating card (find originals in deck)
      const participated=bs.battleDeck.map(c=>c.uid);
      const levelUps=[];
      this.deck.filter(c=>participated.includes(c.uid)).forEach(c=>{
        if(this.giveCardXp(c,xpR))levelUps.push(c.name);
        this.giveCardHonor(c,honorR);
      });
      this.persist();
      this.showBattleEnd(true,goldR,xpR,honorR,levelUps);
    } else if(myHeroDead){
      // === DEFEAT ===
      const goldR=3,xpR=10,honorR=1,lpR=-5;
      this.gold+=goldR;this.leaguePoints=Math.max(0,(this.leaguePoints||0)+lpR);
      const participated=bs.battleDeck.map(c=>c.uid);
      const levelUps=[];
      this.deck.filter(c=>participated.includes(c.uid)).forEach(c=>{
        if(this.giveCardXp(c,xpR))levelUps.push(c.name);
        this.giveCardHonor(c,honorR);
      });
      SFX.play('death');
      // Hero death overlay + slowmo
      const hdo=document.createElement('div');hdo.className='hero-death-overlay';document.body.appendChild(hdo);setTimeout(()=>hdo.remove(),2000);
      this.persist();
      this.showBattleEnd(false,goldR,xpR,honorR,levelUps);
    } else {
      // === Round survived, no hero dead → choices then next round ===
      this.skipReq=false;
      this.showRoundChoice();
    }
   }catch(err){console.error('Battle error:',err);this.log(`⚠️ 에러: ${err.message}`,'atk-log');SFX.bgm(false);this.battleRunning=false;}
  },

  // Show choices between rounds (NO rewards, just choices)
  // Enemy AI picks from same 3 choices, prefers best option
  // Enemy mirrors player's initial deployment (similar units/skills/relics)
  enemyMirrorDeploy(bs){
    const myHero=this.deck.find(c=>c.isHero);
    const myLv=myHero?(myHero.level||1):1;
    const scale=1+(myLv-1)*.1;
    const playerUnits=bs.pCards.filter(c=>!c.isHero);
    const playerRelics=bs.battleRelics.length;
    // Collect player unit rarities to match
    const pRarities=playerUnits.map(c=>c.rarity||'bronze');

    // Add similar number of units matching player's rarity spread
    const eMinionCount=Math.max(0,playerUnits.length+Math.floor(Math.random()*3)-1);
    for(let i=0;i<eMinionCount;i++){
      // Pick rarity similar to player's units
      const targetRar=pRarities.length?pRarities[i%pRarities.length]:'bronze';
      const ri=R_ORDER.indexOf(targetRar);
      const eRi=Math.max(0,Math.min(R_ORDER.length-2,ri+Math.floor(Math.random()*3)-1));
      const r=R_ORDER[eRi];
      let pool=UNITS.filter(u=>u.rarity===r&&!u.id.startsWith('h_'));if(!pool.length)pool=UNITS.filter(u=>u.rarity==='bronze'&&!u.id.startsWith('h_'));
      const b=pool[Math.floor(Math.random()*pool.length)];
      const m={...b,uid:'e_'+uid(),level:Math.max(1,myLv+Math.floor(Math.random()*2)-1),equips:[],
        atk:Math.round(b.atk*scale),hp:Math.round(b.hp*scale),maxHp:Math.round(b.hp*scale),def:Math.round(b.def*scale),
        currentHp:Math.round(b.hp*scale),maxBHp:Math.round(b.hp*scale),side:'enemy',
        row:(b.type==='전사'||b.type==='야수')?'front':'back',frozen:0,poisoned:0,revived:false,invincible:0,curNrg:0,curShield:b.shield||0,burn:0};
      bs.eCards.push(m);
    }

    // Add similar number of skills to random units
    const eSkillCount=Math.max(0,Math.floor(playerUnits*0.7)+Math.floor(Math.random()*2));
    const eAlive=bs.eCards.filter(c=>c.currentHp>0);
    for(let i=0;i<eSkillCount&&eAlive.length;i++){
      const r=pickRar(diff*.3);let pool=SKILLS_DB.filter(s=>s.rarity===r);if(!pool.length)pool=SKILLS_DB;
      const sk=pool[Math.floor(Math.random()*pool.length)];
      const t=eAlive[Math.floor(Math.random()*eAlive.length)];
      applySkillToUnit(sk,t);t.equips=t.equips||[];t.equips.push({icon:sk.icon,name:sk.name,id:sk.id});
    }

    // Apply similar number of relics
    const eRelicCount=Math.max(0,playerRelics+Math.floor(Math.random()*2)-1);
    for(let i=0;i<eRelicCount;i++){
      const r=pickRar(diff*.3);let pool=RELICS_DB.filter(x=>x.rarity===r);if(!pool.length)pool=RELICS_DB;
      const rl=pool[Math.floor(Math.random()*pool.length)];
      applyRelicBattle(rl,bs.eCards);
    }
  },

  // AI performs multiple actions based on AP with situational awareness
  enemyRoundActions(bs){
    const ap=this.getActionPoints();
    const msgs=[];
    for(let a=0;a<ap;a++){
      const msg=this._enemySingleAction(bs);
      if(msg)msgs.push(msg);
    }
    return msgs;
  },
  _enemySingleAction(bs){
    const eAlive=bs.eCards.filter(c=>c.currentHp>0);
    const eHero=bs.eCards.find(c=>c.isHero&&c.currentHp>0);
    const diff=this.totalWins+this.getHeroLevel();
    const scale=1+diff*.08;
    const rd=bs.currentRound;

    // Situational AI: assess what's needed
    const unitCount=eAlive.filter(c=>!c.isHero).length;
    const heroHpPct=eHero?(eHero.currentHp/eHero.maxBHp):1;
    const hasSkillTargets=eAlive.some(c=>!c.isHero&&(c.equips||[]).length<2);

    // Priority 1: Potion if hero low HP
    if(eHero&&heroHpPct<0.3&&!(bs._ePotionCd>0)){
      const heal=Math.floor(eHero.maxBHp*.5);
      eHero.currentHp=Math.min(eHero.currentHp+heal,eHero.maxBHp);
      bs._ePotionCd=2;
      return `적 영웅이 포션 사용! HP+${heal}`;
    }

    // Priority 2: Add units if outnumbered or too few
    let choice;
    if(unitCount<=1) choice='add_card';
    else if(unitCount<=3&&Math.random()<0.5) choice='add_card';
    else if(hasSkillTargets&&Math.random()<0.4) choice='pick_skill';
    else if(Math.random()<0.4) choice='pick_relic';
    else choice='add_card';

    if(choice==='add_card'){
      const candidates=[];
      for(let i=0;i<3;i++){
        const r=pickRar(rd*.5,'battle');let pool=UNITS.filter(u=>u.rarity===r&&!u.id.startsWith('h_'));if(!pool.length)pool=UNITS.filter(u=>!u.id.startsWith('h_'));
        const b=pool[Math.floor(Math.random()*pool.length)];
        candidates.push({...b,uid:'e_'+uid(),level:1,equips:[],
          atk:Math.round(b.atk*scale),hp:Math.round(b.hp*scale),maxHp:Math.round(b.hp*scale),def:Math.round(b.def*scale)});
      }
      const rarVal={divine:5,legendary:4,gold:3,silver:2,bronze:1};
      candidates.sort((a,b)=>(rarVal[b.rarity]||0)-(rarVal[a.rarity]||0)||(b.atk-a.atk));
      const pick=candidates[0];
      const dup=eAlive.find(x=>x.id===pick.id);
      if(dup){fuseCard(dup);dup.currentHp=dup.maxBHp=dup.hp;return `${dup.icon}${dup.name} 합성→${R_LABEL[dup.rarity]}`;}
      pick.currentHp=pick.hp;pick.maxBHp=pick.maxHp;pick.side='enemy';
      pick.row=(pick.type==='전사'||pick.type==='야수')?'front':'back';
      pick.frozen=0;pick.poisoned=0;pick.revived=false;pick.invincible=0;
      bs.eCards.push(pick);
      return `${pick.icon}${pick.name}(${R_LABEL[pick.rarity]}) 고용`;
    } else if(choice==='pick_skill'){
      const updated=bs.eCards.filter(c=>c.currentHp>0);
      if(updated.length){
        const r=pickRar(rd*.4);let pool=SKILLS_DB.filter(s=>s.rarity===r);if(!pool.length)pool=SKILLS_DB;
        const sk=pool[Math.floor(Math.random()*pool.length)];
        // Prefer units with fewer equips
        const sorted=[...updated].sort((a,b)=>((a.equips||[]).length)-((b.equips||[]).length));
        const t=sorted[0];
        applySkillToUnit(sk,t);t.equips=t.equips||[];t.equips.push({icon:sk.icon,name:sk.name,id:sk.id});
        return `${t.icon}${t.name}에 ${sk.icon}${sk.name}`;
      }
      return '';
    } else {
      const updated=bs.eCards.filter(c=>c.currentHp>0);
      const r=pickRar(rd*.4);let pool=RELICS_DB.filter(x=>x.rarity===r);if(!pool.length)pool=RELICS_DB;
      const rl=pool[Math.floor(Math.random()*pool.length)];
      applyRelicBattle(rl,updated);
      return `${rl.icon}${rl.name} 유물 장착`;
    }
  },

  _roundTimer:null,_roundTimerLeft:0,

  showRoundChoice(){
    UI.show('choice-screen');
    this.checkTutorial('first_survive');
    const bs=this.battleState;
    const rd=bs.currentRound;
    // Initialize AP for this round (only on first call per round)
    if(!bs._apInitedRound||bs._apInitedRound!==rd){
      bs._apInitedRound=rd;
      bs._apRemaining=this.getActionPoints();
      bs._enemyActioned=false;
      bs._enemyMsgsHidden=null;
      // Decrease potion cooldown
      if(bs._potionCooldown>0)bs._potionCooldown--;
      if(bs._ePotionCd>0)bs._ePotionCd--;
      // Enemy AI: compute but don't reveal yet
      bs._enemyMsgsHidden=this.enemyRoundActions(bs);
      // Start round timer (15sec per AP, min 20, max 60)
      this._roundTimerLeft=Math.min(60,Math.max(20,this.getActionPoints()*15));
      this._startRoundTimer();
    }
    const apLeft=bs._apRemaining;
    const maxAp=this.getActionPoints();
    document.getElementById('ch-title').textContent=`라운드 ${rd} 생존!`;
    const apBar='🟡'.repeat(apLeft)+'⚫'.repeat(maxAp-apLeft);
    const botName=this._currentBot?this._currentBot.name:'적';
    document.getElementById('ch-sub').innerHTML=`다음은 라운드 ${rd+1} (${rd+1}번 공격)<br>
      <span style="color:#ffd700;font-size:.95rem;">행동력 ${apBar} ${apLeft}/${maxAp}</span><br>
      <div class="timer-bar"><div class="timer-bar-fill" id="round-timer-bar" style="width:100%;"></div></div>
      <div class="timer-text">⏱️ <span id="round-timer-text">${this._roundTimerLeft}</span>초 | ${botName}도 선택 중...</div>`;
    const opts=document.getElementById('ch-options');opts.innerHTML='';
    [{icon:'🃏',title:'동료 소환',desc:'새 동료 소환 (중복 시 합성)',action:'add_card'},
     {icon:'⚡',title:'전투 비전',desc:'비전 습득 & 장착 (중복 시 합성)',action:'pick_skill'},
     {icon:'🏺',title:'유물 발견',desc:'유물 획득 (중복 시 합성)',action:'pick_relic'},
     {icon:'🧪',title:'치유 물약',desc:'영웅 HP 50% 회복 (쿨다운 1R)',action:'potion'},
     {icon:'⏭️',title:'출전 준비',desc:'남은 행동력을 포기하고 전투 시작',action:'end_turn'}].forEach(o=>{
      const d=document.createElement('div');d.className='choice-box';
      const potionCd=bs._potionCooldown||0;
      if(o.action==='potion'&&potionCd>0){
        d.style.opacity='.3';d.style.pointerEvents='none';
        d.innerHTML=`<div class="cb-icon">${o.icon}</div><div class="cb-title">${o.title}</div><div class="cb-desc" style="color:#ff4444;">쿨다운 ${potionCd}라운드</div>`;
      } else if(o.action==='end_turn'){
        d.innerHTML=`<div class="cb-icon">${o.icon}</div><div class="cb-title">${o.title}</div><div class="cb-desc">${o.desc}</div>`;
        d.onclick=()=>{SFX.play('click');this._stopRoundTimer();bs._apRemaining=0;this._revealAndFinish();};
      } else {
        d.innerHTML=`<div class="cb-icon">${o.icon}</div><div class="cb-title">${o.title}</div><div class="cb-desc">${o.desc}</div>`;
        d.onclick=()=>{SFX.play('click');this.doRoundChoice(o.action);};
      }
      opts.appendChild(d);});
  },

  _startRoundTimer(){
    this._stopRoundTimer();
    const maxTime=this._roundTimerLeft;
    this._roundTimer=setInterval(()=>{
      this._roundTimerLeft--;
      const el=document.getElementById('round-timer-text');
      const bar=document.getElementById('round-timer-bar');
      if(el)el.textContent=this._roundTimerLeft;
      if(bar)bar.style.width=Math.max(0,(this._roundTimerLeft/maxTime)*100)+'%';
      if(this._roundTimerLeft<=5&&el)el.style.color='#ff4444';
      if(this._roundTimerLeft<=0){
        this._stopRoundTimer();
        // Time's up — auto skip remaining AP
        const bs=this.battleState;if(bs)bs._apRemaining=0;
        SFX.play('click');
        this._revealAndFinish();
      }
    },1000);
  },

  _stopRoundTimer(){if(this._roundTimer){clearInterval(this._roundTimer);this._roundTimer=null;}},

  _revealAndFinish(){
    this._stopRoundTimer();
    const bs=this.battleState;if(!bs){this.showMenu();return;}
    const msgs=bs._enemyMsgsHidden||[];
    bs._enemyMsgs=msgs;bs._enemyMsgsHidden=null;
    if(msgs.length){
      const botName=this._currentBot?this._currentBot.name:'적';
      UI.modal(`⚔️ ${botName}의 행동`,msgs.map((m,i)=>`${i+1}. ${m}`).join('\n'),()=>{
        this.finishRound();
      });
    } else {
      this.finishRound();
    }
  },

  doRoundChoice(action){
    const bs=this.battleState;

    // === POTION: instant use, no pick screen ===
    if(action==='potion'){
      const hero=bs.pCards.find(c=>c.isHero);
      if(hero){
        const heal=Math.floor(hero.maxBHp*.5);
        hero.currentHp=Math.min(hero.currentHp+heal,hero.maxBHp);
        bs._potionCooldown=2;
        SFX.play('heal');
      }
      bs._apRemaining=Math.max(0,(bs._apRemaining||1)-1);
      if(bs._apRemaining>0){this.showRoundChoice();return;}
      this._stopRoundTimer();this._revealAndFinish();
      return;
    }

    UI.show('pick-screen');
    const title=document.getElementById('pick-title'),sub=document.getElementById('pick-sub'),grid=document.getElementById('pick-grid');
    grid.innerHTML='';document.getElementById('pick-confirm-btn').disabled=true;
    let picked=false;
    this._currentPickAction=action;
    const onPick=()=>{document.getElementById('pick-confirm-btn').disabled=false;};

    // Check if duplicate exists in battle cards
    const checkDupUnit=(c)=>bs.pCards.find(x=>x.id===c.id&&x.uid!==c.uid&&x.currentHp>0);
    const checkDupRelic=(rl)=>bs.battleRelics.find(x=>x.id===rl.id);

    if(action==='add_card'){
      title.textContent='🃏 동료 선택 (이번 전투)';sub.textContent='중복 시 합성하여 등급 상승!';
      for(let i=0;i<3;i++){
        const r=pickRar(bs.currentRound*.5,'battle');let pool=UNITS.filter(u=>u.rarity===r&&!u.id.startsWith('h_'));if(!pool.length)pool=UNITS.filter(u=>!u.id.startsWith('h_'));
        const b=pool[Math.floor(Math.random()*pool.length)];const scale=1+(bs.currentRound-1)*.05;
        const c={...b,uid:uid(),level:1,equips:[],atk:Math.round(b.atk*scale),hp:Math.round(b.hp*scale),maxHp:Math.round(b.hp*scale),def:Math.round(b.def*scale)};
        const dup=checkDupUnit(c);
        const el=mkCardEl(c);
        if(dup){const tag=document.createElement('div');tag.style.cssText='text-align:center;font-size:.7rem;color:#ff66ff;margin-top:2px;';tag.textContent=`🔀 합성 가능! → ${R_LABEL[upgradeRarity(dup.rarity)]}`;el.appendChild(tag);}
        let addedUnit=null;
        el.onclick=()=>{
          if(picked&&addedUnit){
            // DESELECT: 해제
            bs.pCards=bs.pCards.filter(p=>p.uid!==addedUnit.uid);
            addedUnit=null;picked=false;SFX.play('click');
            el.style.opacity='1';el.style.border='';
            grid.querySelectorAll('.card').forEach(x=>{x.style.pointerEvents='';x.style.opacity='1';});
            sub.textContent='동료를 다시 선택하세요.';
            document.getElementById('pick-confirm-btn').disabled=true;
            return;
          }
          if(picked)return;
          if(dup){
            UI.modal('합성 확인',`${dup.icon}${dup.name}(${R_LABEL[dup.rarity]})과 합성하여\n${R_LABEL[upgradeRarity(dup.rarity)]}로 강화하시겠습니까?\n(기존 동료의 힘을 흡수합니다)`,()=>{
              fuseCard(dup);dup.currentHp=dup.maxBHp=dup.hp;
              picked=true;SFX.play('magic');
              grid.querySelectorAll('.card').forEach(x=>{x.style.pointerEvents='none';x.style.opacity='.4';});
              sub.textContent=`🔀 합성! ${dup.name} → ${R_LABEL[dup.rarity]}!`;onPick();
            });
          } else {
            // SELECT: 선택
            picked=true;
            addedUnit={...c,currentHp:c.hp,maxBHp:c.maxHp,side:'player',row:'back',frozen:0,poisoned:0,revived:false,invincible:0,curNrg:0,curShield:c.shield||0,burn:0};
            bs.pCards.push(addedUnit);
            SFX.play('click');
            grid.querySelectorAll('.card').forEach(x=>{if(x!==el){x.style.pointerEvents='none';x.style.opacity='.4';}});
            el.style.opacity='.6';el.style.border='2px solid #44ff88';
            sub.textContent=`✅ ${c.name} 합류! (다시 클릭하면 취소)`;onPick();
          }
        };
        grid.appendChild(el);
      }
    } else if(action==='pick_skill'){
      title.textContent='⚡ 비전 선택 (이번 전투)';sub.textContent='동료에게 전수! 중복 시 합성 강화';
      for(let i=0;i<3;i++){
        const r=pickRar(bs.currentRound*.4);let pool=SKILLS_DB.filter(s=>s.rarity===r);if(!pool.length)pool=SKILLS_DB;
        const sk={...pool[Math.floor(Math.random()*pool.length)],uid:uid()};
        const el=mkRelicEl(sk);el.querySelector('.card-type').textContent='비전 · '+ROLE_L[sk.role];
        // Check if any battle unit already has same skill equipped
        const dupUnit=bs.pCards.find(u=>u.currentHp>0&&(u.equips||[]).some(e=>e.id===sk.id));
        if(dupUnit){const tag=document.createElement('div');tag.style.cssText='text-align:center;font-size:.7rem;color:#ff66ff;margin-top:2px;';tag.textContent=`🔀 ${dupUnit.name}에 합성 가능!`;el.appendChild(tag);}
        el.onclick=()=>{
          if(picked)return;
          if(dupUnit){
            UI.modal('비전 합성',`${dupUnit.icon}${dupUnit.name}의 ${sk.icon}${sk.name}을 합성 강화하시겠습니까?\n(능력치 2배 강화)`,()=>{
              picked=true;applySkillToUnit(sk,dupUnit);SFX.play('magic');
              grid.querySelectorAll('.card').forEach(x=>{x.style.pointerEvents='none';x.style.opacity='.4';});
              sub.textContent=`🔀 ${dupUnit.name}의 ${sk.name} 합성 강화!`;onPick();
            });
          } else {
            // Show equip target selection
            picked=true;
            grid.querySelectorAll('.card').forEach(x=>{x.style.pointerEvents='none';if(x!==el)x.style.opacity='.4';});
            el.style.opacity='.6';
            this.equipSkillBattle(sk,bs,()=>{sub.textContent=`⚡ ${sk.name} 장착 완료!`;onPick();});
          }
        };
        grid.appendChild(el);
      }
    } else if(action==='pick_relic'){
      title.textContent='🏺 유물 선택 (이번 전투)';sub.textContent='전체 적용! 중복 시 합성 강화';
      for(let i=0;i<3;i++){
        const r=pickRar(bs.currentRound*.4);let pool=RELICS_DB.filter(x=>x.rarity===r);if(!pool.length)pool=RELICS_DB;
        const rl={...pool[Math.floor(Math.random()*pool.length)],uid:uid()};
        const dup=checkDupRelic(rl);
        const el=mkRelicEl(rl);
        if(dup){const tag=document.createElement('div');tag.style.cssText='text-align:center;font-size:.7rem;color:#ff66ff;margin-top:2px;';tag.textContent=`🔀 합성 가능! → ${R_LABEL[upgradeRarity(dup.rarity||rl.rarity)]}`;el.appendChild(tag);}
        el.onclick=()=>{
          if(picked)return;
          if(dup){
            UI.modal('유물 합성',`${rl.icon}${rl.name} 유물을 합성하여 효과를 2배로 강화하시겠습니까?`,()=>{
              picked=true;applyRelicBattle(rl,bs.pCards);SFX.play('magic'); // apply again = double
              grid.querySelectorAll('.card').forEach(x=>{x.style.pointerEvents='none';x.style.opacity='.4';});
              sub.textContent=`🔀 ${rl.name} 합성 강화!`;onPick();
            });
          } else {
            picked=true;
            bs.battleRelics.push(rl);applyRelicBattle(rl,bs.pCards);SFX.play('magic');
            grid.querySelectorAll('.card').forEach(x=>{x.style.pointerEvents='none';if(x!==el)x.style.opacity='.4';});
            el.style.opacity='.6';sub.textContent=`✅ ${rl.name} 장착!`;onPick();
          }
        };
        grid.appendChild(el);
      }
    }
  },

  // After battle ends — ROGUELIKE RESET: all temp cards/upgrades/relics gone
  showBattleEnd(won,goldR,xpR,honorR,levelUps=[]){
    this.checkTutorial('first_battle_end');
    if(!won)this.checkTutorial('first_defeat');
    UI.show('reward-screen');
    const title=document.getElementById('rew-title'),sub=document.getElementById('rew-sub'),stats=document.getElementById('rew-stats');
    const rcards=document.getElementById('reward-cards');rcards.innerHTML='';
    const rd=this.battleState?this.battleState.currentRound:0;

    if(won){
      title.textContent='🏆 승전!';title.className='reward-title victory';
      sub.textContent=`${rd}라운드 만에 적 영웅을 쓰러뜨렸습니다!`;
    } else {
      title.textContent='💀 패전';title.className='reward-title defeat';
      sub.textContent=`라운드 ${rd}에서 영웅이 쓰러졌습니다`;
    }
    const lg=this.getLeague();
    let lvStr=levelUps.length?`<br>🎉 성장: ${levelUps.join(', ')}`:'';
    stats.innerHTML=`💰+${goldR} | 🏆${won?'+15':'-5'}점 | 동료별 ✨+${xpR}경험 ⭐+${honorR}${lvStr}<br><span style="color:${lg.color};">${lg.icon} ${lg.name} (${this.leaguePoints}점)</span>`;

    // === WIN STREAK + BLESSINGS ===
    if(won){
      this.winStreak=(this.winStreak||0)+1;
      this.blessings=(this.blessings||0)+1; // 1승 = 1 신의축복
      let streakBonus=0;
      if(this.winStreak>=10){streakBonus=3;}
      else if(this.winStreak>=5){streakBonus=2;}
      else if(this.winStreak>=3){streakBonus=1;}
      if(streakBonus>0){this.blessings+=streakBonus;}
      const streakMsg=this.winStreak>=3?`<br>🔥 <span style="color:#ff6644;">${this.winStreak}연승! 신의축복 +${1+streakBonus}개</span>`:`<br>✨ 신의축복 +1`;
      stats.innerHTML+=streakMsg;
    } else {
      this.winStreak=0;
    }
    // === LOOT / REWARD ===
    const lgIdx=this.LEAGUES.indexOf(lg);
    const leagueGoldBonus=lgIdx>=5?0.6:lgIdx>=4?0.4:lgIdx>=3?0.4:lgIdx>=2?0.2:lgIdx>=1?0.2:0;

    if(!won){
      // === DEFEAT: simple reward + 신의 은총 2배 ===
      this._lootPicked=true; // 패전은 선택 없으므로 바로 통과
      const defeatGold=Math.floor(3*(1+leagueGoldBonus));
      this.gold+=defeatGold;
      const lootDiv=document.createElement('div');lootDiv.style.cssText='text-align:center;margin:10px 0;';
      lootDiv.innerHTML=`<div style="color:#aaa;font-size:.85rem;margin-bottom:8px;">📦 패전 보상: 💰+${defeatGold}</div>`;
      const dblBtn=document.createElement('div');dblBtn.className='loot-double-btn';
      dblBtn.innerHTML=`<button class="btn btn-s btn-green">📺 신의 은총 (보상 2배: +${defeatGold}💰)</button>`;
      dblBtn.querySelector('button').onclick=()=>{
        this.gold+=defeatGold;SFX.play('upgrade');
        stats.innerHTML+=`<br>📺 <span style="color:#44ff88;">신의 은총! 💰+${defeatGold} 추가!</span>`;
        dblBtn.querySelector('button').disabled=true;dblBtn.querySelector('button').textContent='✅ 은총 적용됨';
        this.persist();
      };
      lootDiv.appendChild(dblBtn);
      rcards.appendChild(lootDiv);
    } else {
    // === VICTORY: loot boxes ===
    const baseGold={gold:15,silver:8,bronze:3};
    const lootDiv=document.createElement('div');lootDiv.style.cssText='text-align:center;margin:10px 0;';
    // 5 streak = guaranteed gold box
    const forceGold=won&&this.winStreak>=5;
    lootDiv.innerHTML=`<div style="color:#ffd700;font-size:.9rem;margin-bottom:8px;">🎁 전리품을 선택하세요!${forceGold?' <span style="color:#ff6644;">(5연승! 금 상자 확정)</span>':''}</div>`;
    const boxRow=document.createElement('div');boxRow.className='loot-boxes';
    const tiers=forceGold?['gold','gold','silver']:['gold','silver','bronze'];
    const shuffled=[...tiers].sort(()=>Math.random()-.5);
    // League-scaled loot rarity for item drops
    const itemRarPool=lgIdx>=4?'legendary':lgIdx>=3?'gold':lgIdx>=2?'gold':lgIdx>=1?'silver':'bronze';
    const lootRewards={
      gold:{label:'금 상자',gold:Math.floor(baseGold.gold*(1+leagueGoldBonus)),bonus:'gold',color:'#ffd700'},
      silver:{label:'은 상자',gold:Math.floor(baseGold.silver*(1+leagueGoldBonus)),bonus:'silver',color:'#c0c0c0'},
      bronze:{label:'동 상자',gold:Math.floor(baseGold.bronze*(1+leagueGoldBonus)),bonus:null,color:'#cd7f32'},
    };
    let lootPicked=false;
    shuffled.forEach((tier,i)=>{
      const box=document.createElement('div');box.className='loot-box';
      box.innerHTML='📦';box.title=`상자 ${i+1}`;
      box.onclick=()=>{
        if(lootPicked)return;lootPicked=true;this._lootPicked=true;
        const reward=lootRewards[tier];
        SFX.play(tier==='gold'?'rarity_up':tier==='silver'?'magic':'click');
        boxRow.querySelectorAll('.loot-box').forEach((b,j)=>{
          const t=shuffled[j];const rw=lootRewards[t];
          b.classList.add('opened',t+'-loot');
          b.innerHTML=`<div style="font-size:1.5rem;">${t==='gold'?'🏆':t==='silver'?'🥈':'🥉'}</div>`;
          const res=document.createElement('div');res.className='loot-result';
          if(j===i){res.innerHTML=`<span style="color:${rw.color};font-weight:bold;">✅ ${rw.label}</span><br>💰+${rw.gold}`;b.style.transform='scale(1.1)';}
          else{res.innerHTML=`<span style="color:#555;">${rw.label}</span><br><span style="color:#555;">💰+${rw.gold}</span>`;b.style.opacity='.5';}
          b.appendChild(res);
        });
        this.gold+=reward.gold;
        let bonusText='';
        // Gold box: 30% blessing + 70% skill/relic
        if(reward.bonus==='gold'&&won){
          if(Math.random()<0.3){this.blessings=(this.blessings||0)+1;bonusText=`✨ 신의축복 +1 추가!`;}
          else{
            const maxR=itemRarPool;const pool=SKILLS_DB.filter(s=>R_ORDER.indexOf(s.rarity)<=R_ORDER.indexOf(maxR));
            if(pool.length){const sk={...pool[Math.floor(Math.random()*pool.length)],uid:uid()};this.ownedSkills=this.ownedSkills||[];this.ownedSkills.push(sk);bonusText=`⚡ ${sk.name} 비전 획득!`;}
          }
        }
        // Silver box: 10% blessing
        if(reward.bonus==='silver'&&won){
          if(Math.random()<0.1){this.blessings=(this.blessings||0)+1;bonusText=`✨ 신의축복 +1 추가!`;}
        }
        // 10 streak: guaranteed legendary reward
        if(won&&this.winStreak>=10&&tier==='gold'){
          const pool=RELICS_DB.filter(r=>r.rarity==='legendary');
          if(pool.length){const rl=pool[Math.floor(Math.random()*pool.length)];this.ownedRelics=this.ownedRelics||[];this.ownedRelics.push({...rl,uid:uid()});applyRelic(rl,this.deck);bonusText=`🏺 전설 유물 ${rl.name} 획득!`;}
        }
        stats.innerHTML+=`<br>📦 ${reward.label}: 💰+${reward.gold}${bonusText?'<br>🏆 <span style="color:#ffd700;">'+bonusText+'</span>':''}`;
        // Double reward button
        const dblBtn=document.createElement('div');dblBtn.className='loot-double-btn';
        dblBtn.innerHTML=`<button class="btn btn-s btn-green" id="double-reward-btn">📺 신의 은총 (골드 2배)</button>`;
        dblBtn.querySelector('button').onclick=()=>{
          this.gold+=reward.gold;SFX.play('rarity_up');
          stats.innerHTML+=`<br>📺 <span style="color:#44ff88;">신의 은총! 💰+${reward.gold} 추가!</span>`;
          dblBtn.querySelector('button').disabled=true;dblBtn.querySelector('button').textContent='✅ 은총 적용됨';
          this.persist();
        };
        lootDiv.appendChild(dblBtn);
        this.persist();
      };
      boxRow.appendChild(box);
    });
    lootDiv.appendChild(boxRow);
    rcards.appendChild(lootDiv);
    } // end if(won) loot boxes

    // === ROGUELIKE RESET — restore stats but keep XP/honor/level ===
    // Track which deployed units died in battle
    const deadUids=new Set();
    if(this.battleState){
      const bs=this.battleState;
      const deployed=bs.battleDeck||[];
      const pCards=bs.pCards||[];
      deployed.forEach(dc=>{
        const bc=pCards.find(p=>p.uid===dc.uid);
        if(bc&&bc.currentHp<=0&&!bc.isHero)deadUids.add(bc.uid);
      });
    }
    if(this._deckSnapshot){
      const xpMap={};
      this.deck.forEach(c=>{xpMap[c.uid]={xp:c.xp||0,honor:c.honor||0,level:c.level||1};});
      const snapLvMap={};
      this._deckSnapshot.forEach(c=>{snapLvMap[c.uid]=c.level||1;});
      this.deck=this._deckSnapshot;
      this.deck.forEach(c=>{
        const saved=xpMap[c.uid];
        if(saved){
          const prevLv=snapLvMap[c.uid]||1;
          c.xp=saved.xp;c.honor=saved.honor;c.level=saved.level;
          const gained=c.level-prevLv;
          if(gained>0){c.atk+=gained;c.hp+=gained*2;c.maxHp+=gained*2;c.def+=gained;}
        }
        // Mark dead deployed units as injured
        if(deadUids.has(c.uid)){c.injured=true;}
      });
      this._deckSnapshot=null;
    }
    this.relics=[];
    this.battleState=null;
    this.persist();
  },

  // Equip a permanent skill to a unit
  equipSkillPermanent(skillData){
    const modal=document.getElementById('equip-modal');
    document.getElementById('equip-title').textContent='비전 장착 대상 선택 (영구)';
    document.getElementById('equip-skill-info').textContent=`${skillData.icon} ${skillData.name}: ${skillData.desc}`;
    const targets=document.getElementById('equip-targets');targets.innerHTML='';
    this.deck.forEach(c=>{
      const d=document.createElement('div');d.className=`deck-mini ${c.rarity||'bronze'}`;d.style.cursor='pointer';
      d.innerHTML=`<div class="dm-icon">${c.icon}</div><div class="dm-name">${c.isHero?'⭐':''}${c.name}</div>`;
      d.onclick=()=>{
        applySkillToUnit(skillData,c);
        c.equips=c.equips||[];c.equips.push({icon:skillData.icon,name:skillData.name,id:skillData.id});
        modal.classList.remove('active');SFX.play('magic');this.persist();
      };targets.appendChild(d);});
    modal.classList.add('active');
  },

  // Equip skill during battle (to battle cards)
  equipSkillBattle(skillData,bs,cb){
    const modal=document.getElementById('equip-modal');
    document.getElementById('equip-title').textContent='비전 장착 대상 선택';
    document.getElementById('equip-skill-info').textContent=`${skillData.icon} ${skillData.name}: ${skillData.desc}`;
    const targets=document.getElementById('equip-targets');targets.innerHTML='';
    bs.pCards.filter(c=>c.currentHp>0).forEach(c=>{
      const d=document.createElement('div');d.className=`deck-mini ${c.rarity||'bronze'}`;d.style.cursor='pointer';
      d.innerHTML=`<div class="dm-icon">${c.icon}</div><div class="dm-name">${c.isHero?'⭐':''}${c.name}</div>`;
      d.onclick=()=>{
        applySkillToUnit(skillData,c);
        c.equips=c.equips||[];c.equips.push({icon:skillData.icon,name:skillData.name,id:skillData.id});
        modal.classList.remove('active');SFX.play('magic');if(cb)cb();
      };targets.appendChild(d);});
    modal.classList.add('active');
  },

  // ---- ACTION ANIMATION ----
  _lastTarget:null,
  async showAction(unit,actionText,target){
    if(this.skipReq)return;
    if(target)this._lastTarget=target;
    const tgt=target||this._lastTarget;
    const isCrit=actionText.includes('치명타');
    const spd=this.battleMultiplier||1;
    const atkImg=getCardImg(unit);
    const tgtImg=tgt?getCardImg(tgt):null;
    const elem=unit.element;
    let fxSrc='';
    if(unit.type==='마법사'&&elem)fxSrc=`img/fx_${elem}.png`;
    else if(unit.type==='사수')fxSrc='img/fx_arrow.png';
    else fxSrc='img/fx_slash.png';

    // Highlight active turn card
    document.querySelectorAll('.battle-card.active-turn').forEach(e=>e.classList.remove('active-turn'));
    const atkEl=document.getElementById(`bc-${unit.uid}`);
    if(atkEl)atkEl.classList.add('active-turn');
    // Get attacker/target screen positions
    const tgtEl=tgt?document.getElementById(`bc-${tgt.uid}`):null;
    const atkRect=atkEl?atkEl.getBoundingClientRect():{left:window.innerWidth*.3,top:window.innerHeight*.5,width:100,height:130};
    const tgtRect=tgtEl?tgtEl.getBoundingClientRect():{left:window.innerWidth*.7,top:window.innerHeight*.3,width:100,height:130};

    // Dim overlay
    const ov=document.createElement('div');ov.className='atk-zoom-overlay';ov.id='atk-zoom-ov';
    ov.style.display='block';
    document.body.appendChild(ov);

    // [STEP 1] Attacker zooms up from card position
    const atk=document.createElement('div');atk.style.cssText=`position:fixed;z-index:185;pointer-events:none;text-align:center;
      left:${atkRect.left+atkRect.width/2}px;top:${atkRect.top+atkRect.height/2}px;transform:translate(-50%,-50%) scale(.3);opacity:0;transition:all ${.2/spd}s ease-out;`;
    atk.innerHTML=`<div class="azc-card ${unit.rarity||'bronze'}" style="${isCrit?'box-shadow:0 0 40px rgba(255,68,68,.6);':''}">
      ${atkImg?`<img class="azc-img" src="${atkImg}" style="width:${isCrit?120:100}px;height:${isCrit?120:100}px;">`:`<div style="font-size:3rem;">${unit.icon}</div>`}
      <div class="azc-name">${unit.isHero?'⭐ ':''}${unit.name}</div>
      <div class="azc-action" style="color:${isCrit?'#ffaa00':'#ff6644'};font-size:${isCrit?'1.1rem':'.85rem'};">${actionText}</div>
    </div>`;
    document.body.appendChild(atk);

    // Zoom to center-left
    await wait(20);
    const centerX=window.innerWidth*(unit.side==='player'?.35:.65);
    const centerY=window.innerHeight*.45;
    atk.style.left=centerX+'px';atk.style.top=centerY+'px';
    atk.style.transform='translate(-50%,-50%) scale(1)';atk.style.opacity='1';
    await wait(Math.floor(200/spd));

    // [STEP 2] Charge toward target + effect explosion
    if(tgtEl){
      // Projectile / charge motion
      const midX=(centerX+tgtRect.left+tgtRect.width/2)/2;
      const midY=(centerY+tgtRect.top+tgtRect.height/2)/2;

      if(unit.type==='사수'||unit.type==='마법사'){
        // Ranged: projectile flies from attacker to target
        const proj=document.createElement('div');proj.style.cssText=`position:fixed;z-index:186;pointer-events:none;
          left:${centerX}px;top:${centerY}px;transform:translate(-50%,-50%);transition:all ${.25/spd}s ease-in;`;
        proj.innerHTML=fxSrc?`<img src="${fxSrc}" style="width:50px;height:50px;">`:'✨';
        document.body.appendChild(proj);
        await wait(20);
        proj.style.left=(tgtRect.left+tgtRect.width/2)+'px';
        proj.style.top=(tgtRect.top+tgtRect.height/2)+'px';
        proj.style.transform='translate(-50%,-50%) scale(1.5)';
        await wait(Math.floor(250/spd));
        proj.remove();
      } else {
        // Melee: attacker charges forward
        atk.style.transition=`all ${.15/spd}s ease-in`;
        atk.style.left=(tgtRect.left+tgtRect.width/2)+'px';
        atk.style.top=(tgtRect.top+tgtRect.height/2)+'px';
        atk.style.transform='translate(-50%,-50%) scale(.8)';
        await wait(Math.floor(150/spd));
      }

      // Effect explosion on target
      const fx=document.createElement('div');fx.style.cssText=`position:fixed;z-index:187;pointer-events:none;
        left:${tgtRect.left+tgtRect.width/2}px;top:${tgtRect.top+tgtRect.height/2}px;transform:translate(-50%,-50%) scale(0);
        transition:all ${.15/spd}s ease-out;`;
      fx.innerHTML=fxSrc?`<img src="${fxSrc}" style="width:${isCrit?80:60}px;height:${isCrit?80:60}px;">`:'💥';
      document.body.appendChild(fx);
      await wait(20);
      fx.style.transform='translate(-50%,-50%) scale(1)';
      await wait(Math.floor(150/spd));
      fx.style.opacity='0';fx.style.transform='translate(-50%,-50%) scale(1.8)';
      await wait(Math.floor(100/spd));
      fx.remove();

      // Target shake
      if(tgtEl){
        const hitClass=isCrit?'crit-hit':'hit-flash';
        tgtEl.classList.remove('hit-anim','hit-flash','crit-hit');void tgtEl.offsetWidth;
        tgtEl.classList.add(hitClass);
        setTimeout(()=>tgtEl.classList.remove(hitClass),500);
      }
    }

    // [STEP 3] Attacker fades out
    atk.style.opacity='0';atk.style.transform='translate(-50%,-50%) scale(1.3)';
    atk.style.transition=`all ${.12/spd}s`;
    await wait(Math.floor(120/spd));
    atk.remove();ov.remove();
    if(atkEl)atkEl.classList.remove('active-turn');
  },

  log(t,c){const l=document.getElementById('battle-log');const p=document.createElement('p');p.innerHTML=c?`<span class="${c}">${t}</span>`:t;l.appendChild(p);l.scrollTop=l.scrollHeight;},
  cycleSpeed(){
    if(this.battleMultiplier===1){this.battleMultiplier=2;this.battleSpeed=250;}
    else if(this.battleMultiplier===2){this.battleMultiplier=3;this.battleSpeed=120;}
    else{this.battleMultiplier=1;this.battleSpeed=500;}
    const labels={1:'⏱️ 일반',2:'⏩ 신속',3:'⏭️ 질풍'};
    const btn=document.getElementById('speed-btn');
    if(btn)btn.textContent=labels[this.battleMultiplier];
    SFX.play('click');
  },
  // ── MANUAL SKILL / TARGET SYSTEM ──
  _skillQueue:[], // pending manual skill activations
  _targetMode:false, _targetCallback:null, _playerTarget:null,

  updateSkillBar(){
    const bar=document.getElementById('skill-bar');if(!bar||!this.battleState)return;
    bar.innerHTML='';bar.style.display='flex';
    const bs=this.battleState;
    const pCards=bs.pCards.filter(c=>c.currentHp>0&&c.side==='player'&&c.skillType==='active');
    if(!pCards.length){bar.style.display='none';return;}
    pCards.forEach(c=>{
      const ready=c.curNrg>=c.skillNrg;
      const btn=document.createElement('div');btn.className=`skill-btn${ready?'':' sb-auto'}`;
      btn.innerHTML=`${c.icon} ${c.name}<br><span style="font-size:.55rem;">${c.skillDesc||c.skill}</span>${ready?'<div class="sb-timer" style="width:100%;"></div>':''}`;
      if(ready&&!this.skipReq){
        btn.onclick=()=>{
          SFX.play('magic');
          this._manualSkill(c);
        };
      }
      bar.appendChild(btn);
    });
  },

  _manualSkill(unit){
    const bs=this.battleState;
    const sk=unit.skill;
    const foes=bs.eCards.filter(c=>c.currentHp>0);
    const allies=bs.pCards.filter(c=>c.currentHp>0);
    // Determine if skill needs target
    const needsEnemyTarget=['aoe','breath','dark_bolt','freeze'].includes(sk);
    const needsAllyTarget=['heal_ally'].includes(sk);
    const noTarget=['heal_self','mass_heal','inspire','aura_buff'].includes(sk);

    if(noTarget){
      this._executeSkill(unit,null);
    } else if(needsAllyTarget){
      this._enterTargetMode(allies,'아군을 선택하세요!',(target)=>this._executeSkill(unit,target));
    } else {
      this._enterTargetMode(foes,'대상을 선택하세요!',(target)=>this._executeSkill(unit,target));
    }
  },

  _enterTargetMode(targets,msg,callback){
    this._targetMode=true;this._targetCallback=callback;
    document.getElementById('b-status').textContent=msg;
    document.getElementById('b-status').style.color='#ff6644';
    targets.forEach(c=>{
      const el=document.getElementById(`bc-${c.uid}`);
      if(el){el.classList.add('target-select');
        el.onclick=()=>{
          this._targetMode=false;
          document.querySelectorAll('.target-select').forEach(e=>{e.classList.remove('target-select');e.onclick=null;});
          document.getElementById('b-status').textContent='전투 중...';
          document.getElementById('b-status').style.color='';
          callback(c);
        };
      }
    });
  },

  _executeSkill(unit,target){
    const bs=this.battleState;
    const sk=unit.skill,skNrg=unit.skillNrg||0;
    const foes=bs.eCards.filter(c=>c.currentHp>0);
    const allies=bs.pCards.filter(c=>c.currentHp>0);
    if(unit.curNrg<skNrg)return;
    unit.curNrg-=skNrg;
    unit._manualUsed=true; // flag so auto-skill doesn't double fire
    SFX.play('magic');

    if(sk==='aoe'||sk==='breath'){
      const d=sk==='breath'?5:3;foes.forEach(e=>{e.currentHp-=d;this.showDmg(e,d,false);if(e.currentHp<=0)e.currentHp=0;});
      this.log(`${unit.icon} 수동 비전! 전체${d}데미지`,'ability-log');
    } else if(sk==='heal_self'){
      const h=4;unit.currentHp=Math.min(unit.currentHp+h,unit.maxBHp);this.showHeal(unit,h);SFX.play('heal');
      this.log(`${unit.icon} 수동 자가치유+${h}`,'heal-log');
    } else if(sk==='heal_ally'&&target){
      const h=5;target.currentHp=Math.min(target.currentHp+h,target.maxBHp);this.showHeal(target,h);SFX.play('heal');
      this.log(`${unit.icon}→${target.icon} 수동 치유+${h}`,'heal-log');
    } else if(sk==='mass_heal'){
      allies.forEach(a=>{a.currentHp=Math.min(a.currentHp+3,a.maxBHp);});SFX.play('heal');
      this.log(`${unit.icon} 수동 대치유! 아군전체 HP+3`,'heal-log');
    } else if(sk==='inspire'){
      allies.forEach(a=>{if(a.uid!==unit.uid)a.atk+=2;});
      this.log(`${unit.icon} 수동 고무! 아군 공격+2`,'ability-log');
    } else if(sk==='freeze'&&target){
      target.frozen=1;this.log(`${target.icon} 수동 빙결!`,'ability-log');
    } else if(sk==='dark_bolt'){
      const t=target||foes[0];if(t){t.currentHp-=8;this.showDmg(t,8,false);this.log(`${unit.icon} 수동 암흑탄! ${t.icon}-8`,'ability-log');}
    } else if(sk==='aura_buff'){
      allies.forEach(a=>{a.atk+=1;a.def=(a.def||0)+1;});
      this.log(`${unit.icon} 수동 오라! 아군 공격+1 방어+1`,'ability-log');
    }
    this.renderBF(bs.pCards,bs.eCards);
    this.updateSkillBar();
  },

  // Set player target for normal attacks
  setPlayerTarget(targetUid){
    this._playerTarget=targetUid;
    // Visual
    document.querySelectorAll('.battle-card.targeted').forEach(e=>e.classList.remove('targeted'));
    const el=document.getElementById(`bc-${targetUid}`);
    if(el)el.classList.add('targeted');
  },

  skipBattle(){this.skipReq=true;this.battleSpeed=5;document.getElementById('skill-bar').style.display='none';},
  async triggerSlowMo(duration=1500,type='crit'){
    if(this.skipReq||this._slowMo)return;
    this._slowMo=true;
    const spd=this.battleMultiplier||1;
    const oldSpd=this.battleSpeed;this.battleSpeed=Math.floor(800/spd);
    duration=Math.floor(duration/spd);
    // Visual overlay
    const ov=document.createElement('div');ov.className='slowmo-overlay';ov.id='slowmo-ov';
    if(type==='crit')ov.style.background='radial-gradient(circle,rgba(255,100,50,.15),transparent 70%)';
    else if(type==='danger')ov.style.background='radial-gradient(circle,rgba(255,0,0,.2),transparent 70%)';
    else if(type==='kill')ov.style.background='radial-gradient(circle,rgba(255,215,0,.15),transparent 70%)';
    else if(type==='death')ov.style.background='rgba(0,0,0,.4)';
    else if(type==='revive')ov.style.background='radial-gradient(circle,rgba(255,215,0,.25),transparent 70%)';
    document.body.appendChild(ov);
    await wait(duration);
    ov.remove();this.battleSpeed=oldSpd;this._slowMo=false;
  },

  renderBF(pCards,eCards){
    const mkBc=(c)=>{
      const d=document.createElement('div');d.className=`battle-card ${c.rarity||'bronze'} ${c.currentHp<=0?'dead':''} ${c.isHero?'hero-card':''}`;d.id=`bc-${c.uid}`;
      const hp=Math.max(0,(c.currentHp/c.maxBHp)*100);const hpC=hp>50?'#44cc66':hp>25?'#ccaa44':'#cc4444';
      const eqHtml=(c.equips||[]).map(e=>`<span>${e.icon}</span>`).join('');
      const traits=getTraits(c);
      const traitHtml=traits.map(tid=>{const tr=TRAITS[tid];return tr?`<span style="color:${tr.color};" title="${tr.desc}">${tr.icon}</span>`:''}).join('');
      const imgSrc=getCardImg(c);
      d.innerHTML=`
        <div class="bc-left"><div class="bc-icon">${imgSrc?`<img src="${imgSrc}">`:c.icon}</div></div>
        <div class="bc-right">
          <div class="bc-name">${c.isHero?'⭐':''}${c.name} <span style="color:#ffd700;font-size:.45rem;">Lv${c.level||1}</span></div>
          <div class="bc-stats"><span class="st-atk">⚔${c.atk}</span><span class="st-hp">♥${Math.max(0,Math.ceil(c.currentHp))}</span><span class="st-nrg">⚡${Math.floor(c.curNrg||0)}</span>${traitHtml?` ${traitHtml}`:''}</div>
          <div class="bc-bars"><div class="bc-bar"><div class="bc-bar-fill" style="width:${hp}%;background:${hpC}"></div></div>
          <div class="bc-bar"><div class="bc-bar-fill" style="width:${Math.min(100,((c.curNrg||0)/(c.skillNrg||10))*100)}%;background:#44aaff"></div></div></div>
        </div>${eqHtml?`<div class="bc-equips" style="position:absolute;top:1px;right:2px;">${eqHtml}</div>`:''}`;
      return d;};
    const renderSide=(cards,id)=>{
      const ct=document.getElementById(id);ct.innerHTML='';
      const front=cards.filter(c=>c.row==='front').slice(0,3);
      const back=cards.filter(c=>c.row==='back').slice(0,3);
      const isEnemy=id==='enemy-side';
      // Enemy: back(뒷열) on top, front(앞열) bottom. Player: front(앞열) top, back(뒷열) bottom.
      const topRow=isEnemy?back:front;const botRow=isEnemy?front:back;
      const topLabel=isEnemy?'뒷열':'앞열';const botLabel=isEnemy?'앞열':'뒷열';
      if(topRow.length){
        const r=document.createElement('div');r.className='battle-row';
        topRow.forEach(c=>r.appendChild(mkBc(c)));ct.appendChild(r);
      }
      if(botRow.length){
        const r=document.createElement('div');r.className='battle-row';
        botRow.forEach(c=>{const bc=mkBc(c);bc.style.transform='scale(.88)';r.appendChild(bc);});ct.appendChild(r);
      }
    };
    renderSide(eCards,'enemy-side');renderSide(pCards,'player-side');
    // Make enemy cards clickable for targeting
    eCards.filter(c=>c.currentHp>0).forEach(c=>{
      const el=document.getElementById(`bc-${c.uid}`);
      if(el&&!this._targetMode){
        el.style.cursor='pointer';
        el.onclick=()=>{this.setPlayerTarget(c.uid);SFX.play('click');};
      }
    });
    // Update skill bar
    this.updateSkillBar();
  },

  // ---- RESULT ----
  _lootPicked:false,
  afterBattle(){
    if(!this._lootPicked){
      UI.modal('⚠️ 전리품 미회수','전리품을 선택하지 않고 떠나시겠습니까?\n선택하지 않은 보상은 사라집니다.',()=>{this._lootPicked=false;this.showMenu();});
      return;
    }
    this._lootPicked=false;this.showMenu();
  },

  rerollPick(){
    if(!this._currentPickAction)return;
    if(this.gold<2){document.getElementById('pick-sub').textContent='⚠️ 골드 부족! (2💰 필요)';return;}
    this.gold-=2;this.persist();SFX.play('click');
    this.doRoundChoice(this._currentPickAction);
  },

  finishPick(){
    this.persist();
    if(this.battleState){
      const bs=this.battleState;
      bs._apRemaining=Math.max(0,(bs._apRemaining||1)-1);
      if(bs._apRemaining>0){
        this.showRoundChoice();
        return;
      }
      this._stopRoundTimer();
      this._revealAndFinish();
    } else {
      this.showMenu();
    }
  },
  finishRound(){
    this._stopRoundTimer();
    this.persist();
    if(this.battleState){
      try{this.askFormationForNextRound();}catch(e){console.error('finishRound error:',e);this.showMenu();}
    } else {
      this.showMenu();
    }
  },

  askFormationForNextRound(){
    if(!this.battleState){this.showMenu();return;}
    // Close any existing modal first
    UI.closeModal();
    setTimeout(()=>{
      const ov=document.getElementById('modal-overlay');
      const rd=this.battleState.currentRound+1;
      document.getElementById('modal-title').textContent=`라운드 ${rd} 준비`;
      document.getElementById('modal-msg').textContent=`배치를 변경하시겠습니까? (다음: ${rd}번 공격)`;
      const mb=document.querySelector('#modal-overlay .modal-buttons');
      mb.innerHTML='';
      const b1=document.createElement('button');b1.className='btn btn-s btn-green';b1.textContent='배치 변경';
      b1.onclick=()=>{ov.classList.remove('active');Formation.showForBattle(this.battleState.pCards);};
      const b2=document.createElement('button');b2.className='btn btn-s';b2.textContent='그대로 진군!';
      b2.onclick=()=>{ov.classList.remove('active');this.launchBattle();};
      mb.appendChild(b1);mb.appendChild(b2);
      ov.classList.add('active');
    },100);
  },

  // ---- GAMEOVER ----
  newRun(){
    const u=UNITS.find(x=>x.id===this.heroBaseId)||UNITS[0];
    const hero={...u,uid:uid(),name:Auth.user,heroClass:u.name,isHero:true,rarity:'bronze',level:1,equips:[],maxHp:u.hp,xp:0,honor:0,freePoints:0,growthPts:{atk:0,hp:0,def:0,spd:0,nrg:0,luck:0,eva:0}};
    this.round=0;this.hp=3;this.maxHp=3;this.gold=2;
    this.deck=[hero];this.relics=[];this.ownedRelics=[];this.ownedSkills=[];this.totalGames++;this.persist();this.showMenu();
  },
});
