// Game Effects (이펙트 메서드)
// Generated by docs/_split_game.py — Phase 4
// DO NOT hand-edit keys — edit in original and re-run splitter if needed.

RoF.__gameKeys = RoF.__gameKeys || new Set();
(function(keys){
  for (const k of keys) {
    if (RoF.__gameKeys.has(k)) {
      console.error('[Game] 중복 키 감지:', k);
      RoF.__gameKeyError = true;
    }
    RoF.__gameKeys.add(k);
  }
})(["showAtkEffect", "showDmg", "showHeal", "showAbilEff", "showGameOver"]);

Object.assign(RoF.Game, {
  showAtkEffect(attacker,target){
    const el=document.getElementById(`bc-${target.uid}`);if(!el)return;
    const rect=el.getBoundingClientRect();
    const eff=document.createElement('div');
    const type=attacker.type;
    const elem=attacker.element;
    // Use AI effect images based on element/type
    let fxImg='';
    if(type==='마법사'&&elem){fxImg=`img/fx_${elem}.png`;}
    else if(type==='전사'){fxImg='img/fx_slash.png';}
    else if(type==='사수'){fxImg='img/fx_arrow.png';}
    else{fxImg='img/fx_smash.png';}
    if(fxImg){
      eff.className='slash-effect';
      eff.innerHTML=`<img src="${fxImg}" style="width:60px;height:60px;object-fit:contain;">`;
    } else {
      if(type==='전사'){eff.className='slash-effect';eff.textContent='⚔️';}
      else if(type==='마법사'){eff.className='magic-effect';eff.textContent='✨';}
      else if(type==='사수'){eff.className='slash-effect';eff.textContent='🏹';}
      else{eff.className='slash-effect';eff.textContent='🐾';}
    }
    eff.style.left=rect.left+rect.width/2-30+'px';eff.style.top=rect.top+rect.height/2-30+'px';
    document.body.appendChild(eff);setTimeout(()=>eff.remove(),600);
    // Hit shake
    el.classList.remove('hit-anim','hit-flash','crit-hit');void el.offsetWidth;
    el.classList.add('hit-flash');setTimeout(()=>el.classList.remove('hit-flash'),400);
  },

  showDmg(u,d,crit){const el=document.getElementById(`bc-${u.uid}`);if(!el)return;const n=document.createElement('div');n.className='damage-number';if(crit){n.style.fontSize='1.4rem';n.style.color='#ffaa00';}n.textContent=`-${d}${crit?'!!':''}`;n.style.left=Math.random()*30+20+'px';n.style.top='5px';el.appendChild(n);setTimeout(()=>n.remove(),800);
    if(crit){SFX.play('crit');const bs=document.getElementById('battle-screen');if(bs){bs.classList.remove('screen-shake');void bs.offsetWidth;bs.classList.add('screen-shake');setTimeout(()=>bs.classList.remove('screen-shake'),300);}
      const cf=document.createElement('div');cf.className='crit-flash';document.body.appendChild(cf);setTimeout(()=>cf.remove(),300);
      this.triggerSlowMo(1200,'crit');}},
  showHeal(u,a){const el=document.getElementById(`bc-${u.uid}`);if(!el)return;const n=document.createElement('div');n.className='damage-number heal-number';n.textContent=`+${a}`;n.style.left=Math.random()*30+20+'px';n.style.top='5px';el.appendChild(n);setTimeout(()=>n.remove(),800);},
  showAbilEff(u,emoji){const el=document.getElementById(`bc-${u.uid}`);if(!el)return;const rect=el.getBoundingClientRect();const e=document.createElement('div');e.className='heal-effect';e.textContent=emoji;e.style.left=rect.left+rect.width/2-15+'px';e.style.top=rect.top+'px';document.body.appendChild(e);setTimeout(()=>e.remove(),600);},
  showGameOver(){
    UI.show('gameover-screen');SFX.bgm(false);
    const hero=this.deck.find(c=>c.isHero);
    document.getElementById('final-stats').innerHTML=`모험자: <strong style="color:#ffd700">${Auth.user}</strong><br>영웅: ${hero?hero.icon+' Lv.'+hero.level:'?'}<br>최고 라운드: <strong style="color:#ffd700">${this.bestRound}</strong><br>💰${this.gold} | ⭐${this.getTotalHonor()}<br>총 승리: ${this.totalWins}회<br>전력: ${this.deck.map(c=>c.icon).join(' ')}`;
  },

});
