const {chromium}=require("playwright");
const path=require("path");
const ROOT=path.resolve(__dirname,"..");
const FILE="file:///"+path.join(ROOT,"index.html").split(path.sep).join("/");
(async()=>{
const b=await chromium.launch();
const p=await b.newPage({viewport:{width:1400,height:900}});
const errs=[]; p.on("pageerror",e=>errs.push(e.message));
await p.goto(FILE); await p.waitForTimeout(600);
await p.evaluate(()=>UI.show("signup-screen"));
await p.waitForTimeout(200);
const u="_xct_"+Date.now();
await p.fill("#signup-id",u);
await p.fill("#signup-pw","1234");
await p.fill("#signup-pw2","1234");
await p.evaluate(()=>Auth.signup());
await p.waitForTimeout(1500);
const disp=await p.evaluate(()=>{const s=document.querySelector("#char-select-screen");return s?getComputedStyle(s).display:"missing";});
console.log("char-select display:",disp);
await p.evaluate(()=>{ if(typeof Auth!=="undefined" && Auth.skipPrologue) Auth.skipPrologue(); });
await p.waitForTimeout(500);
await p.screenshot({path:path.join(ROOT,"shots/meeting-char-select-step1.png")});
const step1=await p.evaluate(()=>{const opts=[...document.querySelectorAll(".char-option")];return {optionCount:opts.length,v2cards:document.querySelectorAll(".card-v2").length,firstHTML:opts[0]?opts[0].outerHTML.slice(0,400):null};});
console.log("STEP1:",JSON.stringify(step1,null,2));
await p.evaluate(()=>{document.querySelector(".char-option")?.click();});
await p.waitForTimeout(150);
await p.evaluate(()=>Auth.confirmChar());
await p.waitForTimeout(500);
await p.screenshot({path:path.join(ROOT,"shots/meeting-char-select-step2.png")});
const step2=await p.evaluate(()=>{const opts=[...document.querySelectorAll(".char-option")];return {optionCount:opts.length,v2cards:document.querySelectorAll(".card-v2").length,texts:opts.map(o=>o.textContent.replace(/s+/g," ").trim().slice(0,150)),firstHTML:opts[0]?opts[0].outerHTML.slice(0,700):null,coords:opts.map(o=>{const cr=o.getBoundingClientRect();const pick=sel=>{const e=o.querySelector(sel);if(!e)return null;const r=e.getBoundingClientRect();return{x:+(((r.left+r.width/2)-cr.left)/cr.width*100).toFixed(1),y:+(((r.top+r.height/2)-cr.top)/cr.height*100).toFixed(1),txt:e.textContent.trim()};};return{w:+cr.width.toFixed(0),h:+cr.height.toFixed(0),atk:pick(".st-atk"),hp:pick(".st-hp"),def:pick(".st-def"),spd:pick(".st-spd")};})};});
console.log("STEP2:",JSON.stringify(step2,null,2));
await p.evaluate(()=>{document.querySelector(".char-option")?.click();});
await p.waitForTimeout(150);
await p.evaluate(()=>Auth.confirmChar());
await p.waitForTimeout(800);
await p.evaluate(()=>{if(typeof Game!=="undefined" && Game.showDeckView) Game.showDeckView();});
await p.waitForTimeout(600);
await p.screenshot({path:path.join(ROOT,"shots/meeting-char-deckview.png")});
const dv=await p.evaluate(()=>{const cards=[...document.querySelectorAll(".card-v2")];return {count:cards.length,first:cards[0]?cards[0].className:null};});
console.log("DECKVIEW:",JSON.stringify(dv,null,2));
console.log("ERRS:",errs);
await b.close();
})();
